/*
 * db-vendo-client
 * Schema for db-vendo-client/hafas-rest-api's Friendly Public Transport Format REST API
 *
 * The version of the OpenAPI document: 6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.olech2412.dbvendowrapper.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Alternative
 */
@JsonPropertyOrder({
        Alternative.JSON_PROPERTY_TRIP_ID,
        Alternative.JSON_PROPERTY_DIRECTION,
        Alternative.JSON_PROPERTY_LOCATION,
        Alternative.JSON_PROPERTY_LINE,
        Alternative.JSON_PROPERTY_STOP,
        Alternative.JSON_PROPERTY_WHEN,
        Alternative.JSON_PROPERTY_PLANNED_WHEN,
        Alternative.JSON_PROPERTY_PROGNOSED_WHEN,
        Alternative.JSON_PROPERTY_DELAY,
        Alternative.JSON_PROPERTY_PLATFORM,
        Alternative.JSON_PROPERTY_PLANNED_PLATFORM,
        Alternative.JSON_PROPERTY_PROGNOSED_PLATFORM,
        Alternative.JSON_PROPERTY_REMARKS,
        Alternative.JSON_PROPERTY_CANCELLED,
        Alternative.JSON_PROPERTY_LOAD_FACTOR,
        Alternative.JSON_PROPERTY_PROVENANCE,
        Alternative.JSON_PROPERTY_PREVIOUS_STOPOVERS,
        Alternative.JSON_PROPERTY_NEXT_STOPOVERS,
        Alternative.JSON_PROPERTY_FRAMES,
        Alternative.JSON_PROPERTY_POLYLINE,
        Alternative.JSON_PROPERTY_CURRENT_TRIP_POSITION,
        Alternative.JSON_PROPERTY_ORIGIN,
        Alternative.JSON_PROPERTY_DESTINATION,
        Alternative.JSON_PROPERTY_PROGNOSIS_TYPE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-11T16:58:48.518685525+02:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class Alternative {
    public static final String JSON_PROPERTY_TRIP_ID = "tripId";
    public static final String JSON_PROPERTY_DIRECTION = "direction";
    public static final String JSON_PROPERTY_LOCATION = "location";
    public static final String JSON_PROPERTY_LINE = "line";
    public static final String JSON_PROPERTY_STOP = "stop";
    public static final String JSON_PROPERTY_WHEN = "when";
    public static final String JSON_PROPERTY_PLANNED_WHEN = "plannedWhen";
    public static final String JSON_PROPERTY_PROGNOSED_WHEN = "prognosedWhen";
    public static final String JSON_PROPERTY_DELAY = "delay";
    public static final String JSON_PROPERTY_PLATFORM = "platform";
    public static final String JSON_PROPERTY_PLANNED_PLATFORM = "plannedPlatform";
    public static final String JSON_PROPERTY_PROGNOSED_PLATFORM = "prognosedPlatform";
    public static final String JSON_PROPERTY_REMARKS = "remarks";
    public static final String JSON_PROPERTY_CANCELLED = "cancelled";
    public static final String JSON_PROPERTY_LOAD_FACTOR = "loadFactor";
    public static final String JSON_PROPERTY_PROVENANCE = "provenance";
    public static final String JSON_PROPERTY_PREVIOUS_STOPOVERS = "previousStopovers";
    public static final String JSON_PROPERTY_NEXT_STOPOVERS = "nextStopovers";
    public static final String JSON_PROPERTY_FRAMES = "frames";
    public static final String JSON_PROPERTY_POLYLINE = "polyline";
    public static final String JSON_PROPERTY_CURRENT_TRIP_POSITION = "currentTripPosition";
    public static final String JSON_PROPERTY_ORIGIN = "origin";
    public static final String JSON_PROPERTY_DESTINATION = "destination";
    public static final String JSON_PROPERTY_PROGNOSIS_TYPE = "prognosisType";
    @jakarta.annotation.Nullable
    private String tripId;
    @jakarta.annotation.Nullable
    private String direction;
    @jakarta.annotation.Nullable
    private Location location;
    @jakarta.annotation.Nullable
    private Line line;
    @jakarta.annotation.Nullable
    private StopOverStop stop;
    @jakarta.annotation.Nullable
    private String when;
    @jakarta.annotation.Nullable
    private String plannedWhen;
    @jakarta.annotation.Nullable
    private String prognosedWhen;
    @jakarta.annotation.Nullable
    private BigDecimal delay;
    @jakarta.annotation.Nullable
    private String platform;
    @jakarta.annotation.Nullable
    private String plannedPlatform;
    @jakarta.annotation.Nullable
    private String prognosedPlatform;
    @jakarta.annotation.Nullable
    private List<StopOverRemarksInner> remarks = new ArrayList<>();
    @jakarta.annotation.Nullable
    private Boolean cancelled;
    @jakarta.annotation.Nullable
    private String loadFactor;
    @jakarta.annotation.Nullable
    private String provenance;
    @jakarta.annotation.Nullable
    private List<StopOver> previousStopovers = new ArrayList<>();
    @jakarta.annotation.Nullable
    private List<StopOver> nextStopovers = new ArrayList<>();
    @jakarta.annotation.Nullable
    private List<Frame> frames = new ArrayList<>();
    @jakarta.annotation.Nullable
    private FeatureCollection polyline;
    @jakarta.annotation.Nullable
    private Location currentTripPosition;
    @jakarta.annotation.Nullable
    private StopsIdGet2XXResponse origin;
    @jakarta.annotation.Nullable
    private StopsIdGet2XXResponse destination;
    @jakarta.annotation.Nullable
    private PrognosisType prognosisType;

    public Alternative() {
    }

    public Alternative tripId(@jakarta.annotation.Nullable String tripId) {

        this.tripId = tripId;
        return this;
    }

    /**
     * Get tripId
     *
     * @return tripId
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TRIP_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getTripId() {
        return tripId;
    }


    @JsonProperty(JSON_PROPERTY_TRIP_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTripId(@jakarta.annotation.Nullable String tripId) {
        this.tripId = tripId;
    }

    public Alternative direction(@jakarta.annotation.Nullable String direction) {

        this.direction = direction;
        return this;
    }

    /**
     * Get direction
     *
     * @return direction
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DIRECTION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDirection() {
        return direction;
    }


    @JsonProperty(JSON_PROPERTY_DIRECTION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDirection(@jakarta.annotation.Nullable String direction) {
        this.direction = direction;
    }

    public Alternative location(@jakarta.annotation.Nullable Location location) {

        this.location = location;
        return this;
    }

    /**
     * Get location
     *
     * @return location
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LOCATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Location getLocation() {
        return location;
    }


    @JsonProperty(JSON_PROPERTY_LOCATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLocation(@jakarta.annotation.Nullable Location location) {
        this.location = location;
    }

    public Alternative line(@jakarta.annotation.Nullable Line line) {

        this.line = line;
        return this;
    }

    /**
     * Get line
     *
     * @return line
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LINE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Line getLine() {
        return line;
    }


    @JsonProperty(JSON_PROPERTY_LINE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLine(@jakarta.annotation.Nullable Line line) {
        this.line = line;
    }

    public Alternative stop(@jakarta.annotation.Nullable StopOverStop stop) {

        this.stop = stop;
        return this;
    }

    /**
     * Get stop
     *
     * @return stop
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_STOP)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public StopOverStop getStop() {
        return stop;
    }


    @JsonProperty(JSON_PROPERTY_STOP)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStop(@jakarta.annotation.Nullable StopOverStop stop) {
        this.stop = stop;
    }

    public Alternative when(@jakarta.annotation.Nullable String when) {

        this.when = when;
        return this;
    }

    /**
     * Get when
     *
     * @return when
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_WHEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getWhen() {
        return when;
    }


    @JsonProperty(JSON_PROPERTY_WHEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setWhen(@jakarta.annotation.Nullable String when) {
        this.when = when;
    }

    public Alternative plannedWhen(@jakarta.annotation.Nullable String plannedWhen) {

        this.plannedWhen = plannedWhen;
        return this;
    }

    /**
     * Get plannedWhen
     *
     * @return plannedWhen
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PLANNED_WHEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPlannedWhen() {
        return plannedWhen;
    }


    @JsonProperty(JSON_PROPERTY_PLANNED_WHEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPlannedWhen(@jakarta.annotation.Nullable String plannedWhen) {
        this.plannedWhen = plannedWhen;
    }

    public Alternative prognosedWhen(@jakarta.annotation.Nullable String prognosedWhen) {

        this.prognosedWhen = prognosedWhen;
        return this;
    }

    /**
     * Get prognosedWhen
     *
     * @return prognosedWhen
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PROGNOSED_WHEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPrognosedWhen() {
        return prognosedWhen;
    }


    @JsonProperty(JSON_PROPERTY_PROGNOSED_WHEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPrognosedWhen(@jakarta.annotation.Nullable String prognosedWhen) {
        this.prognosedWhen = prognosedWhen;
    }

    public Alternative delay(@jakarta.annotation.Nullable BigDecimal delay) {

        this.delay = delay;
        return this;
    }

    /**
     * Get delay
     *
     * @return delay
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DELAY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getDelay() {
        return delay;
    }


    @JsonProperty(JSON_PROPERTY_DELAY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDelay(@jakarta.annotation.Nullable BigDecimal delay) {
        this.delay = delay;
    }

    public Alternative platform(@jakarta.annotation.Nullable String platform) {

        this.platform = platform;
        return this;
    }

    /**
     * Get platform
     *
     * @return platform
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPlatform() {
        return platform;
    }


    @JsonProperty(JSON_PROPERTY_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPlatform(@jakarta.annotation.Nullable String platform) {
        this.platform = platform;
    }

    public Alternative plannedPlatform(@jakarta.annotation.Nullable String plannedPlatform) {

        this.plannedPlatform = plannedPlatform;
        return this;
    }

    /**
     * Get plannedPlatform
     *
     * @return plannedPlatform
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PLANNED_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPlannedPlatform() {
        return plannedPlatform;
    }


    @JsonProperty(JSON_PROPERTY_PLANNED_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPlannedPlatform(@jakarta.annotation.Nullable String plannedPlatform) {
        this.plannedPlatform = plannedPlatform;
    }

    public Alternative prognosedPlatform(@jakarta.annotation.Nullable String prognosedPlatform) {

        this.prognosedPlatform = prognosedPlatform;
        return this;
    }

    /**
     * Get prognosedPlatform
     *
     * @return prognosedPlatform
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PROGNOSED_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPrognosedPlatform() {
        return prognosedPlatform;
    }


    @JsonProperty(JSON_PROPERTY_PROGNOSED_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPrognosedPlatform(@jakarta.annotation.Nullable String prognosedPlatform) {
        this.prognosedPlatform = prognosedPlatform;
    }

    public Alternative remarks(@jakarta.annotation.Nullable List<StopOverRemarksInner> remarks) {

        this.remarks = remarks;
        return this;
    }

    public Alternative addRemarksItem(StopOverRemarksInner remarksItem) {
        if (this.remarks == null) {
            this.remarks = new ArrayList<>();
        }
        this.remarks.add(remarksItem);
        return this;
    }

    /**
     * Get remarks
     *
     * @return remarks
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_REMARKS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<StopOverRemarksInner> getRemarks() {
        return remarks;
    }


    @JsonProperty(JSON_PROPERTY_REMARKS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRemarks(@jakarta.annotation.Nullable List<StopOverRemarksInner> remarks) {
        this.remarks = remarks;
    }

    public Alternative cancelled(@jakarta.annotation.Nullable Boolean cancelled) {

        this.cancelled = cancelled;
        return this;
    }

    /**
     * Get cancelled
     *
     * @return cancelled
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CANCELLED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getCancelled() {
        return cancelled;
    }


    @JsonProperty(JSON_PROPERTY_CANCELLED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCancelled(@jakarta.annotation.Nullable Boolean cancelled) {
        this.cancelled = cancelled;
    }

    public Alternative loadFactor(@jakarta.annotation.Nullable String loadFactor) {

        this.loadFactor = loadFactor;
        return this;
    }

    /**
     * Get loadFactor
     *
     * @return loadFactor
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LOAD_FACTOR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getLoadFactor() {
        return loadFactor;
    }


    @JsonProperty(JSON_PROPERTY_LOAD_FACTOR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLoadFactor(@jakarta.annotation.Nullable String loadFactor) {
        this.loadFactor = loadFactor;
    }

    public Alternative provenance(@jakarta.annotation.Nullable String provenance) {

        this.provenance = provenance;
        return this;
    }

    /**
     * Get provenance
     *
     * @return provenance
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PROVENANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getProvenance() {
        return provenance;
    }


    @JsonProperty(JSON_PROPERTY_PROVENANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProvenance(@jakarta.annotation.Nullable String provenance) {
        this.provenance = provenance;
    }

    public Alternative previousStopovers(@jakarta.annotation.Nullable List<StopOver> previousStopovers) {

        this.previousStopovers = previousStopovers;
        return this;
    }

    public Alternative addPreviousStopoversItem(StopOver previousStopoversItem) {
        if (this.previousStopovers == null) {
            this.previousStopovers = new ArrayList<>();
        }
        this.previousStopovers.add(previousStopoversItem);
        return this;
    }

    /**
     * Get previousStopovers
     *
     * @return previousStopovers
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PREVIOUS_STOPOVERS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<StopOver> getPreviousStopovers() {
        return previousStopovers;
    }


    @JsonProperty(JSON_PROPERTY_PREVIOUS_STOPOVERS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPreviousStopovers(@jakarta.annotation.Nullable List<StopOver> previousStopovers) {
        this.previousStopovers = previousStopovers;
    }

    public Alternative nextStopovers(@jakarta.annotation.Nullable List<StopOver> nextStopovers) {

        this.nextStopovers = nextStopovers;
        return this;
    }

    public Alternative addNextStopoversItem(StopOver nextStopoversItem) {
        if (this.nextStopovers == null) {
            this.nextStopovers = new ArrayList<>();
        }
        this.nextStopovers.add(nextStopoversItem);
        return this;
    }

    /**
     * Get nextStopovers
     *
     * @return nextStopovers
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_NEXT_STOPOVERS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<StopOver> getNextStopovers() {
        return nextStopovers;
    }


    @JsonProperty(JSON_PROPERTY_NEXT_STOPOVERS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNextStopovers(@jakarta.annotation.Nullable List<StopOver> nextStopovers) {
        this.nextStopovers = nextStopovers;
    }

    public Alternative frames(@jakarta.annotation.Nullable List<Frame> frames) {

        this.frames = frames;
        return this;
    }

    public Alternative addFramesItem(Frame framesItem) {
        if (this.frames == null) {
            this.frames = new ArrayList<>();
        }
        this.frames.add(framesItem);
        return this;
    }

    /**
     * Get frames
     *
     * @return frames
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_FRAMES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<Frame> getFrames() {
        return frames;
    }


    @JsonProperty(JSON_PROPERTY_FRAMES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFrames(@jakarta.annotation.Nullable List<Frame> frames) {
        this.frames = frames;
    }

    public Alternative polyline(@jakarta.annotation.Nullable FeatureCollection polyline) {

        this.polyline = polyline;
        return this;
    }

    /**
     * Get polyline
     *
     * @return polyline
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_POLYLINE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public FeatureCollection getPolyline() {
        return polyline;
    }


    @JsonProperty(JSON_PROPERTY_POLYLINE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPolyline(@jakarta.annotation.Nullable FeatureCollection polyline) {
        this.polyline = polyline;
    }

    public Alternative currentTripPosition(@jakarta.annotation.Nullable Location currentTripPosition) {

        this.currentTripPosition = currentTripPosition;
        return this;
    }

    /**
     * Get currentTripPosition
     *
     * @return currentTripPosition
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CURRENT_TRIP_POSITION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Location getCurrentTripPosition() {
        return currentTripPosition;
    }


    @JsonProperty(JSON_PROPERTY_CURRENT_TRIP_POSITION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCurrentTripPosition(@jakarta.annotation.Nullable Location currentTripPosition) {
        this.currentTripPosition = currentTripPosition;
    }

    public Alternative origin(@jakarta.annotation.Nullable StopsIdGet2XXResponse origin) {

        this.origin = origin;
        return this;
    }

    /**
     * Get origin
     *
     * @return origin
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ORIGIN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public StopsIdGet2XXResponse getOrigin() {
        return origin;
    }


    @JsonProperty(JSON_PROPERTY_ORIGIN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setOrigin(@jakarta.annotation.Nullable StopsIdGet2XXResponse origin) {
        this.origin = origin;
    }

    public Alternative destination(@jakarta.annotation.Nullable StopsIdGet2XXResponse destination) {

        this.destination = destination;
        return this;
    }

    /**
     * Get destination
     *
     * @return destination
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DESTINATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public StopsIdGet2XXResponse getDestination() {
        return destination;
    }


    @JsonProperty(JSON_PROPERTY_DESTINATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDestination(@jakarta.annotation.Nullable StopsIdGet2XXResponse destination) {
        this.destination = destination;
    }

    public Alternative prognosisType(@jakarta.annotation.Nullable PrognosisType prognosisType) {

        this.prognosisType = prognosisType;
        return this;
    }

    /**
     * Get prognosisType
     *
     * @return prognosisType
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PROGNOSIS_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public PrognosisType getPrognosisType() {
        return prognosisType;
    }


    @JsonProperty(JSON_PROPERTY_PROGNOSIS_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPrognosisType(@jakarta.annotation.Nullable PrognosisType prognosisType) {
        this.prognosisType = prognosisType;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Alternative alternative = (Alternative) o;
        return Objects.equals(this.tripId, alternative.tripId) &&
                Objects.equals(this.direction, alternative.direction) &&
                Objects.equals(this.location, alternative.location) &&
                Objects.equals(this.line, alternative.line) &&
                Objects.equals(this.stop, alternative.stop) &&
                Objects.equals(this.when, alternative.when) &&
                Objects.equals(this.plannedWhen, alternative.plannedWhen) &&
                Objects.equals(this.prognosedWhen, alternative.prognosedWhen) &&
                Objects.equals(this.delay, alternative.delay) &&
                Objects.equals(this.platform, alternative.platform) &&
                Objects.equals(this.plannedPlatform, alternative.plannedPlatform) &&
                Objects.equals(this.prognosedPlatform, alternative.prognosedPlatform) &&
                Objects.equals(this.remarks, alternative.remarks) &&
                Objects.equals(this.cancelled, alternative.cancelled) &&
                Objects.equals(this.loadFactor, alternative.loadFactor) &&
                Objects.equals(this.provenance, alternative.provenance) &&
                Objects.equals(this.previousStopovers, alternative.previousStopovers) &&
                Objects.equals(this.nextStopovers, alternative.nextStopovers) &&
                Objects.equals(this.frames, alternative.frames) &&
                Objects.equals(this.polyline, alternative.polyline) &&
                Objects.equals(this.currentTripPosition, alternative.currentTripPosition) &&
                Objects.equals(this.origin, alternative.origin) &&
                Objects.equals(this.destination, alternative.destination) &&
                Objects.equals(this.prognosisType, alternative.prognosisType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(tripId, direction, location, line, stop, when, plannedWhen, prognosedWhen, delay, platform, plannedPlatform, prognosedPlatform, remarks, cancelled, loadFactor, provenance, previousStopovers, nextStopovers, frames, polyline, currentTripPosition, origin, destination, prognosisType);
    }

    @Override
    public String toString() {
        String sb = "class Alternative {\n" +
                "    tripId: " + toIndentedString(tripId) + "\n" +
                "    direction: " + toIndentedString(direction) + "\n" +
                "    location: " + toIndentedString(location) + "\n" +
                "    line: " + toIndentedString(line) + "\n" +
                "    stop: " + toIndentedString(stop) + "\n" +
                "    when: " + toIndentedString(when) + "\n" +
                "    plannedWhen: " + toIndentedString(plannedWhen) + "\n" +
                "    prognosedWhen: " + toIndentedString(prognosedWhen) + "\n" +
                "    delay: " + toIndentedString(delay) + "\n" +
                "    platform: " + toIndentedString(platform) + "\n" +
                "    plannedPlatform: " + toIndentedString(plannedPlatform) + "\n" +
                "    prognosedPlatform: " + toIndentedString(prognosedPlatform) + "\n" +
                "    remarks: " + toIndentedString(remarks) + "\n" +
                "    cancelled: " + toIndentedString(cancelled) + "\n" +
                "    loadFactor: " + toIndentedString(loadFactor) + "\n" +
                "    provenance: " + toIndentedString(provenance) + "\n" +
                "    previousStopovers: " + toIndentedString(previousStopovers) + "\n" +
                "    nextStopovers: " + toIndentedString(nextStopovers) + "\n" +
                "    frames: " + toIndentedString(frames) + "\n" +
                "    polyline: " + toIndentedString(polyline) + "\n" +
                "    currentTripPosition: " + toIndentedString(currentTripPosition) + "\n" +
                "    origin: " + toIndentedString(origin) + "\n" +
                "    destination: " + toIndentedString(destination) + "\n" +
                "    prognosisType: " + toIndentedString(prognosisType) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

