/*
 * db-vendo-client
 * Schema for db-vendo-client/hafas-rest-api's Friendly Public Transport Format REST API
 *
 * The version of the OpenAPI document: 6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.olech2412.dbvendowrapper.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Leg of journey
 */
@JsonPropertyOrder({
        Leg.JSON_PROPERTY_TRIP_ID,
        Leg.JSON_PROPERTY_ORIGIN,
        Leg.JSON_PROPERTY_DESTINATION,
        Leg.JSON_PROPERTY_DEPARTURE,
        Leg.JSON_PROPERTY_PLANNED_DEPARTURE,
        Leg.JSON_PROPERTY_PROGNOSED_ARRIVAL,
        Leg.JSON_PROPERTY_DEPARTURE_DELAY,
        Leg.JSON_PROPERTY_DEPARTURE_PLATFORM,
        Leg.JSON_PROPERTY_PROGNOSED_DEPARTURE_PLATFORM,
        Leg.JSON_PROPERTY_PLANNED_DEPARTURE_PLATFORM,
        Leg.JSON_PROPERTY_ARRIVAL,
        Leg.JSON_PROPERTY_PLANNED_ARRIVAL,
        Leg.JSON_PROPERTY_PROGNOSED_DEPARTURE,
        Leg.JSON_PROPERTY_ARRIVAL_DELAY,
        Leg.JSON_PROPERTY_ARRIVAL_PLATFORM,
        Leg.JSON_PROPERTY_PROGNOSED_ARRIVAL_PLATFORM,
        Leg.JSON_PROPERTY_PLANNED_ARRIVAL_PLATFORM,
        Leg.JSON_PROPERTY_STOPOVERS,
        Leg.JSON_PROPERTY_SCHEDULE,
        Leg.JSON_PROPERTY_PRICE,
        Leg.JSON_PROPERTY_OPERATOR,
        Leg.JSON_PROPERTY_DIRECTION,
        Leg.JSON_PROPERTY_LINE,
        Leg.JSON_PROPERTY_REACHABLE,
        Leg.JSON_PROPERTY_CANCELLED,
        Leg.JSON_PROPERTY_WALKING,
        Leg.JSON_PROPERTY_LOAD_FACTOR,
        Leg.JSON_PROPERTY_DISTANCE,
        Leg.JSON_PROPERTY_PUBLIC,
        Leg.JSON_PROPERTY_TRANSFER,
        Leg.JSON_PROPERTY_CYCLE,
        Leg.JSON_PROPERTY_ALTERNATIVES,
        Leg.JSON_PROPERTY_POLYLINE,
        Leg.JSON_PROPERTY_REMARKS,
        Leg.JSON_PROPERTY_CURRENT_LOCATION,
        Leg.JSON_PROPERTY_DEPARTURE_PROGNOSIS_TYPE,
        Leg.JSON_PROPERTY_ARRIVAL_PROGNOSIS_TYPE,
        Leg.JSON_PROPERTY_CHECKIN
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-11T16:58:48.518685525+02:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class Leg {
    public static final String JSON_PROPERTY_TRIP_ID = "tripId";
    public static final String JSON_PROPERTY_ORIGIN = "origin";
    public static final String JSON_PROPERTY_DESTINATION = "destination";
    public static final String JSON_PROPERTY_DEPARTURE = "departure";
    public static final String JSON_PROPERTY_PLANNED_DEPARTURE = "plannedDeparture";
    public static final String JSON_PROPERTY_PROGNOSED_ARRIVAL = "prognosedArrival";
    public static final String JSON_PROPERTY_DEPARTURE_DELAY = "departureDelay";
    public static final String JSON_PROPERTY_DEPARTURE_PLATFORM = "departurePlatform";
    public static final String JSON_PROPERTY_PROGNOSED_DEPARTURE_PLATFORM = "prognosedDeparturePlatform";
    public static final String JSON_PROPERTY_PLANNED_DEPARTURE_PLATFORM = "plannedDeparturePlatform";
    public static final String JSON_PROPERTY_ARRIVAL = "arrival";
    public static final String JSON_PROPERTY_PLANNED_ARRIVAL = "plannedArrival";
    public static final String JSON_PROPERTY_PROGNOSED_DEPARTURE = "prognosedDeparture";
    public static final String JSON_PROPERTY_ARRIVAL_DELAY = "arrivalDelay";
    public static final String JSON_PROPERTY_ARRIVAL_PLATFORM = "arrivalPlatform";
    public static final String JSON_PROPERTY_PROGNOSED_ARRIVAL_PLATFORM = "prognosedArrivalPlatform";
    public static final String JSON_PROPERTY_PLANNED_ARRIVAL_PLATFORM = "plannedArrivalPlatform";
    public static final String JSON_PROPERTY_STOPOVERS = "stopovers";
    public static final String JSON_PROPERTY_SCHEDULE = "schedule";
    public static final String JSON_PROPERTY_PRICE = "price";
    public static final String JSON_PROPERTY_OPERATOR = "operator";
    public static final String JSON_PROPERTY_DIRECTION = "direction";
    public static final String JSON_PROPERTY_LINE = "line";
    public static final String JSON_PROPERTY_REACHABLE = "reachable";
    public static final String JSON_PROPERTY_CANCELLED = "cancelled";
    public static final String JSON_PROPERTY_WALKING = "walking";
    public static final String JSON_PROPERTY_LOAD_FACTOR = "loadFactor";
    public static final String JSON_PROPERTY_DISTANCE = "distance";
    public static final String JSON_PROPERTY_PUBLIC = "public";
    public static final String JSON_PROPERTY_TRANSFER = "transfer";
    public static final String JSON_PROPERTY_CYCLE = "cycle";
    public static final String JSON_PROPERTY_ALTERNATIVES = "alternatives";
    public static final String JSON_PROPERTY_POLYLINE = "polyline";
    public static final String JSON_PROPERTY_REMARKS = "remarks";
    public static final String JSON_PROPERTY_CURRENT_LOCATION = "currentLocation";
    public static final String JSON_PROPERTY_DEPARTURE_PROGNOSIS_TYPE = "departurePrognosisType";
    public static final String JSON_PROPERTY_ARRIVAL_PROGNOSIS_TYPE = "arrivalPrognosisType";
    public static final String JSON_PROPERTY_CHECKIN = "checkin";
    @jakarta.annotation.Nullable
    private String tripId;
    @jakarta.annotation.Nullable
    private StopsIdGet2XXResponse origin;
    @jakarta.annotation.Nullable
    private StopsIdGet2XXResponse destination;
    @jakarta.annotation.Nullable
    private String departure;
    @jakarta.annotation.Nullable
    private String plannedDeparture;
    @jakarta.annotation.Nullable
    private String prognosedArrival;
    @jakarta.annotation.Nullable
    private BigDecimal departureDelay;
    @jakarta.annotation.Nullable
    private String departurePlatform;
    @jakarta.annotation.Nullable
    private String prognosedDeparturePlatform;
    @jakarta.annotation.Nullable
    private String plannedDeparturePlatform;
    @jakarta.annotation.Nullable
    private String arrival;
    @jakarta.annotation.Nullable
    private String plannedArrival;
    @jakarta.annotation.Nullable
    private String prognosedDeparture;
    @jakarta.annotation.Nullable
    private BigDecimal arrivalDelay;
    @jakarta.annotation.Nullable
    private String arrivalPlatform;
    @jakarta.annotation.Nullable
    private String prognosedArrivalPlatform;
    @jakarta.annotation.Nullable
    private String plannedArrivalPlatform;
    @jakarta.annotation.Nullable
    private List<StopOver> stopovers = new ArrayList<>();
    @jakarta.annotation.Nullable
    private BigDecimal schedule;
    @jakarta.annotation.Nullable
    private Price price;
    @jakarta.annotation.Nullable
    private BigDecimal operator;
    @jakarta.annotation.Nullable
    private String direction;
    @jakarta.annotation.Nullable
    private Line line;
    @jakarta.annotation.Nullable
    private Boolean reachable;
    @jakarta.annotation.Nullable
    private Boolean cancelled;
    @jakarta.annotation.Nullable
    private Boolean walking;
    @jakarta.annotation.Nullable
    private String loadFactor;
    @jakarta.annotation.Nullable
    private BigDecimal distance;
    @jakarta.annotation.Nullable
    private Boolean _public;
    @jakarta.annotation.Nullable
    private Boolean transfer;
    @jakarta.annotation.Nullable
    private Cycle cycle;
    @jakarta.annotation.Nullable
    private List<Alternative> alternatives = new ArrayList<>();
    @jakarta.annotation.Nullable
    private FeatureCollection polyline;
    @jakarta.annotation.Nullable
    private List<StopOverRemarksInner> remarks = new ArrayList<>();
    @jakarta.annotation.Nullable
    private Location currentLocation;
    @jakarta.annotation.Nullable
    private PrognosisType departurePrognosisType;
    @jakarta.annotation.Nullable
    private PrognosisType arrivalPrognosisType;
    @jakarta.annotation.Nullable
    private Boolean checkin;

    public Leg() {
    }

    public Leg tripId(@jakarta.annotation.Nullable String tripId) {

        this.tripId = tripId;
        return this;
    }

    /**
     * Get tripId
     *
     * @return tripId
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TRIP_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getTripId() {
        return tripId;
    }


    @JsonProperty(JSON_PROPERTY_TRIP_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTripId(@jakarta.annotation.Nullable String tripId) {
        this.tripId = tripId;
    }

    public Leg origin(@jakarta.annotation.Nullable StopsIdGet2XXResponse origin) {

        this.origin = origin;
        return this;
    }

    /**
     * Get origin
     *
     * @return origin
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ORIGIN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public StopsIdGet2XXResponse getOrigin() {
        return origin;
    }


    @JsonProperty(JSON_PROPERTY_ORIGIN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setOrigin(@jakarta.annotation.Nullable StopsIdGet2XXResponse origin) {
        this.origin = origin;
    }

    public Leg destination(@jakarta.annotation.Nullable StopsIdGet2XXResponse destination) {

        this.destination = destination;
        return this;
    }

    /**
     * Get destination
     *
     * @return destination
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DESTINATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public StopsIdGet2XXResponse getDestination() {
        return destination;
    }


    @JsonProperty(JSON_PROPERTY_DESTINATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDestination(@jakarta.annotation.Nullable StopsIdGet2XXResponse destination) {
        this.destination = destination;
    }

    public Leg departure(@jakarta.annotation.Nullable String departure) {

        this.departure = departure;
        return this;
    }

    /**
     * Get departure
     *
     * @return departure
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DEPARTURE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDeparture() {
        return departure;
    }


    @JsonProperty(JSON_PROPERTY_DEPARTURE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDeparture(@jakarta.annotation.Nullable String departure) {
        this.departure = departure;
    }

    public Leg plannedDeparture(@jakarta.annotation.Nullable String plannedDeparture) {

        this.plannedDeparture = plannedDeparture;
        return this;
    }

    /**
     * Get plannedDeparture
     *
     * @return plannedDeparture
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PLANNED_DEPARTURE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPlannedDeparture() {
        return plannedDeparture;
    }


    @JsonProperty(JSON_PROPERTY_PLANNED_DEPARTURE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPlannedDeparture(@jakarta.annotation.Nullable String plannedDeparture) {
        this.plannedDeparture = plannedDeparture;
    }

    public Leg prognosedArrival(@jakarta.annotation.Nullable String prognosedArrival) {

        this.prognosedArrival = prognosedArrival;
        return this;
    }

    /**
     * Get prognosedArrival
     *
     * @return prognosedArrival
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PROGNOSED_ARRIVAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPrognosedArrival() {
        return prognosedArrival;
    }


    @JsonProperty(JSON_PROPERTY_PROGNOSED_ARRIVAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPrognosedArrival(@jakarta.annotation.Nullable String prognosedArrival) {
        this.prognosedArrival = prognosedArrival;
    }

    public Leg departureDelay(@jakarta.annotation.Nullable BigDecimal departureDelay) {

        this.departureDelay = departureDelay;
        return this;
    }

    /**
     * Get departureDelay
     *
     * @return departureDelay
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DEPARTURE_DELAY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getDepartureDelay() {
        return departureDelay;
    }


    @JsonProperty(JSON_PROPERTY_DEPARTURE_DELAY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDepartureDelay(@jakarta.annotation.Nullable BigDecimal departureDelay) {
        this.departureDelay = departureDelay;
    }

    public Leg departurePlatform(@jakarta.annotation.Nullable String departurePlatform) {

        this.departurePlatform = departurePlatform;
        return this;
    }

    /**
     * Get departurePlatform
     *
     * @return departurePlatform
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DEPARTURE_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDeparturePlatform() {
        return departurePlatform;
    }


    @JsonProperty(JSON_PROPERTY_DEPARTURE_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDeparturePlatform(@jakarta.annotation.Nullable String departurePlatform) {
        this.departurePlatform = departurePlatform;
    }

    public Leg prognosedDeparturePlatform(@jakarta.annotation.Nullable String prognosedDeparturePlatform) {

        this.prognosedDeparturePlatform = prognosedDeparturePlatform;
        return this;
    }

    /**
     * Get prognosedDeparturePlatform
     *
     * @return prognosedDeparturePlatform
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PROGNOSED_DEPARTURE_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPrognosedDeparturePlatform() {
        return prognosedDeparturePlatform;
    }


    @JsonProperty(JSON_PROPERTY_PROGNOSED_DEPARTURE_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPrognosedDeparturePlatform(@jakarta.annotation.Nullable String prognosedDeparturePlatform) {
        this.prognosedDeparturePlatform = prognosedDeparturePlatform;
    }

    public Leg plannedDeparturePlatform(@jakarta.annotation.Nullable String plannedDeparturePlatform) {

        this.plannedDeparturePlatform = plannedDeparturePlatform;
        return this;
    }

    /**
     * Get plannedDeparturePlatform
     *
     * @return plannedDeparturePlatform
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PLANNED_DEPARTURE_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPlannedDeparturePlatform() {
        return plannedDeparturePlatform;
    }


    @JsonProperty(JSON_PROPERTY_PLANNED_DEPARTURE_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPlannedDeparturePlatform(@jakarta.annotation.Nullable String plannedDeparturePlatform) {
        this.plannedDeparturePlatform = plannedDeparturePlatform;
    }

    public Leg arrival(@jakarta.annotation.Nullable String arrival) {

        this.arrival = arrival;
        return this;
    }

    /**
     * Get arrival
     *
     * @return arrival
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ARRIVAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getArrival() {
        return arrival;
    }


    @JsonProperty(JSON_PROPERTY_ARRIVAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setArrival(@jakarta.annotation.Nullable String arrival) {
        this.arrival = arrival;
    }

    public Leg plannedArrival(@jakarta.annotation.Nullable String plannedArrival) {

        this.plannedArrival = plannedArrival;
        return this;
    }

    /**
     * Get plannedArrival
     *
     * @return plannedArrival
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PLANNED_ARRIVAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPlannedArrival() {
        return plannedArrival;
    }


    @JsonProperty(JSON_PROPERTY_PLANNED_ARRIVAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPlannedArrival(@jakarta.annotation.Nullable String plannedArrival) {
        this.plannedArrival = plannedArrival;
    }

    public Leg prognosedDeparture(@jakarta.annotation.Nullable String prognosedDeparture) {

        this.prognosedDeparture = prognosedDeparture;
        return this;
    }

    /**
     * Get prognosedDeparture
     *
     * @return prognosedDeparture
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PROGNOSED_DEPARTURE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPrognosedDeparture() {
        return prognosedDeparture;
    }


    @JsonProperty(JSON_PROPERTY_PROGNOSED_DEPARTURE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPrognosedDeparture(@jakarta.annotation.Nullable String prognosedDeparture) {
        this.prognosedDeparture = prognosedDeparture;
    }

    public Leg arrivalDelay(@jakarta.annotation.Nullable BigDecimal arrivalDelay) {

        this.arrivalDelay = arrivalDelay;
        return this;
    }

    /**
     * Get arrivalDelay
     *
     * @return arrivalDelay
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ARRIVAL_DELAY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getArrivalDelay() {
        return arrivalDelay;
    }


    @JsonProperty(JSON_PROPERTY_ARRIVAL_DELAY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setArrivalDelay(@jakarta.annotation.Nullable BigDecimal arrivalDelay) {
        this.arrivalDelay = arrivalDelay;
    }

    public Leg arrivalPlatform(@jakarta.annotation.Nullable String arrivalPlatform) {

        this.arrivalPlatform = arrivalPlatform;
        return this;
    }

    /**
     * Get arrivalPlatform
     *
     * @return arrivalPlatform
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ARRIVAL_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getArrivalPlatform() {
        return arrivalPlatform;
    }


    @JsonProperty(JSON_PROPERTY_ARRIVAL_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setArrivalPlatform(@jakarta.annotation.Nullable String arrivalPlatform) {
        this.arrivalPlatform = arrivalPlatform;
    }

    public Leg prognosedArrivalPlatform(@jakarta.annotation.Nullable String prognosedArrivalPlatform) {

        this.prognosedArrivalPlatform = prognosedArrivalPlatform;
        return this;
    }

    /**
     * Get prognosedArrivalPlatform
     *
     * @return prognosedArrivalPlatform
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PROGNOSED_ARRIVAL_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPrognosedArrivalPlatform() {
        return prognosedArrivalPlatform;
    }


    @JsonProperty(JSON_PROPERTY_PROGNOSED_ARRIVAL_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPrognosedArrivalPlatform(@jakarta.annotation.Nullable String prognosedArrivalPlatform) {
        this.prognosedArrivalPlatform = prognosedArrivalPlatform;
    }

    public Leg plannedArrivalPlatform(@jakarta.annotation.Nullable String plannedArrivalPlatform) {

        this.plannedArrivalPlatform = plannedArrivalPlatform;
        return this;
    }

    /**
     * Get plannedArrivalPlatform
     *
     * @return plannedArrivalPlatform
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PLANNED_ARRIVAL_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPlannedArrivalPlatform() {
        return plannedArrivalPlatform;
    }


    @JsonProperty(JSON_PROPERTY_PLANNED_ARRIVAL_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPlannedArrivalPlatform(@jakarta.annotation.Nullable String plannedArrivalPlatform) {
        this.plannedArrivalPlatform = plannedArrivalPlatform;
    }

    public Leg stopovers(@jakarta.annotation.Nullable List<StopOver> stopovers) {

        this.stopovers = stopovers;
        return this;
    }

    public Leg addStopoversItem(StopOver stopoversItem) {
        if (this.stopovers == null) {
            this.stopovers = new ArrayList<>();
        }
        this.stopovers.add(stopoversItem);
        return this;
    }

    /**
     * Get stopovers
     *
     * @return stopovers
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_STOPOVERS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<StopOver> getStopovers() {
        return stopovers;
    }


    @JsonProperty(JSON_PROPERTY_STOPOVERS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStopovers(@jakarta.annotation.Nullable List<StopOver> stopovers) {
        this.stopovers = stopovers;
    }

    public Leg schedule(@jakarta.annotation.Nullable BigDecimal schedule) {

        this.schedule = schedule;
        return this;
    }

    /**
     * Get schedule
     *
     * @return schedule
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SCHEDULE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getSchedule() {
        return schedule;
    }


    @JsonProperty(JSON_PROPERTY_SCHEDULE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSchedule(@jakarta.annotation.Nullable BigDecimal schedule) {
        this.schedule = schedule;
    }

    public Leg price(@jakarta.annotation.Nullable Price price) {

        this.price = price;
        return this;
    }

    /**
     * Get price
     *
     * @return price
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PRICE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Price getPrice() {
        return price;
    }


    @JsonProperty(JSON_PROPERTY_PRICE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPrice(@jakarta.annotation.Nullable Price price) {
        this.price = price;
    }

    public Leg operator(@jakarta.annotation.Nullable BigDecimal operator) {

        this.operator = operator;
        return this;
    }

    /**
     * Get operator
     *
     * @return operator
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_OPERATOR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getOperator() {
        return operator;
    }


    @JsonProperty(JSON_PROPERTY_OPERATOR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setOperator(@jakarta.annotation.Nullable BigDecimal operator) {
        this.operator = operator;
    }

    public Leg direction(@jakarta.annotation.Nullable String direction) {

        this.direction = direction;
        return this;
    }

    /**
     * Get direction
     *
     * @return direction
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DIRECTION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDirection() {
        return direction;
    }


    @JsonProperty(JSON_PROPERTY_DIRECTION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDirection(@jakarta.annotation.Nullable String direction) {
        this.direction = direction;
    }

    public Leg line(@jakarta.annotation.Nullable Line line) {

        this.line = line;
        return this;
    }

    /**
     * Get line
     *
     * @return line
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LINE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Line getLine() {
        return line;
    }


    @JsonProperty(JSON_PROPERTY_LINE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLine(@jakarta.annotation.Nullable Line line) {
        this.line = line;
    }

    public Leg reachable(@jakarta.annotation.Nullable Boolean reachable) {

        this.reachable = reachable;
        return this;
    }

    /**
     * Get reachable
     *
     * @return reachable
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_REACHABLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getReachable() {
        return reachable;
    }


    @JsonProperty(JSON_PROPERTY_REACHABLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setReachable(@jakarta.annotation.Nullable Boolean reachable) {
        this.reachable = reachable;
    }

    public Leg cancelled(@jakarta.annotation.Nullable Boolean cancelled) {

        this.cancelled = cancelled;
        return this;
    }

    /**
     * Get cancelled
     *
     * @return cancelled
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CANCELLED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getCancelled() {
        return cancelled;
    }


    @JsonProperty(JSON_PROPERTY_CANCELLED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCancelled(@jakarta.annotation.Nullable Boolean cancelled) {
        this.cancelled = cancelled;
    }

    public Leg walking(@jakarta.annotation.Nullable Boolean walking) {

        this.walking = walking;
        return this;
    }

    /**
     * Get walking
     *
     * @return walking
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_WALKING)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getWalking() {
        return walking;
    }


    @JsonProperty(JSON_PROPERTY_WALKING)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setWalking(@jakarta.annotation.Nullable Boolean walking) {
        this.walking = walking;
    }

    public Leg loadFactor(@jakarta.annotation.Nullable String loadFactor) {

        this.loadFactor = loadFactor;
        return this;
    }

    /**
     * Get loadFactor
     *
     * @return loadFactor
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LOAD_FACTOR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getLoadFactor() {
        return loadFactor;
    }


    @JsonProperty(JSON_PROPERTY_LOAD_FACTOR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLoadFactor(@jakarta.annotation.Nullable String loadFactor) {
        this.loadFactor = loadFactor;
    }

    public Leg distance(@jakarta.annotation.Nullable BigDecimal distance) {

        this.distance = distance;
        return this;
    }

    /**
     * Get distance
     *
     * @return distance
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DISTANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getDistance() {
        return distance;
    }


    @JsonProperty(JSON_PROPERTY_DISTANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDistance(@jakarta.annotation.Nullable BigDecimal distance) {
        this.distance = distance;
    }

    public Leg _public(@jakarta.annotation.Nullable Boolean _public) {

        this._public = _public;
        return this;
    }

    /**
     * Get _public
     *
     * @return _public
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PUBLIC)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getPublic() {
        return _public;
    }


    @JsonProperty(JSON_PROPERTY_PUBLIC)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPublic(@jakarta.annotation.Nullable Boolean _public) {
        this._public = _public;
    }

    public Leg transfer(@jakarta.annotation.Nullable Boolean transfer) {

        this.transfer = transfer;
        return this;
    }

    /**
     * Get transfer
     *
     * @return transfer
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TRANSFER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getTransfer() {
        return transfer;
    }


    @JsonProperty(JSON_PROPERTY_TRANSFER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTransfer(@jakarta.annotation.Nullable Boolean transfer) {
        this.transfer = transfer;
    }

    public Leg cycle(@jakarta.annotation.Nullable Cycle cycle) {

        this.cycle = cycle;
        return this;
    }

    /**
     * Get cycle
     *
     * @return cycle
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CYCLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Cycle getCycle() {
        return cycle;
    }


    @JsonProperty(JSON_PROPERTY_CYCLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCycle(@jakarta.annotation.Nullable Cycle cycle) {
        this.cycle = cycle;
    }

    public Leg alternatives(@jakarta.annotation.Nullable List<Alternative> alternatives) {

        this.alternatives = alternatives;
        return this;
    }

    public Leg addAlternativesItem(Alternative alternativesItem) {
        if (this.alternatives == null) {
            this.alternatives = new ArrayList<>();
        }
        this.alternatives.add(alternativesItem);
        return this;
    }

    /**
     * Get alternatives
     *
     * @return alternatives
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ALTERNATIVES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<Alternative> getAlternatives() {
        return alternatives;
    }


    @JsonProperty(JSON_PROPERTY_ALTERNATIVES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAlternatives(@jakarta.annotation.Nullable List<Alternative> alternatives) {
        this.alternatives = alternatives;
    }

    public Leg polyline(@jakarta.annotation.Nullable FeatureCollection polyline) {

        this.polyline = polyline;
        return this;
    }

    /**
     * Get polyline
     *
     * @return polyline
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_POLYLINE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public FeatureCollection getPolyline() {
        return polyline;
    }


    @JsonProperty(JSON_PROPERTY_POLYLINE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPolyline(@jakarta.annotation.Nullable FeatureCollection polyline) {
        this.polyline = polyline;
    }

    public Leg remarks(@jakarta.annotation.Nullable List<StopOverRemarksInner> remarks) {

        this.remarks = remarks;
        return this;
    }

    public Leg addRemarksItem(StopOverRemarksInner remarksItem) {
        if (this.remarks == null) {
            this.remarks = new ArrayList<>();
        }
        this.remarks.add(remarksItem);
        return this;
    }

    /**
     * Get remarks
     *
     * @return remarks
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_REMARKS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<StopOverRemarksInner> getRemarks() {
        return remarks;
    }


    @JsonProperty(JSON_PROPERTY_REMARKS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRemarks(@jakarta.annotation.Nullable List<StopOverRemarksInner> remarks) {
        this.remarks = remarks;
    }

    public Leg currentLocation(@jakarta.annotation.Nullable Location currentLocation) {

        this.currentLocation = currentLocation;
        return this;
    }

    /**
     * Get currentLocation
     *
     * @return currentLocation
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CURRENT_LOCATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Location getCurrentLocation() {
        return currentLocation;
    }


    @JsonProperty(JSON_PROPERTY_CURRENT_LOCATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCurrentLocation(@jakarta.annotation.Nullable Location currentLocation) {
        this.currentLocation = currentLocation;
    }

    public Leg departurePrognosisType(@jakarta.annotation.Nullable PrognosisType departurePrognosisType) {

        this.departurePrognosisType = departurePrognosisType;
        return this;
    }

    /**
     * Get departurePrognosisType
     *
     * @return departurePrognosisType
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DEPARTURE_PROGNOSIS_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public PrognosisType getDeparturePrognosisType() {
        return departurePrognosisType;
    }


    @JsonProperty(JSON_PROPERTY_DEPARTURE_PROGNOSIS_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDeparturePrognosisType(@jakarta.annotation.Nullable PrognosisType departurePrognosisType) {
        this.departurePrognosisType = departurePrognosisType;
    }

    public Leg arrivalPrognosisType(@jakarta.annotation.Nullable PrognosisType arrivalPrognosisType) {

        this.arrivalPrognosisType = arrivalPrognosisType;
        return this;
    }

    /**
     * Get arrivalPrognosisType
     *
     * @return arrivalPrognosisType
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ARRIVAL_PROGNOSIS_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public PrognosisType getArrivalPrognosisType() {
        return arrivalPrognosisType;
    }


    @JsonProperty(JSON_PROPERTY_ARRIVAL_PROGNOSIS_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setArrivalPrognosisType(@jakarta.annotation.Nullable PrognosisType arrivalPrognosisType) {
        this.arrivalPrognosisType = arrivalPrognosisType;
    }

    public Leg checkin(@jakarta.annotation.Nullable Boolean checkin) {

        this.checkin = checkin;
        return this;
    }

    /**
     * Get checkin
     *
     * @return checkin
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CHECKIN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getCheckin() {
        return checkin;
    }


    @JsonProperty(JSON_PROPERTY_CHECKIN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCheckin(@jakarta.annotation.Nullable Boolean checkin) {
        this.checkin = checkin;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Leg leg = (Leg) o;
        return Objects.equals(this.tripId, leg.tripId) &&
                Objects.equals(this.origin, leg.origin) &&
                Objects.equals(this.destination, leg.destination) &&
                Objects.equals(this.departure, leg.departure) &&
                Objects.equals(this.plannedDeparture, leg.plannedDeparture) &&
                Objects.equals(this.prognosedArrival, leg.prognosedArrival) &&
                Objects.equals(this.departureDelay, leg.departureDelay) &&
                Objects.equals(this.departurePlatform, leg.departurePlatform) &&
                Objects.equals(this.prognosedDeparturePlatform, leg.prognosedDeparturePlatform) &&
                Objects.equals(this.plannedDeparturePlatform, leg.plannedDeparturePlatform) &&
                Objects.equals(this.arrival, leg.arrival) &&
                Objects.equals(this.plannedArrival, leg.plannedArrival) &&
                Objects.equals(this.prognosedDeparture, leg.prognosedDeparture) &&
                Objects.equals(this.arrivalDelay, leg.arrivalDelay) &&
                Objects.equals(this.arrivalPlatform, leg.arrivalPlatform) &&
                Objects.equals(this.prognosedArrivalPlatform, leg.prognosedArrivalPlatform) &&
                Objects.equals(this.plannedArrivalPlatform, leg.plannedArrivalPlatform) &&
                Objects.equals(this.stopovers, leg.stopovers) &&
                Objects.equals(this.schedule, leg.schedule) &&
                Objects.equals(this.price, leg.price) &&
                Objects.equals(this.operator, leg.operator) &&
                Objects.equals(this.direction, leg.direction) &&
                Objects.equals(this.line, leg.line) &&
                Objects.equals(this.reachable, leg.reachable) &&
                Objects.equals(this.cancelled, leg.cancelled) &&
                Objects.equals(this.walking, leg.walking) &&
                Objects.equals(this.loadFactor, leg.loadFactor) &&
                Objects.equals(this.distance, leg.distance) &&
                Objects.equals(this._public, leg._public) &&
                Objects.equals(this.transfer, leg.transfer) &&
                Objects.equals(this.cycle, leg.cycle) &&
                Objects.equals(this.alternatives, leg.alternatives) &&
                Objects.equals(this.polyline, leg.polyline) &&
                Objects.equals(this.remarks, leg.remarks) &&
                Objects.equals(this.currentLocation, leg.currentLocation) &&
                Objects.equals(this.departurePrognosisType, leg.departurePrognosisType) &&
                Objects.equals(this.arrivalPrognosisType, leg.arrivalPrognosisType) &&
                Objects.equals(this.checkin, leg.checkin);
    }

    @Override
    public int hashCode() {
        return Objects.hash(tripId, origin, destination, departure, plannedDeparture, prognosedArrival, departureDelay, departurePlatform, prognosedDeparturePlatform, plannedDeparturePlatform, arrival, plannedArrival, prognosedDeparture, arrivalDelay, arrivalPlatform, prognosedArrivalPlatform, plannedArrivalPlatform, stopovers, schedule, price, operator, direction, line, reachable, cancelled, walking, loadFactor, distance, _public, transfer, cycle, alternatives, polyline, remarks, currentLocation, departurePrognosisType, arrivalPrognosisType, checkin);
    }

    @Override
    public String toString() {
        String sb = "class Leg {\n" +
                "    tripId: " + toIndentedString(tripId) + "\n" +
                "    origin: " + toIndentedString(origin) + "\n" +
                "    destination: " + toIndentedString(destination) + "\n" +
                "    departure: " + toIndentedString(departure) + "\n" +
                "    plannedDeparture: " + toIndentedString(plannedDeparture) + "\n" +
                "    prognosedArrival: " + toIndentedString(prognosedArrival) + "\n" +
                "    departureDelay: " + toIndentedString(departureDelay) + "\n" +
                "    departurePlatform: " + toIndentedString(departurePlatform) + "\n" +
                "    prognosedDeparturePlatform: " + toIndentedString(prognosedDeparturePlatform) + "\n" +
                "    plannedDeparturePlatform: " + toIndentedString(plannedDeparturePlatform) + "\n" +
                "    arrival: " + toIndentedString(arrival) + "\n" +
                "    plannedArrival: " + toIndentedString(plannedArrival) + "\n" +
                "    prognosedDeparture: " + toIndentedString(prognosedDeparture) + "\n" +
                "    arrivalDelay: " + toIndentedString(arrivalDelay) + "\n" +
                "    arrivalPlatform: " + toIndentedString(arrivalPlatform) + "\n" +
                "    prognosedArrivalPlatform: " + toIndentedString(prognosedArrivalPlatform) + "\n" +
                "    plannedArrivalPlatform: " + toIndentedString(plannedArrivalPlatform) + "\n" +
                "    stopovers: " + toIndentedString(stopovers) + "\n" +
                "    schedule: " + toIndentedString(schedule) + "\n" +
                "    price: " + toIndentedString(price) + "\n" +
                "    operator: " + toIndentedString(operator) + "\n" +
                "    direction: " + toIndentedString(direction) + "\n" +
                "    line: " + toIndentedString(line) + "\n" +
                "    reachable: " + toIndentedString(reachable) + "\n" +
                "    cancelled: " + toIndentedString(cancelled) + "\n" +
                "    walking: " + toIndentedString(walking) + "\n" +
                "    loadFactor: " + toIndentedString(loadFactor) + "\n" +
                "    distance: " + toIndentedString(distance) + "\n" +
                "    _public: " + toIndentedString(_public) + "\n" +
                "    transfer: " + toIndentedString(transfer) + "\n" +
                "    cycle: " + toIndentedString(cycle) + "\n" +
                "    alternatives: " + toIndentedString(alternatives) + "\n" +
                "    polyline: " + toIndentedString(polyline) + "\n" +
                "    remarks: " + toIndentedString(remarks) + "\n" +
                "    currentLocation: " + toIndentedString(currentLocation) + "\n" +
                "    departurePrognosisType: " + toIndentedString(departurePrognosisType) + "\n" +
                "    arrivalPrognosisType: " + toIndentedString(arrivalPrognosisType) + "\n" +
                "    checkin: " + toIndentedString(checkin) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

