/*
 * db-vendo-client
 * Schema for db-vendo-client/hafas-rest-api's Friendly Public Transport Format REST API
 *
 * The version of the OpenAPI document: 6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.olech2412.dbvendowrapper.model;

import com.fasterxml.jackson.annotation.*;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Line
 */
@JsonPropertyOrder({
        Line.JSON_PROPERTY_TYPE,
        Line.JSON_PROPERTY_ID,
        Line.JSON_PROPERTY_NAME,
        Line.JSON_PROPERTY_ADMIN_CODE,
        Line.JSON_PROPERTY_FAHRT_NR,
        Line.JSON_PROPERTY_ADDITIONAL_NAME,
        Line.JSON_PROPERTY_PRODUCT,
        Line.JSON_PROPERTY_PUBLIC,
        Line.JSON_PROPERTY_MODE,
        Line.JSON_PROPERTY_ROUTES,
        Line.JSON_PROPERTY_OPERATOR,
        Line.JSON_PROPERTY_EXPRESS,
        Line.JSON_PROPERTY_METRO,
        Line.JSON_PROPERTY_NIGHT,
        Line.JSON_PROPERTY_NR,
        Line.JSON_PROPERTY_SYMBOL,
        Line.JSON_PROPERTY_DIRECTIONS,
        Line.JSON_PROPERTY_PRODUCT_NAME
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-11T16:58:48.518685525+02:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class Line {
    public static final String JSON_PROPERTY_TYPE = "type";
    public static final String JSON_PROPERTY_ID = "id";
    public static final String JSON_PROPERTY_NAME = "name";
    public static final String JSON_PROPERTY_ADMIN_CODE = "adminCode";
    public static final String JSON_PROPERTY_FAHRT_NR = "fahrtNr";
    public static final String JSON_PROPERTY_ADDITIONAL_NAME = "additionalName";
    public static final String JSON_PROPERTY_PRODUCT = "product";
    public static final String JSON_PROPERTY_PUBLIC = "public";
    public static final String JSON_PROPERTY_MODE = "mode";
    public static final String JSON_PROPERTY_ROUTES = "routes";
    public static final String JSON_PROPERTY_OPERATOR = "operator";
    public static final String JSON_PROPERTY_EXPRESS = "express";
    public static final String JSON_PROPERTY_METRO = "metro";
    public static final String JSON_PROPERTY_NIGHT = "night";
    public static final String JSON_PROPERTY_NR = "nr";
    public static final String JSON_PROPERTY_SYMBOL = "symbol";
    public static final String JSON_PROPERTY_DIRECTIONS = "directions";
    public static final String JSON_PROPERTY_PRODUCT_NAME = "productName";
    @jakarta.annotation.Nullable
    private TypeEnum type;
    @jakarta.annotation.Nullable
    private String id;
    @jakarta.annotation.Nullable
    private String name;
    @jakarta.annotation.Nullable
    private String adminCode;
    @jakarta.annotation.Nullable
    private String fahrtNr;
    @jakarta.annotation.Nullable
    private String additionalName;
    @jakarta.annotation.Nullable
    private String product;
    @jakarta.annotation.Nullable
    private Boolean _public;
    @jakarta.annotation.Nullable
    private ModeEnum mode;
    @jakarta.annotation.Nullable
    private List<String> routes = new ArrayList<>();
    @jakarta.annotation.Nullable
    private Operator operator;
    @jakarta.annotation.Nullable
    private Boolean express;
    @jakarta.annotation.Nullable
    private Boolean metro;
    @jakarta.annotation.Nullable
    private Boolean night;
    @jakarta.annotation.Nullable
    private BigDecimal nr;
    @jakarta.annotation.Nullable
    private String symbol;
    @jakarta.annotation.Nullable
    private List<String> directions = new ArrayList<>();
    @jakarta.annotation.Nullable
    private String productName;

    public Line() {
    }

    public Line type(@jakarta.annotation.Nullable TypeEnum type) {

        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public TypeEnum getType() {
        return type;
    }

    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setType(@jakarta.annotation.Nullable TypeEnum type) {
        this.type = type;
    }

    public Line id(@jakarta.annotation.Nullable String id) {

        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getId() {
        return id;
    }

    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setId(@jakarta.annotation.Nullable String id) {
        this.id = id;
    }

    public Line name(@jakarta.annotation.Nullable String name) {

        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getName() {
        return name;
    }

    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setName(@jakarta.annotation.Nullable String name) {
        this.name = name;
    }

    public Line adminCode(@jakarta.annotation.Nullable String adminCode) {

        this.adminCode = adminCode;
        return this;
    }

    /**
     * Get adminCode
     *
     * @return adminCode
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ADMIN_CODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getAdminCode() {
        return adminCode;
    }

    @JsonProperty(JSON_PROPERTY_ADMIN_CODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAdminCode(@jakarta.annotation.Nullable String adminCode) {
        this.adminCode = adminCode;
    }

    public Line fahrtNr(@jakarta.annotation.Nullable String fahrtNr) {

        this.fahrtNr = fahrtNr;
        return this;
    }

    /**
     * Get fahrtNr
     *
     * @return fahrtNr
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_FAHRT_NR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getFahrtNr() {
        return fahrtNr;
    }

    @JsonProperty(JSON_PROPERTY_FAHRT_NR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFahrtNr(@jakarta.annotation.Nullable String fahrtNr) {
        this.fahrtNr = fahrtNr;
    }

    public Line additionalName(@jakarta.annotation.Nullable String additionalName) {

        this.additionalName = additionalName;
        return this;
    }

    /**
     * Get additionalName
     *
     * @return additionalName
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ADDITIONAL_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getAdditionalName() {
        return additionalName;
    }

    @JsonProperty(JSON_PROPERTY_ADDITIONAL_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAdditionalName(@jakarta.annotation.Nullable String additionalName) {
        this.additionalName = additionalName;
    }

    public Line product(@jakarta.annotation.Nullable String product) {

        this.product = product;
        return this;
    }

    /**
     * Get product
     *
     * @return product
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PRODUCT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getProduct() {
        return product;
    }

    @JsonProperty(JSON_PROPERTY_PRODUCT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProduct(@jakarta.annotation.Nullable String product) {
        this.product = product;
    }

    public Line _public(@jakarta.annotation.Nullable Boolean _public) {

        this._public = _public;
        return this;
    }

    /**
     * Get _public
     *
     * @return _public
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PUBLIC)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getPublic() {
        return _public;
    }

    @JsonProperty(JSON_PROPERTY_PUBLIC)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPublic(@jakarta.annotation.Nullable Boolean _public) {
        this._public = _public;
    }

    public Line mode(@jakarta.annotation.Nullable ModeEnum mode) {

        this.mode = mode;
        return this;
    }

    /**
     * Get mode
     *
     * @return mode
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public ModeEnum getMode() {
        return mode;
    }

    @JsonProperty(JSON_PROPERTY_MODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMode(@jakarta.annotation.Nullable ModeEnum mode) {
        this.mode = mode;
    }

    public Line routes(@jakarta.annotation.Nullable List<String> routes) {

        this.routes = routes;
        return this;
    }

    public Line addRoutesItem(String routesItem) {
        if (this.routes == null) {
            this.routes = new ArrayList<>();
        }
        this.routes.add(routesItem);
        return this;
    }

    /**
     * routes ids
     *
     * @return routes
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ROUTES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<String> getRoutes() {
        return routes;
    }

    @JsonProperty(JSON_PROPERTY_ROUTES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRoutes(@jakarta.annotation.Nullable List<String> routes) {
        this.routes = routes;
    }

    public Line operator(@jakarta.annotation.Nullable Operator operator) {

        this.operator = operator;
        return this;
    }

    /**
     * Get operator
     *
     * @return operator
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_OPERATOR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Operator getOperator() {
        return operator;
    }

    @JsonProperty(JSON_PROPERTY_OPERATOR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setOperator(@jakarta.annotation.Nullable Operator operator) {
        this.operator = operator;
    }

    public Line express(@jakarta.annotation.Nullable Boolean express) {

        this.express = express;
        return this;
    }

    /**
     * Get express
     *
     * @return express
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_EXPRESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getExpress() {
        return express;
    }

    @JsonProperty(JSON_PROPERTY_EXPRESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setExpress(@jakarta.annotation.Nullable Boolean express) {
        this.express = express;
    }

    public Line metro(@jakarta.annotation.Nullable Boolean metro) {

        this.metro = metro;
        return this;
    }

    /**
     * Get metro
     *
     * @return metro
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_METRO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getMetro() {
        return metro;
    }

    @JsonProperty(JSON_PROPERTY_METRO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMetro(@jakarta.annotation.Nullable Boolean metro) {
        this.metro = metro;
    }

    public Line night(@jakarta.annotation.Nullable Boolean night) {

        this.night = night;
        return this;
    }

    /**
     * Get night
     *
     * @return night
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_NIGHT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getNight() {
        return night;
    }

    @JsonProperty(JSON_PROPERTY_NIGHT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNight(@jakarta.annotation.Nullable Boolean night) {
        this.night = night;
    }

    public Line nr(@jakarta.annotation.Nullable BigDecimal nr) {

        this.nr = nr;
        return this;
    }

    /**
     * Get nr
     *
     * @return nr
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_NR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getNr() {
        return nr;
    }

    @JsonProperty(JSON_PROPERTY_NR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNr(@jakarta.annotation.Nullable BigDecimal nr) {
        this.nr = nr;
    }

    public Line symbol(@jakarta.annotation.Nullable String symbol) {

        this.symbol = symbol;
        return this;
    }

    /**
     * Get symbol
     *
     * @return symbol
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SYMBOL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getSymbol() {
        return symbol;
    }

    @JsonProperty(JSON_PROPERTY_SYMBOL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSymbol(@jakarta.annotation.Nullable String symbol) {
        this.symbol = symbol;
    }

    public Line directions(@jakarta.annotation.Nullable List<String> directions) {

        this.directions = directions;
        return this;
    }

    public Line addDirectionsItem(String directionsItem) {
        if (this.directions == null) {
            this.directions = new ArrayList<>();
        }
        this.directions.add(directionsItem);
        return this;
    }

    /**
     * Get directions
     *
     * @return directions
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DIRECTIONS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<String> getDirections() {
        return directions;
    }

    @JsonProperty(JSON_PROPERTY_DIRECTIONS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDirections(@jakarta.annotation.Nullable List<String> directions) {
        this.directions = directions;
    }

    public Line productName(@jakarta.annotation.Nullable String productName) {

        this.productName = productName;
        return this;
    }

    /**
     * Get productName
     *
     * @return productName
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PRODUCT_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getProductName() {
        return productName;
    }

    @JsonProperty(JSON_PROPERTY_PRODUCT_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProductName(@jakarta.annotation.Nullable String productName) {
        this.productName = productName;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Line line = (Line) o;
        return Objects.equals(this.type, line.type) &&
                Objects.equals(this.id, line.id) &&
                Objects.equals(this.name, line.name) &&
                Objects.equals(this.adminCode, line.adminCode) &&
                Objects.equals(this.fahrtNr, line.fahrtNr) &&
                Objects.equals(this.additionalName, line.additionalName) &&
                Objects.equals(this.product, line.product) &&
                Objects.equals(this._public, line._public) &&
                Objects.equals(this.mode, line.mode) &&
                Objects.equals(this.routes, line.routes) &&
                Objects.equals(this.operator, line.operator) &&
                Objects.equals(this.express, line.express) &&
                Objects.equals(this.metro, line.metro) &&
                Objects.equals(this.night, line.night) &&
                Objects.equals(this.nr, line.nr) &&
                Objects.equals(this.symbol, line.symbol) &&
                Objects.equals(this.directions, line.directions) &&
                Objects.equals(this.productName, line.productName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(type, id, name, adminCode, fahrtNr, additionalName, product, _public, mode, routes, operator, express, metro, night, nr, symbol, directions, productName);
    }

    @Override
    public String toString() {
        String sb = "class Line {\n" +
                "    type: " + toIndentedString(type) + "\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    adminCode: " + toIndentedString(adminCode) + "\n" +
                "    fahrtNr: " + toIndentedString(fahrtNr) + "\n" +
                "    additionalName: " + toIndentedString(additionalName) + "\n" +
                "    product: " + toIndentedString(product) + "\n" +
                "    _public: " + toIndentedString(_public) + "\n" +
                "    mode: " + toIndentedString(mode) + "\n" +
                "    routes: " + toIndentedString(routes) + "\n" +
                "    operator: " + toIndentedString(operator) + "\n" +
                "    express: " + toIndentedString(express) + "\n" +
                "    metro: " + toIndentedString(metro) + "\n" +
                "    night: " + toIndentedString(night) + "\n" +
                "    nr: " + toIndentedString(nr) + "\n" +
                "    symbol: " + toIndentedString(symbol) + "\n" +
                "    directions: " + toIndentedString(directions) + "\n" +
                "    productName: " + toIndentedString(productName) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Gets or Sets type
     */
    public enum TypeEnum {
        LINE("line");

        private final String value;

        TypeEnum(String value) {
            this.value = value;
        }

        @JsonCreator
        public static TypeEnum fromValue(String value) {
            for (TypeEnum b : TypeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }
    }

    /**
     * Gets or Sets mode
     */
    public enum ModeEnum {
        AIRCRAFT("aircraft"),

        BICYCLE("bicycle"),

        BUS("bus"),

        CAR("car"),

        GONDOLA("gondola"),

        TAXI("taxi"),

        TRAIN("train"),

        WALKING("walking"),

        WATERCRAFT("watercraft");

        private final String value;

        ModeEnum(String value) {
            this.value = value;
        }

        @JsonCreator
        public static ModeEnum fromValue(String value) {
            for (ModeEnum b : ModeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }
    }

}

