/*
 * db-vendo-client
 * Schema for db-vendo-client/hafas-rest-api's Friendly Public Transport Format REST API
 *
 * The version of the OpenAPI document: 6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.olech2412.dbvendowrapper.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * NearByOptions
 */
@JsonPropertyOrder({
        NearByOptions.JSON_PROPERTY_RESULTS,
        NearByOptions.JSON_PROPERTY_DISTANCE,
        NearByOptions.JSON_PROPERTY_POI,
        NearByOptions.JSON_PROPERTY_STOPS,
        NearByOptions.JSON_PROPERTY_PRODUCTS,
        NearByOptions.JSON_PROPERTY_SUB_STOPS,
        NearByOptions.JSON_PROPERTY_ENTRANCES,
        NearByOptions.JSON_PROPERTY_LINES_OF_STOPS,
        NearByOptions.JSON_PROPERTY_LANGUAGE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-11T16:58:48.518685525+02:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class NearByOptions {
    public static final String JSON_PROPERTY_RESULTS = "results";
    public static final String JSON_PROPERTY_DISTANCE = "distance";
    public static final String JSON_PROPERTY_POI = "poi";
    public static final String JSON_PROPERTY_STOPS = "stops";
    public static final String JSON_PROPERTY_PRODUCTS = "products";
    public static final String JSON_PROPERTY_SUB_STOPS = "subStops";
    public static final String JSON_PROPERTY_ENTRANCES = "entrances";
    public static final String JSON_PROPERTY_LINES_OF_STOPS = "linesOfStops";
    public static final String JSON_PROPERTY_LANGUAGE = "language";
    @jakarta.annotation.Nullable
    private BigDecimal results = new BigDecimal("8");
    @jakarta.annotation.Nullable
    private BigDecimal distance;
    @jakarta.annotation.Nullable
    private Boolean poi = false;
    @jakarta.annotation.Nullable
    private Boolean stops = true;
    @jakarta.annotation.Nullable
    private Map<String, Boolean> products = new HashMap<>();
    @jakarta.annotation.Nullable
    private Boolean subStops = true;
    @jakarta.annotation.Nullable
    private Boolean entrances = true;
    @jakarta.annotation.Nullable
    private Boolean linesOfStops = false;
    @jakarta.annotation.Nullable
    private String language = "en";

    public NearByOptions() {
    }

    public NearByOptions results(@jakarta.annotation.Nullable BigDecimal results) {

        this.results = results;
        return this;
    }

    /**
     * maximum number of results
     *
     * @return results
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_RESULTS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getResults() {
        return results;
    }


    @JsonProperty(JSON_PROPERTY_RESULTS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setResults(@jakarta.annotation.Nullable BigDecimal results) {
        this.results = results;
    }

    public NearByOptions distance(@jakarta.annotation.Nullable BigDecimal distance) {

        this.distance = distance;
        return this;
    }

    /**
     * maximum walking distance in meters
     *
     * @return distance
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DISTANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getDistance() {
        return distance;
    }


    @JsonProperty(JSON_PROPERTY_DISTANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDistance(@jakarta.annotation.Nullable BigDecimal distance) {
        this.distance = distance;
    }

    public NearByOptions poi(@jakarta.annotation.Nullable Boolean poi) {

        this.poi = poi;
        return this;
    }

    /**
     * return points of interest?
     *
     * @return poi
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_POI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getPoi() {
        return poi;
    }


    @JsonProperty(JSON_PROPERTY_POI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPoi(@jakarta.annotation.Nullable Boolean poi) {
        this.poi = poi;
    }

    public NearByOptions stops(@jakarta.annotation.Nullable Boolean stops) {

        this.stops = stops;
        return this;
    }

    /**
     * return stops/stations?
     *
     * @return stops
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_STOPS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getStops() {
        return stops;
    }


    @JsonProperty(JSON_PROPERTY_STOPS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStops(@jakarta.annotation.Nullable Boolean stops) {
        this.stops = stops;
    }

    public NearByOptions products(@jakarta.annotation.Nullable Map<String, Boolean> products) {

        this.products = products;
        return this;
    }

    public NearByOptions putProductsItem(String key, Boolean productsItem) {
        if (this.products == null) {
            this.products = new HashMap<>();
        }
        this.products.put(key, productsItem);
        return this;
    }

    /**
     * Each public transportation network exposes its products as boolean properties. See {@link ProductType}
     *
     * @return products
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PRODUCTS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Map<String, Boolean> getProducts() {
        return products;
    }


    @JsonProperty(JSON_PROPERTY_PRODUCTS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProducts(@jakarta.annotation.Nullable Map<String, Boolean> products) {
        this.products = products;
    }

    public NearByOptions subStops(@jakarta.annotation.Nullable Boolean subStops) {

        this.subStops = subStops;
        return this;
    }

    /**
     * parse &amp; expose sub-stops of stations?
     *
     * @return subStops
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SUB_STOPS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getSubStops() {
        return subStops;
    }


    @JsonProperty(JSON_PROPERTY_SUB_STOPS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSubStops(@jakarta.annotation.Nullable Boolean subStops) {
        this.subStops = subStops;
    }

    public NearByOptions entrances(@jakarta.annotation.Nullable Boolean entrances) {

        this.entrances = entrances;
        return this;
    }

    /**
     * parse &amp; expose entrances of stops/stations?
     *
     * @return entrances
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ENTRANCES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getEntrances() {
        return entrances;
    }


    @JsonProperty(JSON_PROPERTY_ENTRANCES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEntrances(@jakarta.annotation.Nullable Boolean entrances) {
        this.entrances = entrances;
    }

    public NearByOptions linesOfStops(@jakarta.annotation.Nullable Boolean linesOfStops) {

        this.linesOfStops = linesOfStops;
        return this;
    }

    /**
     * parse &amp; expose lines at each stop/station?
     *
     * @return linesOfStops
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LINES_OF_STOPS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getLinesOfStops() {
        return linesOfStops;
    }


    @JsonProperty(JSON_PROPERTY_LINES_OF_STOPS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLinesOfStops(@jakarta.annotation.Nullable Boolean linesOfStops) {
        this.linesOfStops = linesOfStops;
    }

    public NearByOptions language(@jakarta.annotation.Nullable String language) {

        this.language = language;
        return this;
    }

    /**
     * language
     *
     * @return language
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LANGUAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getLanguage() {
        return language;
    }


    @JsonProperty(JSON_PROPERTY_LANGUAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLanguage(@jakarta.annotation.Nullable String language) {
        this.language = language;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        NearByOptions nearByOptions = (NearByOptions) o;
        return Objects.equals(this.results, nearByOptions.results) &&
                Objects.equals(this.distance, nearByOptions.distance) &&
                Objects.equals(this.poi, nearByOptions.poi) &&
                Objects.equals(this.stops, nearByOptions.stops) &&
                Objects.equals(this.products, nearByOptions.products) &&
                Objects.equals(this.subStops, nearByOptions.subStops) &&
                Objects.equals(this.entrances, nearByOptions.entrances) &&
                Objects.equals(this.linesOfStops, nearByOptions.linesOfStops) &&
                Objects.equals(this.language, nearByOptions.language);
    }

    @Override
    public int hashCode() {
        return Objects.hash(results, distance, poi, stops, products, subStops, entrances, linesOfStops, language);
    }

    @Override
    public String toString() {
        String sb = "class NearByOptions {\n" +
                "    results: " + toIndentedString(results) + "\n" +
                "    distance: " + toIndentedString(distance) + "\n" +
                "    poi: " + toIndentedString(poi) + "\n" +
                "    stops: " + toIndentedString(stops) + "\n" +
                "    products: " + toIndentedString(products) + "\n" +
                "    subStops: " + toIndentedString(subStops) + "\n" +
                "    entrances: " + toIndentedString(entrances) + "\n" +
                "    linesOfStops: " + toIndentedString(linesOfStops) + "\n" +
                "    language: " + toIndentedString(language) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

