/*
 * db-vendo-client
 * Schema for db-vendo-client/hafas-rest-api's Friendly Public Transport Format REST API
 *
 * The version of the OpenAPI document: 6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.olech2412.dbvendowrapper.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * ProfileSpecificProducts
 */
@JsonPropertyOrder({
        ProfileSpecificProducts.JSON_PROPERTY_NATIONAL_EXPRESS,
        ProfileSpecificProducts.JSON_PROPERTY_NATIONAL,
        ProfileSpecificProducts.JSON_PROPERTY_REGIONAL_EXPRESS,
        ProfileSpecificProducts.JSON_PROPERTY_REGIONAL,
        ProfileSpecificProducts.JSON_PROPERTY_SUBURBAN,
        ProfileSpecificProducts.JSON_PROPERTY_BUS,
        ProfileSpecificProducts.JSON_PROPERTY_FERRY,
        ProfileSpecificProducts.JSON_PROPERTY_SUBWAY,
        ProfileSpecificProducts.JSON_PROPERTY_TRAM,
        ProfileSpecificProducts.JSON_PROPERTY_TAXI
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-11T16:58:48.518685525+02:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class ProfileSpecificProducts {
    public static final String JSON_PROPERTY_NATIONAL_EXPRESS = "nationalExpress";
    public static final String JSON_PROPERTY_NATIONAL = "national";
    public static final String JSON_PROPERTY_REGIONAL_EXPRESS = "regionalExpress";
    public static final String JSON_PROPERTY_REGIONAL = "regional";
    public static final String JSON_PROPERTY_SUBURBAN = "suburban";
    public static final String JSON_PROPERTY_BUS = "bus";
    public static final String JSON_PROPERTY_FERRY = "ferry";
    public static final String JSON_PROPERTY_SUBWAY = "subway";
    public static final String JSON_PROPERTY_TRAM = "tram";
    public static final String JSON_PROPERTY_TAXI = "taxi";
    @jakarta.annotation.Nullable
    private Boolean nationalExpress = true;
    @jakarta.annotation.Nullable
    private Boolean national = true;
    @jakarta.annotation.Nullable
    private Boolean regionalExpress = true;
    @jakarta.annotation.Nullable
    private Boolean regional = true;
    @jakarta.annotation.Nullable
    private Boolean suburban = true;
    @jakarta.annotation.Nullable
    private Boolean bus = true;
    @jakarta.annotation.Nullable
    private Boolean ferry = true;
    @jakarta.annotation.Nullable
    private Boolean subway = true;
    @jakarta.annotation.Nullable
    private Boolean tram = true;
    @jakarta.annotation.Nullable
    private Boolean taxi = true;

    public ProfileSpecificProducts() {
    }

    public ProfileSpecificProducts nationalExpress(@jakarta.annotation.Nullable Boolean nationalExpress) {

        this.nationalExpress = nationalExpress;
        return this;
    }

    /**
     * Include InterCityExpress (ICE)?
     *
     * @return nationalExpress
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_NATIONAL_EXPRESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getNationalExpress() {
        return nationalExpress;
    }


    @JsonProperty(JSON_PROPERTY_NATIONAL_EXPRESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNationalExpress(@jakarta.annotation.Nullable Boolean nationalExpress) {
        this.nationalExpress = nationalExpress;
    }

    public ProfileSpecificProducts national(@jakarta.annotation.Nullable Boolean national) {

        this.national = national;
        return this;
    }

    /**
     * Include InterCity &amp; EuroCity (IC/EC)?
     *
     * @return national
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_NATIONAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getNational() {
        return national;
    }


    @JsonProperty(JSON_PROPERTY_NATIONAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNational(@jakarta.annotation.Nullable Boolean national) {
        this.national = national;
    }

    public ProfileSpecificProducts regionalExpress(@jakarta.annotation.Nullable Boolean regionalExpress) {

        this.regionalExpress = regionalExpress;
        return this;
    }

    /**
     * Include InterRegio, FlixTrain, Westbahn etc.?
     *
     * @return regionalExpress
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_REGIONAL_EXPRESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getRegionalExpress() {
        return regionalExpress;
    }


    @JsonProperty(JSON_PROPERTY_REGIONAL_EXPRESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRegionalExpress(@jakarta.annotation.Nullable Boolean regionalExpress) {
        this.regionalExpress = regionalExpress;
    }

    public ProfileSpecificProducts regional(@jakarta.annotation.Nullable Boolean regional) {

        this.regional = regional;
        return this;
    }

    /**
     * Include Regio (RB)?
     *
     * @return regional
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_REGIONAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getRegional() {
        return regional;
    }


    @JsonProperty(JSON_PROPERTY_REGIONAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRegional(@jakarta.annotation.Nullable Boolean regional) {
        this.regional = regional;
    }

    public ProfileSpecificProducts suburban(@jakarta.annotation.Nullable Boolean suburban) {

        this.suburban = suburban;
        return this;
    }

    /**
     * Include S-Bahn (S)?
     *
     * @return suburban
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SUBURBAN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getSuburban() {
        return suburban;
    }


    @JsonProperty(JSON_PROPERTY_SUBURBAN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSuburban(@jakarta.annotation.Nullable Boolean suburban) {
        this.suburban = suburban;
    }

    public ProfileSpecificProducts bus(@jakarta.annotation.Nullable Boolean bus) {

        this.bus = bus;
        return this;
    }

    /**
     * Include Bus (B)?
     *
     * @return bus
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_BUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getBus() {
        return bus;
    }


    @JsonProperty(JSON_PROPERTY_BUS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setBus(@jakarta.annotation.Nullable Boolean bus) {
        this.bus = bus;
    }

    public ProfileSpecificProducts ferry(@jakarta.annotation.Nullable Boolean ferry) {

        this.ferry = ferry;
        return this;
    }

    /**
     * Include Ferry (F)?
     *
     * @return ferry
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_FERRY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getFerry() {
        return ferry;
    }


    @JsonProperty(JSON_PROPERTY_FERRY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFerry(@jakarta.annotation.Nullable Boolean ferry) {
        this.ferry = ferry;
    }

    public ProfileSpecificProducts subway(@jakarta.annotation.Nullable Boolean subway) {

        this.subway = subway;
        return this;
    }

    /**
     * Include U-Bahn (U)?
     *
     * @return subway
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SUBWAY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getSubway() {
        return subway;
    }


    @JsonProperty(JSON_PROPERTY_SUBWAY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSubway(@jakarta.annotation.Nullable Boolean subway) {
        this.subway = subway;
    }

    public ProfileSpecificProducts tram(@jakarta.annotation.Nullable Boolean tram) {

        this.tram = tram;
        return this;
    }

    /**
     * Include Tram (T)?
     *
     * @return tram
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TRAM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getTram() {
        return tram;
    }


    @JsonProperty(JSON_PROPERTY_TRAM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTram(@jakarta.annotation.Nullable Boolean tram) {
        this.tram = tram;
    }

    public ProfileSpecificProducts taxi(@jakarta.annotation.Nullable Boolean taxi) {

        this.taxi = taxi;
        return this;
    }

    /**
     * Include Group Taxi (Taxi)?
     *
     * @return taxi
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TAXI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getTaxi() {
        return taxi;
    }


    @JsonProperty(JSON_PROPERTY_TAXI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTaxi(@jakarta.annotation.Nullable Boolean taxi) {
        this.taxi = taxi;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ProfileSpecificProducts profileSpecificProducts = (ProfileSpecificProducts) o;
        return Objects.equals(this.nationalExpress, profileSpecificProducts.nationalExpress) &&
                Objects.equals(this.national, profileSpecificProducts.national) &&
                Objects.equals(this.regionalExpress, profileSpecificProducts.regionalExpress) &&
                Objects.equals(this.regional, profileSpecificProducts.regional) &&
                Objects.equals(this.suburban, profileSpecificProducts.suburban) &&
                Objects.equals(this.bus, profileSpecificProducts.bus) &&
                Objects.equals(this.ferry, profileSpecificProducts.ferry) &&
                Objects.equals(this.subway, profileSpecificProducts.subway) &&
                Objects.equals(this.tram, profileSpecificProducts.tram) &&
                Objects.equals(this.taxi, profileSpecificProducts.taxi);
    }

    @Override
    public int hashCode() {
        return Objects.hash(nationalExpress, national, regionalExpress, regional, suburban, bus, ferry, subway, tram, taxi);
    }

    @Override
    public String toString() {
        String sb = "class ProfileSpecificProducts {\n" +
                "    nationalExpress: " + toIndentedString(nationalExpress) + "\n" +
                "    national: " + toIndentedString(national) + "\n" +
                "    regionalExpress: " + toIndentedString(regionalExpress) + "\n" +
                "    regional: " + toIndentedString(regional) + "\n" +
                "    suburban: " + toIndentedString(suburban) + "\n" +
                "    bus: " + toIndentedString(bus) + "\n" +
                "    ferry: " + toIndentedString(ferry) + "\n" +
                "    subway: " + toIndentedString(subway) + "\n" +
                "    tram: " + toIndentedString(tram) + "\n" +
                "    taxi: " + toIndentedString(taxi) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

