/*
 * db-vendo-client
 * Schema for db-vendo-client/hafas-rest-api's Friendly Public Transport Format REST API
 *
 * The version of the OpenAPI document: 6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.olech2412.dbvendowrapper.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * ServerInfo
 */
@JsonPropertyOrder({
        ServerInfo.JSON_PROPERTY_HCI_VERSION,
        ServerInfo.JSON_PROPERTY_TIMETABLE_START,
        ServerInfo.JSON_PROPERTY_TIMETABLE_END,
        ServerInfo.JSON_PROPERTY_SERVER_TIME,
        ServerInfo.JSON_PROPERTY_REALTIME_DATA_UPDATED_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-11T16:58:48.518685525+02:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class ServerInfo {
    public static final String JSON_PROPERTY_HCI_VERSION = "hciVersion";
    public static final String JSON_PROPERTY_TIMETABLE_START = "timetableStart";
    public static final String JSON_PROPERTY_TIMETABLE_END = "timetableEnd";
    public static final String JSON_PROPERTY_SERVER_TIME = "serverTime";
    public static final String JSON_PROPERTY_REALTIME_DATA_UPDATED_AT = "realtimeDataUpdatedAt";
    @jakarta.annotation.Nullable
    private String hciVersion;
    @jakarta.annotation.Nullable
    private String timetableStart;
    @jakarta.annotation.Nullable
    private String timetableEnd;
    @jakarta.annotation.Nullable
    private String serverTime;
    @jakarta.annotation.Nullable
    private BigDecimal realtimeDataUpdatedAt;

    public ServerInfo() {
    }

    public ServerInfo hciVersion(@jakarta.annotation.Nullable String hciVersion) {

        this.hciVersion = hciVersion;
        return this;
    }

    /**
     * Get hciVersion
     *
     * @return hciVersion
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_HCI_VERSION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getHciVersion() {
        return hciVersion;
    }


    @JsonProperty(JSON_PROPERTY_HCI_VERSION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setHciVersion(@jakarta.annotation.Nullable String hciVersion) {
        this.hciVersion = hciVersion;
    }

    public ServerInfo timetableStart(@jakarta.annotation.Nullable String timetableStart) {

        this.timetableStart = timetableStart;
        return this;
    }

    /**
     * Get timetableStart
     *
     * @return timetableStart
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TIMETABLE_START)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getTimetableStart() {
        return timetableStart;
    }


    @JsonProperty(JSON_PROPERTY_TIMETABLE_START)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTimetableStart(@jakarta.annotation.Nullable String timetableStart) {
        this.timetableStart = timetableStart;
    }

    public ServerInfo timetableEnd(@jakarta.annotation.Nullable String timetableEnd) {

        this.timetableEnd = timetableEnd;
        return this;
    }

    /**
     * Get timetableEnd
     *
     * @return timetableEnd
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TIMETABLE_END)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getTimetableEnd() {
        return timetableEnd;
    }


    @JsonProperty(JSON_PROPERTY_TIMETABLE_END)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTimetableEnd(@jakarta.annotation.Nullable String timetableEnd) {
        this.timetableEnd = timetableEnd;
    }

    public ServerInfo serverTime(@jakarta.annotation.Nullable String serverTime) {

        this.serverTime = serverTime;
        return this;
    }

    /**
     * Get serverTime
     *
     * @return serverTime
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SERVER_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getServerTime() {
        return serverTime;
    }


    @JsonProperty(JSON_PROPERTY_SERVER_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setServerTime(@jakarta.annotation.Nullable String serverTime) {
        this.serverTime = serverTime;
    }

    public ServerInfo realtimeDataUpdatedAt(@jakarta.annotation.Nullable BigDecimal realtimeDataUpdatedAt) {

        this.realtimeDataUpdatedAt = realtimeDataUpdatedAt;
        return this;
    }

    /**
     * Get realtimeDataUpdatedAt
     *
     * @return realtimeDataUpdatedAt
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_REALTIME_DATA_UPDATED_AT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getRealtimeDataUpdatedAt() {
        return realtimeDataUpdatedAt;
    }


    @JsonProperty(JSON_PROPERTY_REALTIME_DATA_UPDATED_AT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRealtimeDataUpdatedAt(@jakarta.annotation.Nullable BigDecimal realtimeDataUpdatedAt) {
        this.realtimeDataUpdatedAt = realtimeDataUpdatedAt;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ServerInfo serverInfo = (ServerInfo) o;
        return Objects.equals(this.hciVersion, serverInfo.hciVersion) &&
                Objects.equals(this.timetableStart, serverInfo.timetableStart) &&
                Objects.equals(this.timetableEnd, serverInfo.timetableEnd) &&
                Objects.equals(this.serverTime, serverInfo.serverTime) &&
                Objects.equals(this.realtimeDataUpdatedAt, serverInfo.realtimeDataUpdatedAt);
    }

    @Override
    public int hashCode() {
        return Objects.hash(hciVersion, timetableStart, timetableEnd, serverTime, realtimeDataUpdatedAt);
    }

    @Override
    public String toString() {
        String sb = "class ServerInfo {\n" +
                "    hciVersion: " + toIndentedString(hciVersion) + "\n" +
                "    timetableStart: " + toIndentedString(timetableStart) + "\n" +
                "    timetableEnd: " + toIndentedString(timetableEnd) + "\n" +
                "    serverTime: " + toIndentedString(serverTime) + "\n" +
                "    realtimeDataUpdatedAt: " + toIndentedString(realtimeDataUpdatedAt) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

