/*
 * db-vendo-client
 * Schema for db-vendo-client/hafas-rest-api's Friendly Public Transport Format REST API
 *
 * The version of the OpenAPI document: 6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.olech2412.dbvendowrapper.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * ServerOptions
 */
@JsonPropertyOrder({
        ServerOptions.JSON_PROPERTY_VERSION_INFO,
        ServerOptions.JSON_PROPERTY_LANGUAGE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-11T16:58:48.518685525+02:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class ServerOptions {
    public static final String JSON_PROPERTY_VERSION_INFO = "versionInfo";
    public static final String JSON_PROPERTY_LANGUAGE = "language";
    @jakarta.annotation.Nullable
    private Boolean versionInfo = true;
    @jakarta.annotation.Nullable
    private String language = "en";

    public ServerOptions() {
    }

    public ServerOptions versionInfo(@jakarta.annotation.Nullable Boolean versionInfo) {

        this.versionInfo = versionInfo;
        return this;
    }

    /**
     * versionInfo
     *
     * @return versionInfo
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_VERSION_INFO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getVersionInfo() {
        return versionInfo;
    }


    @JsonProperty(JSON_PROPERTY_VERSION_INFO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setVersionInfo(@jakarta.annotation.Nullable Boolean versionInfo) {
        this.versionInfo = versionInfo;
    }

    public ServerOptions language(@jakarta.annotation.Nullable String language) {

        this.language = language;
        return this;
    }

    /**
     * Language of the results
     *
     * @return language
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LANGUAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getLanguage() {
        return language;
    }


    @JsonProperty(JSON_PROPERTY_LANGUAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLanguage(@jakarta.annotation.Nullable String language) {
        this.language = language;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ServerOptions serverOptions = (ServerOptions) o;
        return Objects.equals(this.versionInfo, serverOptions.versionInfo) &&
                Objects.equals(this.language, serverOptions.language);
    }

    @Override
    public int hashCode() {
        return Objects.hash(versionInfo, language);
    }

    @Override
    public String toString() {
        String sb = "class ServerOptions {\n" +
                "    versionInfo: " + toIndentedString(versionInfo) + "\n" +
                "    language: " + toIndentedString(language) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

