/*
 * db-vendo-client
 * Schema for db-vendo-client/hafas-rest-api's Friendly Public Transport Format REST API
 *
 * The version of the OpenAPI document: 6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.olech2412.dbvendowrapper.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * StopsIdDeparturesGet2XXResponse
 */
@JsonPropertyOrder({
        StopsIdDeparturesResponse.JSON_PROPERTY_DEPARTURES,
        StopsIdDeparturesResponse.JSON_PROPERTY_REALTIME_DATA_UPDATED_AT
})
@JsonTypeName("_stops__id__departures_get_2XX_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-11T16:58:48.518685525+02:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class StopsIdDeparturesResponse implements CachedAwareResponse {
    public static final String JSON_PROPERTY_DEPARTURES = "departures";
    public static final String JSON_PROPERTY_REALTIME_DATA_UPDATED_AT = "realtimeDataUpdatedAt";
    @jakarta.annotation.Nonnull
    private List<Alternative> departures = new ArrayList<>();
    @jakarta.annotation.Nullable
    private Integer realtimeDataUpdatedAt;
    private boolean fromCache = false;

    public StopsIdDeparturesResponse() {
    }

    public StopsIdDeparturesResponse departures(@jakarta.annotation.Nonnull List<Alternative> departures) {

        this.departures = departures;
        return this;
    }

    public StopsIdDeparturesResponse addDeparturesItem(Alternative departuresItem) {
        if (this.departures == null) {
            this.departures = new ArrayList<>();
        }
        this.departures.add(departuresItem);
        return this;
    }

    /**
     * Get departures
     *
     * @return departures
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_DEPARTURES)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public List<Alternative> getDepartures() {
        return departures;
    }


    @JsonProperty(JSON_PROPERTY_DEPARTURES)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setDepartures(@jakarta.annotation.Nonnull List<Alternative> departures) {
        this.departures = departures;
    }

    public StopsIdDeparturesResponse realtimeDataUpdatedAt(@jakarta.annotation.Nullable Integer realtimeDataUpdatedAt) {

        this.realtimeDataUpdatedAt = realtimeDataUpdatedAt;
        return this;
    }

    /**
     * Get realtimeDataUpdatedAt
     *
     * @return realtimeDataUpdatedAt
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_REALTIME_DATA_UPDATED_AT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getRealtimeDataUpdatedAt() {
        return realtimeDataUpdatedAt;
    }


    @JsonProperty(JSON_PROPERTY_REALTIME_DATA_UPDATED_AT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRealtimeDataUpdatedAt(@jakarta.annotation.Nullable Integer realtimeDataUpdatedAt) {
        this.realtimeDataUpdatedAt = realtimeDataUpdatedAt;
    }

    @Override
    public void setFromCache(boolean fromCache) {
        this.fromCache = fromCache;
    }

    @Override
    public boolean isFromCache() {
        return fromCache;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StopsIdDeparturesResponse stopsIdDeparturesResponse = (StopsIdDeparturesResponse) o;
        return Objects.equals(this.departures, stopsIdDeparturesResponse.departures) &&
                Objects.equals(this.realtimeDataUpdatedAt, stopsIdDeparturesResponse.realtimeDataUpdatedAt);
    }

    @Override
    public int hashCode() {
        return Objects.hash(departures, realtimeDataUpdatedAt);
    }

    @Override
    public String toString() {
        String sb = "class StopsIdDeparturesGet2XXResponse {\n" +
                "    departures: " + toIndentedString(departures) + "\n" +
                "    realtimeDataUpdatedAt: " + toIndentedString(realtimeDataUpdatedAt) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

