/*
 * db-vendo-client
 * Schema for db-vendo-client/hafas-rest-api's Friendly Public Transport Format REST API
 *
 * The version of the OpenAPI document: 6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.olech2412.dbvendowrapper.model;

import com.fasterxml.jackson.annotation.*;

import java.math.BigDecimal;
import java.util.*;

/**
 * StopsIdGet2XXResponse
 */
@JsonPropertyOrder({
        StopsIdGet2XXResponse.JSON_PROPERTY_TYPE,
        StopsIdGet2XXResponse.JSON_PROPERTY_ID,
        StopsIdGet2XXResponse.JSON_PROPERTY_NAME,
        StopsIdGet2XXResponse.JSON_PROPERTY_POI,
        StopsIdGet2XXResponse.JSON_PROPERTY_ADDRESS,
        StopsIdGet2XXResponse.JSON_PROPERTY_LONGITUDE,
        StopsIdGet2XXResponse.JSON_PROPERTY_LATITUDE,
        StopsIdGet2XXResponse.JSON_PROPERTY_ALTITUDE,
        StopsIdGet2XXResponse.JSON_PROPERTY_DISTANCE,
        StopsIdGet2XXResponse.JSON_PROPERTY_STATION,
        StopsIdGet2XXResponse.JSON_PROPERTY_LOCATION,
        StopsIdGet2XXResponse.JSON_PROPERTY_PRODUCTS,
        StopsIdGet2XXResponse.JSON_PROPERTY_LINES,
        StopsIdGet2XXResponse.JSON_PROPERTY_IS_META,
        StopsIdGet2XXResponse.JSON_PROPERTY_REGIONS,
        StopsIdGet2XXResponse.JSON_PROPERTY_FACILITIES,
        StopsIdGet2XXResponse.JSON_PROPERTY_REISEZENTRUM_OPENING_HOURS,
        StopsIdGet2XXResponse.JSON_PROPERTY_STOPS,
        StopsIdGet2XXResponse.JSON_PROPERTY_ENTRANCES,
        StopsIdGet2XXResponse.JSON_PROPERTY_TRANSIT_AUTHORITY,
        StopsIdGet2XXResponse.JSON_PROPERTY_IDS,
        StopsIdGet2XXResponse.JSON_PROPERTY_LOAD_FACTOR
})
@JsonTypeName("_stops__id__get_2XX_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-11T16:58:48.518685525+02:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class StopsIdGet2XXResponse {
    public static final String JSON_PROPERTY_TYPE = "type";
    public static final String JSON_PROPERTY_ID = "id";
    public static final String JSON_PROPERTY_NAME = "name";
    public static final String JSON_PROPERTY_POI = "poi";
    public static final String JSON_PROPERTY_ADDRESS = "address";
    public static final String JSON_PROPERTY_LONGITUDE = "longitude";
    public static final String JSON_PROPERTY_LATITUDE = "latitude";
    public static final String JSON_PROPERTY_ALTITUDE = "altitude";
    public static final String JSON_PROPERTY_DISTANCE = "distance";
    public static final String JSON_PROPERTY_STATION = "station";
    public static final String JSON_PROPERTY_LOCATION = "location";
    public static final String JSON_PROPERTY_PRODUCTS = "products";
    public static final String JSON_PROPERTY_LINES = "lines";
    public static final String JSON_PROPERTY_IS_META = "isMeta";
    public static final String JSON_PROPERTY_REGIONS = "regions";
    public static final String JSON_PROPERTY_FACILITIES = "facilities";
    public static final String JSON_PROPERTY_REISEZENTRUM_OPENING_HOURS = "reisezentrumOpeningHours";
    public static final String JSON_PROPERTY_STOPS = "stops";
    public static final String JSON_PROPERTY_ENTRANCES = "entrances";
    public static final String JSON_PROPERTY_TRANSIT_AUTHORITY = "transitAuthority";
    public static final String JSON_PROPERTY_IDS = "ids";
    public static final String JSON_PROPERTY_LOAD_FACTOR = "loadFactor";
    @jakarta.annotation.Nullable
    private TypeEnum type;
    @jakarta.annotation.Nullable
    private String id;
    @jakarta.annotation.Nullable
    private String name;
    @jakarta.annotation.Nullable
    private Boolean poi;
    @jakarta.annotation.Nullable
    private String address;
    @jakarta.annotation.Nullable
    private BigDecimal longitude;
    @jakarta.annotation.Nullable
    private BigDecimal latitude;
    @jakarta.annotation.Nullable
    private BigDecimal altitude;
    @jakarta.annotation.Nullable
    private BigDecimal distance;
    @jakarta.annotation.Nullable
    private Station station;
    @jakarta.annotation.Nullable
    private Location location;
    @jakarta.annotation.Nullable
    private Map<String, Boolean> products = new HashMap<>();
    @jakarta.annotation.Nullable
    private List<Line> lines = new ArrayList<>();
    @jakarta.annotation.Nullable
    private Boolean isMeta;
    @jakarta.annotation.Nullable
    private List<String> regions = new ArrayList<>();
    @jakarta.annotation.Nullable
    private Map<String, String> facilities = new HashMap<>();
    @jakarta.annotation.Nullable
    private ReisezentrumOpeningHours reisezentrumOpeningHours;
    @jakarta.annotation.Nullable
    private List<StopsIdGet2XXResponse> stops = new ArrayList<>();
    @jakarta.annotation.Nullable
    private List<Location> entrances = new ArrayList<>();
    @jakarta.annotation.Nullable
    private String transitAuthority;
    @jakarta.annotation.Nullable
    private Map<String, String> ids = new HashMap<>();
    @jakarta.annotation.Nullable
    private String loadFactor;
    public StopsIdGet2XXResponse() {
    }

    public StopsIdGet2XXResponse type(@jakarta.annotation.Nullable TypeEnum type) {

        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public TypeEnum getType() {
        return type;
    }

    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setType(@jakarta.annotation.Nullable TypeEnum type) {
        this.type = type;
    }

    public StopsIdGet2XXResponse id(@jakarta.annotation.Nullable String id) {

        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getId() {
        return id;
    }

    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setId(@jakarta.annotation.Nullable String id) {
        this.id = id;
    }

    public StopsIdGet2XXResponse name(@jakarta.annotation.Nullable String name) {

        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getName() {
        return name;
    }

    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setName(@jakarta.annotation.Nullable String name) {
        this.name = name;
    }

    public StopsIdGet2XXResponse poi(@jakarta.annotation.Nullable Boolean poi) {

        this.poi = poi;
        return this;
    }

    /**
     * Get poi
     *
     * @return poi
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_POI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getPoi() {
        return poi;
    }

    @JsonProperty(JSON_PROPERTY_POI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPoi(@jakarta.annotation.Nullable Boolean poi) {
        this.poi = poi;
    }

    public StopsIdGet2XXResponse address(@jakarta.annotation.Nullable String address) {

        this.address = address;
        return this;
    }

    /**
     * Get address
     *
     * @return address
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ADDRESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getAddress() {
        return address;
    }

    @JsonProperty(JSON_PROPERTY_ADDRESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAddress(@jakarta.annotation.Nullable String address) {
        this.address = address;
    }

    public StopsIdGet2XXResponse longitude(@jakarta.annotation.Nullable BigDecimal longitude) {

        this.longitude = longitude;
        return this;
    }

    /**
     * Get longitude
     *
     * @return longitude
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LONGITUDE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getLongitude() {
        return longitude;
    }

    @JsonProperty(JSON_PROPERTY_LONGITUDE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLongitude(@jakarta.annotation.Nullable BigDecimal longitude) {
        this.longitude = longitude;
    }

    public StopsIdGet2XXResponse latitude(@jakarta.annotation.Nullable BigDecimal latitude) {

        this.latitude = latitude;
        return this;
    }

    /**
     * Get latitude
     *
     * @return latitude
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LATITUDE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getLatitude() {
        return latitude;
    }

    @JsonProperty(JSON_PROPERTY_LATITUDE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLatitude(@jakarta.annotation.Nullable BigDecimal latitude) {
        this.latitude = latitude;
    }

    public StopsIdGet2XXResponse altitude(@jakarta.annotation.Nullable BigDecimal altitude) {

        this.altitude = altitude;
        return this;
    }

    /**
     * Get altitude
     *
     * @return altitude
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ALTITUDE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getAltitude() {
        return altitude;
    }

    @JsonProperty(JSON_PROPERTY_ALTITUDE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAltitude(@jakarta.annotation.Nullable BigDecimal altitude) {
        this.altitude = altitude;
    }

    public StopsIdGet2XXResponse distance(@jakarta.annotation.Nullable BigDecimal distance) {

        this.distance = distance;
        return this;
    }

    /**
     * Get distance
     *
     * @return distance
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DISTANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getDistance() {
        return distance;
    }

    @JsonProperty(JSON_PROPERTY_DISTANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDistance(@jakarta.annotation.Nullable BigDecimal distance) {
        this.distance = distance;
    }

    public StopsIdGet2XXResponse station(@jakarta.annotation.Nullable Station station) {

        this.station = station;
        return this;
    }

    /**
     * Get station
     *
     * @return station
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_STATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Station getStation() {
        return station;
    }

    @JsonProperty(JSON_PROPERTY_STATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStation(@jakarta.annotation.Nullable Station station) {
        this.station = station;
    }

    public StopsIdGet2XXResponse location(@jakarta.annotation.Nullable Location location) {

        this.location = location;
        return this;
    }

    /**
     * Get location
     *
     * @return location
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LOCATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Location getLocation() {
        return location;
    }

    @JsonProperty(JSON_PROPERTY_LOCATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLocation(@jakarta.annotation.Nullable Location location) {
        this.location = location;
    }

    public StopsIdGet2XXResponse products(@jakarta.annotation.Nullable Map<String, Boolean> products) {

        this.products = products;
        return this;
    }

    public StopsIdGet2XXResponse putProductsItem(String key, Boolean productsItem) {
        if (this.products == null) {
            this.products = new HashMap<>();
        }
        this.products.put(key, productsItem);
        return this;
    }

    /**
     * Each public transportation network exposes its products as boolean properties. See {@link ProductType}
     *
     * @return products
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PRODUCTS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Map<String, Boolean> getProducts() {
        return products;
    }

    @JsonProperty(JSON_PROPERTY_PRODUCTS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProducts(@jakarta.annotation.Nullable Map<String, Boolean> products) {
        this.products = products;
    }

    public StopsIdGet2XXResponse lines(@jakarta.annotation.Nullable List<Line> lines) {

        this.lines = lines;
        return this;
    }

    public StopsIdGet2XXResponse addLinesItem(Line linesItem) {
        if (this.lines == null) {
            this.lines = new ArrayList<>();
        }
        this.lines.add(linesItem);
        return this;
    }

    /**
     * Get lines
     *
     * @return lines
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LINES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<Line> getLines() {
        return lines;
    }

    @JsonProperty(JSON_PROPERTY_LINES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLines(@jakarta.annotation.Nullable List<Line> lines) {
        this.lines = lines;
    }

    public StopsIdGet2XXResponse isMeta(@jakarta.annotation.Nullable Boolean isMeta) {

        this.isMeta = isMeta;
        return this;
    }

    /**
     * Get isMeta
     *
     * @return isMeta
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_IS_META)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getIsMeta() {
        return isMeta;
    }

    @JsonProperty(JSON_PROPERTY_IS_META)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIsMeta(@jakarta.annotation.Nullable Boolean isMeta) {
        this.isMeta = isMeta;
    }

    public StopsIdGet2XXResponse regions(@jakarta.annotation.Nullable List<String> regions) {

        this.regions = regions;
        return this;
    }

    public StopsIdGet2XXResponse addRegionsItem(String regionsItem) {
        if (this.regions == null) {
            this.regions = new ArrayList<>();
        }
        this.regions.add(regionsItem);
        return this;
    }

    /**
     * region ids
     *
     * @return regions
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_REGIONS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<String> getRegions() {
        return regions;
    }

    @JsonProperty(JSON_PROPERTY_REGIONS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRegions(@jakarta.annotation.Nullable List<String> regions) {
        this.regions = regions;
    }

    public StopsIdGet2XXResponse facilities(@jakarta.annotation.Nullable Map<String, String> facilities) {

        this.facilities = facilities;
        return this;
    }

    public StopsIdGet2XXResponse putFacilitiesItem(String key, String facilitiesItem) {
        if (this.facilities == null) {
            this.facilities = new HashMap<>();
        }
        this.facilities.put(key, facilitiesItem);
        return this;
    }

    /**
     * Get facilities
     *
     * @return facilities
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_FACILITIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Map<String, String> getFacilities() {
        return facilities;
    }

    @JsonProperty(JSON_PROPERTY_FACILITIES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFacilities(@jakarta.annotation.Nullable Map<String, String> facilities) {
        this.facilities = facilities;
    }

    public StopsIdGet2XXResponse reisezentrumOpeningHours(@jakarta.annotation.Nullable ReisezentrumOpeningHours reisezentrumOpeningHours) {

        this.reisezentrumOpeningHours = reisezentrumOpeningHours;
        return this;
    }

    /**
     * Get reisezentrumOpeningHours
     *
     * @return reisezentrumOpeningHours
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_REISEZENTRUM_OPENING_HOURS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public ReisezentrumOpeningHours getReisezentrumOpeningHours() {
        return reisezentrumOpeningHours;
    }

    @JsonProperty(JSON_PROPERTY_REISEZENTRUM_OPENING_HOURS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setReisezentrumOpeningHours(@jakarta.annotation.Nullable ReisezentrumOpeningHours reisezentrumOpeningHours) {
        this.reisezentrumOpeningHours = reisezentrumOpeningHours;
    }

    public StopsIdGet2XXResponse stops(@jakarta.annotation.Nullable List<StopsIdGet2XXResponse> stops) {

        this.stops = stops;
        return this;
    }

    public StopsIdGet2XXResponse addStopsItem(StopsIdGet2XXResponse stopsItem) {
        if (this.stops == null) {
            this.stops = new ArrayList<>();
        }
        this.stops.add(stopsItem);
        return this;
    }

    /**
     * Get stops
     *
     * @return stops
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_STOPS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<StopsIdGet2XXResponse> getStops() {
        return stops;
    }

    @JsonProperty(JSON_PROPERTY_STOPS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStops(@jakarta.annotation.Nullable List<StopsIdGet2XXResponse> stops) {
        this.stops = stops;
    }

    public StopsIdGet2XXResponse entrances(@jakarta.annotation.Nullable List<Location> entrances) {

        this.entrances = entrances;
        return this;
    }

    public StopsIdGet2XXResponse addEntrancesItem(Location entrancesItem) {
        if (this.entrances == null) {
            this.entrances = new ArrayList<>();
        }
        this.entrances.add(entrancesItem);
        return this;
    }

    /**
     * Get entrances
     *
     * @return entrances
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ENTRANCES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<Location> getEntrances() {
        return entrances;
    }

    @JsonProperty(JSON_PROPERTY_ENTRANCES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEntrances(@jakarta.annotation.Nullable List<Location> entrances) {
        this.entrances = entrances;
    }

    public StopsIdGet2XXResponse transitAuthority(@jakarta.annotation.Nullable String transitAuthority) {

        this.transitAuthority = transitAuthority;
        return this;
    }

    /**
     * Get transitAuthority
     *
     * @return transitAuthority
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TRANSIT_AUTHORITY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getTransitAuthority() {
        return transitAuthority;
    }

    @JsonProperty(JSON_PROPERTY_TRANSIT_AUTHORITY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTransitAuthority(@jakarta.annotation.Nullable String transitAuthority) {
        this.transitAuthority = transitAuthority;
    }

    public StopsIdGet2XXResponse ids(@jakarta.annotation.Nullable Map<String, String> ids) {

        this.ids = ids;
        return this;
    }

    public StopsIdGet2XXResponse putIdsItem(String key, String idsItem) {
        if (this.ids == null) {
            this.ids = new HashMap<>();
        }
        this.ids.put(key, idsItem);
        return this;
    }

    /**
     * Ids of a Stop, i.e. dhid as &#39;DELFI Haltestellen ID&#39;
     *
     * @return ids
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_IDS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Map<String, String> getIds() {
        return ids;
    }

    @JsonProperty(JSON_PROPERTY_IDS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setIds(@jakarta.annotation.Nullable Map<String, String> ids) {
        this.ids = ids;
    }

    public StopsIdGet2XXResponse loadFactor(@jakarta.annotation.Nullable String loadFactor) {

        this.loadFactor = loadFactor;
        return this;
    }

    /**
     * Get loadFactor
     *
     * @return loadFactor
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LOAD_FACTOR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getLoadFactor() {
        return loadFactor;
    }

    @JsonProperty(JSON_PROPERTY_LOAD_FACTOR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLoadFactor(@jakarta.annotation.Nullable String loadFactor) {
        this.loadFactor = loadFactor;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StopsIdGet2XXResponse stopsIdGet2XXResponse = (StopsIdGet2XXResponse) o;
        return Objects.equals(this.type, stopsIdGet2XXResponse.type) &&
                Objects.equals(this.id, stopsIdGet2XXResponse.id) &&
                Objects.equals(this.name, stopsIdGet2XXResponse.name) &&
                Objects.equals(this.poi, stopsIdGet2XXResponse.poi) &&
                Objects.equals(this.address, stopsIdGet2XXResponse.address) &&
                Objects.equals(this.longitude, stopsIdGet2XXResponse.longitude) &&
                Objects.equals(this.latitude, stopsIdGet2XXResponse.latitude) &&
                Objects.equals(this.altitude, stopsIdGet2XXResponse.altitude) &&
                Objects.equals(this.distance, stopsIdGet2XXResponse.distance) &&
                Objects.equals(this.station, stopsIdGet2XXResponse.station) &&
                Objects.equals(this.location, stopsIdGet2XXResponse.location) &&
                Objects.equals(this.products, stopsIdGet2XXResponse.products) &&
                Objects.equals(this.lines, stopsIdGet2XXResponse.lines) &&
                Objects.equals(this.isMeta, stopsIdGet2XXResponse.isMeta) &&
                Objects.equals(this.regions, stopsIdGet2XXResponse.regions) &&
                Objects.equals(this.facilities, stopsIdGet2XXResponse.facilities) &&
                Objects.equals(this.reisezentrumOpeningHours, stopsIdGet2XXResponse.reisezentrumOpeningHours) &&
                Objects.equals(this.stops, stopsIdGet2XXResponse.stops) &&
                Objects.equals(this.entrances, stopsIdGet2XXResponse.entrances) &&
                Objects.equals(this.transitAuthority, stopsIdGet2XXResponse.transitAuthority) &&
                Objects.equals(this.ids, stopsIdGet2XXResponse.ids) &&
                Objects.equals(this.loadFactor, stopsIdGet2XXResponse.loadFactor);
    }

    @Override
    public int hashCode() {
        return Objects.hash(type, id, name, poi, address, longitude, latitude, altitude, distance, station, location, products, lines, isMeta, regions, facilities, reisezentrumOpeningHours, stops, entrances, transitAuthority, ids, loadFactor);
    }

    @Override
    public String toString() {
        String sb = "class StopsIdGet2XXResponse {\n" +
                "    type: " + toIndentedString(type) + "\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    poi: " + toIndentedString(poi) + "\n" +
                "    address: " + toIndentedString(address) + "\n" +
                "    longitude: " + toIndentedString(longitude) + "\n" +
                "    latitude: " + toIndentedString(latitude) + "\n" +
                "    altitude: " + toIndentedString(altitude) + "\n" +
                "    distance: " + toIndentedString(distance) + "\n" +
                "    station: " + toIndentedString(station) + "\n" +
                "    location: " + toIndentedString(location) + "\n" +
                "    products: " + toIndentedString(products) + "\n" +
                "    lines: " + toIndentedString(lines) + "\n" +
                "    isMeta: " + toIndentedString(isMeta) + "\n" +
                "    regions: " + toIndentedString(regions) + "\n" +
                "    facilities: " + toIndentedString(facilities) + "\n" +
                "    reisezentrumOpeningHours: " + toIndentedString(reisezentrumOpeningHours) + "\n" +
                "    stops: " + toIndentedString(stops) + "\n" +
                "    entrances: " + toIndentedString(entrances) + "\n" +
                "    transitAuthority: " + toIndentedString(transitAuthority) + "\n" +
                "    ids: " + toIndentedString(ids) + "\n" +
                "    loadFactor: " + toIndentedString(loadFactor) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Gets or Sets type
     */
    public enum TypeEnum {
        LOCATION("location"),

        STATION("station"),

        STOP("stop");

        private final String value;

        TypeEnum(String value) {
            this.value = value;
        }

        @JsonCreator
        public static TypeEnum fromValue(String value) {
            for (TypeEnum b : TypeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }
    }

}

