/*
 * db-vendo-client
 * Schema for db-vendo-client/hafas-rest-api's Friendly Public Transport Format REST API
 *
 * The version of the OpenAPI document: 6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.olech2412.dbvendoclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * BoundingBox
 */
@JsonPropertyOrder({
        BoundingBox.JSON_PROPERTY_NORTH,
        BoundingBox.JSON_PROPERTY_WEST,
        BoundingBox.JSON_PROPERTY_SOUTH,
        BoundingBox.JSON_PROPERTY_EAST
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-11T16:58:48.518685525+02:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class BoundingBox {
    public static final String JSON_PROPERTY_NORTH = "north";
    public static final String JSON_PROPERTY_WEST = "west";
    public static final String JSON_PROPERTY_SOUTH = "south";
    public static final String JSON_PROPERTY_EAST = "east";
    @jakarta.annotation.Nullable
    private BigDecimal north;
    @jakarta.annotation.Nullable
    private BigDecimal west;
    @jakarta.annotation.Nullable
    private BigDecimal south;
    @jakarta.annotation.Nullable
    private BigDecimal east;

    public BoundingBox() {
    }

    public BoundingBox north(@jakarta.annotation.Nullable BigDecimal north) {

        this.north = north;
        return this;
    }

    /**
     * Get north
     *
     * @return north
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_NORTH)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getNorth() {
        return north;
    }


    @JsonProperty(JSON_PROPERTY_NORTH)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setNorth(@jakarta.annotation.Nullable BigDecimal north) {
        this.north = north;
    }

    public BoundingBox west(@jakarta.annotation.Nullable BigDecimal west) {

        this.west = west;
        return this;
    }

    /**
     * Get west
     *
     * @return west
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_WEST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getWest() {
        return west;
    }


    @JsonProperty(JSON_PROPERTY_WEST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setWest(@jakarta.annotation.Nullable BigDecimal west) {
        this.west = west;
    }

    public BoundingBox south(@jakarta.annotation.Nullable BigDecimal south) {

        this.south = south;
        return this;
    }

    /**
     * Get south
     *
     * @return south
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SOUTH)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getSouth() {
        return south;
    }


    @JsonProperty(JSON_PROPERTY_SOUTH)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSouth(@jakarta.annotation.Nullable BigDecimal south) {
        this.south = south;
    }

    public BoundingBox east(@jakarta.annotation.Nullable BigDecimal east) {

        this.east = east;
        return this;
    }

    /**
     * Get east
     *
     * @return east
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_EAST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getEast() {
        return east;
    }


    @JsonProperty(JSON_PROPERTY_EAST)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEast(@jakarta.annotation.Nullable BigDecimal east) {
        this.east = east;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        BoundingBox boundingBox = (BoundingBox) o;
        return Objects.equals(this.north, boundingBox.north) &&
                Objects.equals(this.west, boundingBox.west) &&
                Objects.equals(this.south, boundingBox.south) &&
                Objects.equals(this.east, boundingBox.east);
    }

    @Override
    public int hashCode() {
        return Objects.hash(north, west, south, east);
    }

    @Override
    public String toString() {
        String sb = "class BoundingBox {\n" +
                "    north: " + toIndentedString(north) + "\n" +
                "    west: " + toIndentedString(west) + "\n" +
                "    south: " + toIndentedString(south) + "\n" +
                "    east: " + toIndentedString(east) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

