/*
 * db-vendo-client
 * Schema for db-vendo-client/hafas-rest-api's Friendly Public Transport Format REST API
 *
 * The version of the OpenAPI document: 6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.olech2412.dbvendoclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * JourneysOptions
 */
@JsonPropertyOrder({
        JourneysOptions.JSON_PROPERTY_DEPARTURE,
        JourneysOptions.JSON_PROPERTY_ARRIVAL,
        JourneysOptions.JSON_PROPERTY_EARLIER_THAN,
        JourneysOptions.JSON_PROPERTY_LATER_THAN,
        JourneysOptions.JSON_PROPERTY_RESULTS,
        JourneysOptions.JSON_PROPERTY_VIA,
        JourneysOptions.JSON_PROPERTY_STOPOVERS,
        JourneysOptions.JSON_PROPERTY_TRANSFERS,
        JourneysOptions.JSON_PROPERTY_TRANSFER_TIME,
        JourneysOptions.JSON_PROPERTY_ACCESSIBILITY,
        JourneysOptions.JSON_PROPERTY_BIKE,
        JourneysOptions.JSON_PROPERTY_PRODUCTS,
        JourneysOptions.JSON_PROPERTY_TICKETS,
        JourneysOptions.JSON_PROPERTY_POLYLINES,
        JourneysOptions.JSON_PROPERTY_SUB_STOPS,
        JourneysOptions.JSON_PROPERTY_ENTRANCES,
        JourneysOptions.JSON_PROPERTY_REMARKS,
        JourneysOptions.JSON_PROPERTY_WALKING_SPEED,
        JourneysOptions.JSON_PROPERTY_START_WITH_WALKING,
        JourneysOptions.JSON_PROPERTY_LANGUAGE,
        JourneysOptions.JSON_PROPERTY_SCHEDULED_DAYS,
        JourneysOptions.JSON_PROPERTY_WHEN,
        JourneysOptions.JSON_PROPERTY_FIRST_CLASS,
        JourneysOptions.JSON_PROPERTY_AGE_GROUP,
        JourneysOptions.JSON_PROPERTY_AGE,
        JourneysOptions.JSON_PROPERTY_LOYALTY_CARD,
        JourneysOptions.JSON_PROPERTY_ROUTING_MODE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-11T16:58:48.518685525+02:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class JourneysOptions {
    public static final String JSON_PROPERTY_DEPARTURE = "departure";
    public static final String JSON_PROPERTY_ARRIVAL = "arrival";
    public static final String JSON_PROPERTY_EARLIER_THAN = "earlierThan";
    public static final String JSON_PROPERTY_LATER_THAN = "laterThan";
    public static final String JSON_PROPERTY_RESULTS = "results";
    public static final String JSON_PROPERTY_VIA = "via";
    public static final String JSON_PROPERTY_STOPOVERS = "stopovers";
    public static final String JSON_PROPERTY_TRANSFERS = "transfers";
    public static final String JSON_PROPERTY_TRANSFER_TIME = "transferTime";
    public static final String JSON_PROPERTY_ACCESSIBILITY = "accessibility";
    public static final String JSON_PROPERTY_BIKE = "bike";
    public static final String JSON_PROPERTY_PRODUCTS = "products";
    public static final String JSON_PROPERTY_TICKETS = "tickets";
    public static final String JSON_PROPERTY_POLYLINES = "polylines";
    public static final String JSON_PROPERTY_SUB_STOPS = "subStops";
    public static final String JSON_PROPERTY_ENTRANCES = "entrances";
    public static final String JSON_PROPERTY_REMARKS = "remarks";
    public static final String JSON_PROPERTY_WALKING_SPEED = "walkingSpeed";
    public static final String JSON_PROPERTY_START_WITH_WALKING = "startWithWalking";
    public static final String JSON_PROPERTY_LANGUAGE = "language";
    public static final String JSON_PROPERTY_SCHEDULED_DAYS = "scheduledDays";
    public static final String JSON_PROPERTY_WHEN = "when";
    public static final String JSON_PROPERTY_FIRST_CLASS = "firstClass";
    public static final String JSON_PROPERTY_AGE_GROUP = "ageGroup";
    public static final String JSON_PROPERTY_AGE = "age";
    public static final String JSON_PROPERTY_LOYALTY_CARD = "loyaltyCard";
    public static final String JSON_PROPERTY_ROUTING_MODE = "routingMode";
    @jakarta.annotation.Nullable
    private OffsetDateTime departure;
    @jakarta.annotation.Nullable
    private OffsetDateTime arrival;
    @jakarta.annotation.Nullable
    private String earlierThan;
    @jakarta.annotation.Nullable
    private String laterThan;
    @jakarta.annotation.Nullable
    private BigDecimal results = new BigDecimal("3");
    @jakarta.annotation.Nullable
    private String via;
    @jakarta.annotation.Nullable
    private Boolean stopovers = false;
    @jakarta.annotation.Nullable
    private BigDecimal transfers = new BigDecimal("10");
    @jakarta.annotation.Nullable
    private BigDecimal transferTime = new BigDecimal("10");
    @jakarta.annotation.Nullable
    private String accessibility = "none";
    @jakarta.annotation.Nullable
    private Boolean bike = false;
    @jakarta.annotation.Nullable
    private Map<String, Boolean> products = new HashMap<>();
    @jakarta.annotation.Nullable
    private Boolean tickets = false;
    @jakarta.annotation.Nullable
    private Boolean polylines = false;
    @jakarta.annotation.Nullable
    private Boolean subStops = false;
    @jakarta.annotation.Nullable
    private Boolean entrances = true;
    @jakarta.annotation.Nullable
    private Boolean remarks = true;
    @jakarta.annotation.Nullable
    private String walkingSpeed = "slow";
    @jakarta.annotation.Nullable
    private Boolean startWithWalking = false;
    @jakarta.annotation.Nullable
    private String language = "en";
    @jakarta.annotation.Nullable
    private Boolean scheduledDays = false;
    @jakarta.annotation.Nullable
    private OffsetDateTime when;
    @jakarta.annotation.Nullable
    private Boolean firstClass = false;
    @jakarta.annotation.Nullable
    private AgeGroup ageGroup;
    @jakarta.annotation.Nullable
    private BigDecimal age;
    @jakarta.annotation.Nullable
    private LoyaltyCard loyaltyCard;
    @jakarta.annotation.Nullable
    private RoutingMode routingMode;

    public JourneysOptions() {
    }

    public JourneysOptions departure(@jakarta.annotation.Nullable OffsetDateTime departure) {

        this.departure = departure;
        return this;
    }

    /**
     * departure date, undefined corresponds to Date.Now
     *
     * @return departure
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DEPARTURE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getDeparture() {
        return departure;
    }


    @JsonProperty(JSON_PROPERTY_DEPARTURE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDeparture(@jakarta.annotation.Nullable OffsetDateTime departure) {
        this.departure = departure;
    }

    public JourneysOptions arrival(@jakarta.annotation.Nullable OffsetDateTime arrival) {

        this.arrival = arrival;
        return this;
    }

    /**
     * arrival date, departure and arrival are mutually exclusive.
     *
     * @return arrival
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ARRIVAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getArrival() {
        return arrival;
    }


    @JsonProperty(JSON_PROPERTY_ARRIVAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setArrival(@jakarta.annotation.Nullable OffsetDateTime arrival) {
        this.arrival = arrival;
    }

    public JourneysOptions earlierThan(@jakarta.annotation.Nullable String earlierThan) {

        this.earlierThan = earlierThan;
        return this;
    }

    /**
     * earlierThan, use {@link Journeys#earlierRef}, earlierThan and departure/arrival are mutually exclusive.
     *
     * @return earlierThan
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_EARLIER_THAN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getEarlierThan() {
        return earlierThan;
    }


    @JsonProperty(JSON_PROPERTY_EARLIER_THAN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEarlierThan(@jakarta.annotation.Nullable String earlierThan) {
        this.earlierThan = earlierThan;
    }

    public JourneysOptions laterThan(@jakarta.annotation.Nullable String laterThan) {

        this.laterThan = laterThan;
        return this;
    }

    /**
     * laterThan, use {@link Journeys#laterRef}, laterThan and departure/arrival are mutually exclusive.
     *
     * @return laterThan
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LATER_THAN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getLaterThan() {
        return laterThan;
    }


    @JsonProperty(JSON_PROPERTY_LATER_THAN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLaterThan(@jakarta.annotation.Nullable String laterThan) {
        this.laterThan = laterThan;
    }

    public JourneysOptions results(@jakarta.annotation.Nullable BigDecimal results) {

        this.results = results;
        return this;
    }

    /**
     * how many search results?
     *
     * @return results
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_RESULTS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getResults() {
        return results;
    }


    @JsonProperty(JSON_PROPERTY_RESULTS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setResults(@jakarta.annotation.Nullable BigDecimal results) {
        this.results = results;
    }

    public JourneysOptions via(@jakarta.annotation.Nullable String via) {

        this.via = via;
        return this;
    }

    /**
     * let journeys pass this station
     *
     * @return via
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_VIA)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getVia() {
        return via;
    }


    @JsonProperty(JSON_PROPERTY_VIA)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setVia(@jakarta.annotation.Nullable String via) {
        this.via = via;
    }

    public JourneysOptions stopovers(@jakarta.annotation.Nullable Boolean stopovers) {

        this.stopovers = stopovers;
        return this;
    }

    /**
     * return stations on the way?
     *
     * @return stopovers
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_STOPOVERS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getStopovers() {
        return stopovers;
    }


    @JsonProperty(JSON_PROPERTY_STOPOVERS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStopovers(@jakarta.annotation.Nullable Boolean stopovers) {
        this.stopovers = stopovers;
    }

    public JourneysOptions transfers(@jakarta.annotation.Nullable BigDecimal transfers) {

        this.transfers = transfers;
        return this;
    }

    /**
     * Maximum nr of transfers. Default: Let HAFAS decide.
     *
     * @return transfers
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TRANSFERS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getTransfers() {
        return transfers;
    }


    @JsonProperty(JSON_PROPERTY_TRANSFERS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTransfers(@jakarta.annotation.Nullable BigDecimal transfers) {
        this.transfers = transfers;
    }

    public JourneysOptions transferTime(@jakarta.annotation.Nullable BigDecimal transferTime) {

        this.transferTime = transferTime;
        return this;
    }

    /**
     * minimum time for a single transfer in minutes
     *
     * @return transferTime
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TRANSFER_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getTransferTime() {
        return transferTime;
    }


    @JsonProperty(JSON_PROPERTY_TRANSFER_TIME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTransferTime(@jakarta.annotation.Nullable BigDecimal transferTime) {
        this.transferTime = transferTime;
    }

    public JourneysOptions accessibility(@jakarta.annotation.Nullable String accessibility) {

        this.accessibility = accessibility;
        return this;
    }

    /**
     * &#39;none&#39;, &#39;partial&#39; or &#39;complete&#39;
     *
     * @return accessibility
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ACCESSIBILITY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getAccessibility() {
        return accessibility;
    }


    @JsonProperty(JSON_PROPERTY_ACCESSIBILITY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAccessibility(@jakarta.annotation.Nullable String accessibility) {
        this.accessibility = accessibility;
    }

    public JourneysOptions bike(@jakarta.annotation.Nullable Boolean bike) {

        this.bike = bike;
        return this;
    }

    /**
     * only bike-friendly journeys
     *
     * @return bike
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_BIKE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getBike() {
        return bike;
    }


    @JsonProperty(JSON_PROPERTY_BIKE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setBike(@jakarta.annotation.Nullable Boolean bike) {
        this.bike = bike;
    }

    public JourneysOptions products(@jakarta.annotation.Nullable Map<String, Boolean> products) {

        this.products = products;
        return this;
    }

    public JourneysOptions putProductsItem(String key, Boolean productsItem) {
        if (this.products == null) {
            this.products = new HashMap<>();
        }
        this.products.put(key, productsItem);
        return this;
    }

    /**
     * Each public transportation network exposes its products as boolean properties. See {@link ProductType}
     *
     * @return products
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PRODUCTS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Map<String, Boolean> getProducts() {
        return products;
    }


    @JsonProperty(JSON_PROPERTY_PRODUCTS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProducts(@jakarta.annotation.Nullable Map<String, Boolean> products) {
        this.products = products;
    }

    public JourneysOptions tickets(@jakarta.annotation.Nullable Boolean tickets) {

        this.tickets = tickets;
        return this;
    }

    /**
     * return tickets? only available with some profiles
     *
     * @return tickets
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TICKETS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getTickets() {
        return tickets;
    }


    @JsonProperty(JSON_PROPERTY_TICKETS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTickets(@jakarta.annotation.Nullable Boolean tickets) {
        this.tickets = tickets;
    }

    public JourneysOptions polylines(@jakarta.annotation.Nullable Boolean polylines) {

        this.polylines = polylines;
        return this;
    }

    /**
     * return a shape for each leg?
     *
     * @return polylines
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_POLYLINES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getPolylines() {
        return polylines;
    }


    @JsonProperty(JSON_PROPERTY_POLYLINES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPolylines(@jakarta.annotation.Nullable Boolean polylines) {
        this.polylines = polylines;
    }

    public JourneysOptions subStops(@jakarta.annotation.Nullable Boolean subStops) {

        this.subStops = subStops;
        return this;
    }

    /**
     * parse &amp; expose sub-stops of stations?
     *
     * @return subStops
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SUB_STOPS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getSubStops() {
        return subStops;
    }


    @JsonProperty(JSON_PROPERTY_SUB_STOPS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSubStops(@jakarta.annotation.Nullable Boolean subStops) {
        this.subStops = subStops;
    }

    public JourneysOptions entrances(@jakarta.annotation.Nullable Boolean entrances) {

        this.entrances = entrances;
        return this;
    }

    /**
     * parse &amp; expose entrances of stops/stations?
     *
     * @return entrances
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ENTRANCES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getEntrances() {
        return entrances;
    }


    @JsonProperty(JSON_PROPERTY_ENTRANCES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEntrances(@jakarta.annotation.Nullable Boolean entrances) {
        this.entrances = entrances;
    }

    public JourneysOptions remarks(@jakarta.annotation.Nullable Boolean remarks) {

        this.remarks = remarks;
        return this;
    }

    /**
     * parse &amp; expose hints &amp; warnings?
     *
     * @return remarks
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_REMARKS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getRemarks() {
        return remarks;
    }


    @JsonProperty(JSON_PROPERTY_REMARKS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRemarks(@jakarta.annotation.Nullable Boolean remarks) {
        this.remarks = remarks;
    }

    public JourneysOptions walkingSpeed(@jakarta.annotation.Nullable String walkingSpeed) {

        this.walkingSpeed = walkingSpeed;
        return this;
    }

    /**
     * &#39;slow&#39;, &#39;normal&#39;, &#39;fast&#39;
     *
     * @return walkingSpeed
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_WALKING_SPEED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getWalkingSpeed() {
        return walkingSpeed;
    }


    @JsonProperty(JSON_PROPERTY_WALKING_SPEED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setWalkingSpeed(@jakarta.annotation.Nullable String walkingSpeed) {
        this.walkingSpeed = walkingSpeed;
    }

    public JourneysOptions startWithWalking(@jakarta.annotation.Nullable Boolean startWithWalking) {

        this.startWithWalking = startWithWalking;
        return this;
    }

    /**
     * start with walking
     *
     * @return startWithWalking
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_START_WITH_WALKING)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getStartWithWalking() {
        return startWithWalking;
    }


    @JsonProperty(JSON_PROPERTY_START_WITH_WALKING)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStartWithWalking(@jakarta.annotation.Nullable Boolean startWithWalking) {
        this.startWithWalking = startWithWalking;
    }

    public JourneysOptions language(@jakarta.annotation.Nullable String language) {

        this.language = language;
        return this;
    }

    /**
     * language to get results in
     *
     * @return language
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LANGUAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getLanguage() {
        return language;
    }


    @JsonProperty(JSON_PROPERTY_LANGUAGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLanguage(@jakarta.annotation.Nullable String language) {
        this.language = language;
    }

    public JourneysOptions scheduledDays(@jakarta.annotation.Nullable Boolean scheduledDays) {

        this.scheduledDays = scheduledDays;
        return this;
    }

    /**
     * parse which days each journey is valid on
     *
     * @return scheduledDays
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SCHEDULED_DAYS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getScheduledDays() {
        return scheduledDays;
    }


    @JsonProperty(JSON_PROPERTY_SCHEDULED_DAYS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setScheduledDays(@jakarta.annotation.Nullable Boolean scheduledDays) {
        this.scheduledDays = scheduledDays;
    }

    public JourneysOptions when(@jakarta.annotation.Nullable OffsetDateTime when) {

        this.when = when;
        return this;
    }

    /**
     * Get when
     *
     * @return when
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_WHEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public OffsetDateTime getWhen() {
        return when;
    }


    @JsonProperty(JSON_PROPERTY_WHEN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setWhen(@jakarta.annotation.Nullable OffsetDateTime when) {
        this.when = when;
    }

    public JourneysOptions firstClass(@jakarta.annotation.Nullable Boolean firstClass) {

        this.firstClass = firstClass;
        return this;
    }

    /**
     * firstClass
     *
     * @return firstClass
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_FIRST_CLASS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getFirstClass() {
        return firstClass;
    }


    @JsonProperty(JSON_PROPERTY_FIRST_CLASS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFirstClass(@jakarta.annotation.Nullable Boolean firstClass) {
        this.firstClass = firstClass;
    }

    public JourneysOptions ageGroup(@jakarta.annotation.Nullable AgeGroup ageGroup) {

        this.ageGroup = ageGroup;
        return this;
    }

    /**
     * Get ageGroup
     *
     * @return ageGroup
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_AGE_GROUP)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public AgeGroup getAgeGroup() {
        return ageGroup;
    }


    @JsonProperty(JSON_PROPERTY_AGE_GROUP)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAgeGroup(@jakarta.annotation.Nullable AgeGroup ageGroup) {
        this.ageGroup = ageGroup;
    }

    public JourneysOptions age(@jakarta.annotation.Nullable BigDecimal age) {

        this.age = age;
        return this;
    }

    /**
     * age
     *
     * @return age
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_AGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getAge() {
        return age;
    }


    @JsonProperty(JSON_PROPERTY_AGE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAge(@jakarta.annotation.Nullable BigDecimal age) {
        this.age = age;
    }

    public JourneysOptions loyaltyCard(@jakarta.annotation.Nullable LoyaltyCard loyaltyCard) {

        this.loyaltyCard = loyaltyCard;
        return this;
    }

    /**
     * Get loyaltyCard
     *
     * @return loyaltyCard
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LOYALTY_CARD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public LoyaltyCard getLoyaltyCard() {
        return loyaltyCard;
    }


    @JsonProperty(JSON_PROPERTY_LOYALTY_CARD)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLoyaltyCard(@jakarta.annotation.Nullable LoyaltyCard loyaltyCard) {
        this.loyaltyCard = loyaltyCard;
    }

    public JourneysOptions routingMode(@jakarta.annotation.Nullable RoutingMode routingMode) {

        this.routingMode = routingMode;
        return this;
    }

    /**
     * Get routingMode
     *
     * @return routingMode
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ROUTING_MODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public RoutingMode getRoutingMode() {
        return routingMode;
    }


    @JsonProperty(JSON_PROPERTY_ROUTING_MODE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRoutingMode(@jakarta.annotation.Nullable RoutingMode routingMode) {
        this.routingMode = routingMode;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        JourneysOptions journeysOptions = (JourneysOptions) o;
        return Objects.equals(this.departure, journeysOptions.departure) &&
                Objects.equals(this.arrival, journeysOptions.arrival) &&
                Objects.equals(this.earlierThan, journeysOptions.earlierThan) &&
                Objects.equals(this.laterThan, journeysOptions.laterThan) &&
                Objects.equals(this.results, journeysOptions.results) &&
                Objects.equals(this.via, journeysOptions.via) &&
                Objects.equals(this.stopovers, journeysOptions.stopovers) &&
                Objects.equals(this.transfers, journeysOptions.transfers) &&
                Objects.equals(this.transferTime, journeysOptions.transferTime) &&
                Objects.equals(this.accessibility, journeysOptions.accessibility) &&
                Objects.equals(this.bike, journeysOptions.bike) &&
                Objects.equals(this.products, journeysOptions.products) &&
                Objects.equals(this.tickets, journeysOptions.tickets) &&
                Objects.equals(this.polylines, journeysOptions.polylines) &&
                Objects.equals(this.subStops, journeysOptions.subStops) &&
                Objects.equals(this.entrances, journeysOptions.entrances) &&
                Objects.equals(this.remarks, journeysOptions.remarks) &&
                Objects.equals(this.walkingSpeed, journeysOptions.walkingSpeed) &&
                Objects.equals(this.startWithWalking, journeysOptions.startWithWalking) &&
                Objects.equals(this.language, journeysOptions.language) &&
                Objects.equals(this.scheduledDays, journeysOptions.scheduledDays) &&
                Objects.equals(this.when, journeysOptions.when) &&
                Objects.equals(this.firstClass, journeysOptions.firstClass) &&
                Objects.equals(this.ageGroup, journeysOptions.ageGroup) &&
                Objects.equals(this.age, journeysOptions.age) &&
                Objects.equals(this.loyaltyCard, journeysOptions.loyaltyCard) &&
                Objects.equals(this.routingMode, journeysOptions.routingMode);
    }

    @Override
    public int hashCode() {
        return Objects.hash(departure, arrival, earlierThan, laterThan, results, via, stopovers, transfers, transferTime, accessibility, bike, products, tickets, polylines, subStops, entrances, remarks, walkingSpeed, startWithWalking, language, scheduledDays, when, firstClass, ageGroup, age, loyaltyCard, routingMode);
    }

    @Override
    public String toString() {
        String sb = "class JourneysOptions {\n" +
                "    departure: " + toIndentedString(departure) + "\n" +
                "    arrival: " + toIndentedString(arrival) + "\n" +
                "    earlierThan: " + toIndentedString(earlierThan) + "\n" +
                "    laterThan: " + toIndentedString(laterThan) + "\n" +
                "    results: " + toIndentedString(results) + "\n" +
                "    via: " + toIndentedString(via) + "\n" +
                "    stopovers: " + toIndentedString(stopovers) + "\n" +
                "    transfers: " + toIndentedString(transfers) + "\n" +
                "    transferTime: " + toIndentedString(transferTime) + "\n" +
                "    accessibility: " + toIndentedString(accessibility) + "\n" +
                "    bike: " + toIndentedString(bike) + "\n" +
                "    products: " + toIndentedString(products) + "\n" +
                "    tickets: " + toIndentedString(tickets) + "\n" +
                "    polylines: " + toIndentedString(polylines) + "\n" +
                "    subStops: " + toIndentedString(subStops) + "\n" +
                "    entrances: " + toIndentedString(entrances) + "\n" +
                "    remarks: " + toIndentedString(remarks) + "\n" +
                "    walkingSpeed: " + toIndentedString(walkingSpeed) + "\n" +
                "    startWithWalking: " + toIndentedString(startWithWalking) + "\n" +
                "    language: " + toIndentedString(language) + "\n" +
                "    scheduledDays: " + toIndentedString(scheduledDays) + "\n" +
                "    when: " + toIndentedString(when) + "\n" +
                "    firstClass: " + toIndentedString(firstClass) + "\n" +
                "    ageGroup: " + toIndentedString(ageGroup) + "\n" +
                "    age: " + toIndentedString(age) + "\n" +
                "    loyaltyCard: " + toIndentedString(loyaltyCard) + "\n" +
                "    routingMode: " + toIndentedString(routingMode) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

