/*
 * db-vendo-client
 * Schema for db-vendo-client/hafas-rest-api's Friendly Public Transport Format REST API
 *
 * The version of the OpenAPI document: 6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.olech2412.dbvendoclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * JourneysGet2XXResponse
 */
@JsonPropertyOrder({
        JourneysGet2XXResponse.JSON_PROPERTY_JOURNEYS,
        JourneysGet2XXResponse.JSON_PROPERTY_REALTIME_DATA_UPDATED_AT,
        JourneysGet2XXResponse.JSON_PROPERTY_EARLIER_REF,
        JourneysGet2XXResponse.JSON_PROPERTY_LATER_REF
})
@JsonTypeName("_journeys_get_2XX_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-11T16:58:48.518685525+02:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class JourneysGet2XXResponse {
    public static final String JSON_PROPERTY_JOURNEYS = "journeys";
    public static final String JSON_PROPERTY_REALTIME_DATA_UPDATED_AT = "realtimeDataUpdatedAt";
    public static final String JSON_PROPERTY_EARLIER_REF = "earlierRef";
    public static final String JSON_PROPERTY_LATER_REF = "laterRef";
    @jakarta.annotation.Nonnull
    private List<Journey> journeys = new ArrayList<>();
    @jakarta.annotation.Nullable
    private Integer realtimeDataUpdatedAt;
    @jakarta.annotation.Nullable
    private String earlierRef;
    @jakarta.annotation.Nullable
    private String laterRef;

    public JourneysGet2XXResponse() {
    }

    public JourneysGet2XXResponse journeys(@jakarta.annotation.Nonnull List<Journey> journeys) {

        this.journeys = journeys;
        return this;
    }

    public JourneysGet2XXResponse addJourneysItem(Journey journeysItem) {
        if (this.journeys == null) {
            this.journeys = new ArrayList<>();
        }
        this.journeys.add(journeysItem);
        return this;
    }

    /**
     * Get journeys
     *
     * @return journeys
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_JOURNEYS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public List<Journey> getJourneys() {
        return journeys;
    }


    @JsonProperty(JSON_PROPERTY_JOURNEYS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setJourneys(@jakarta.annotation.Nonnull List<Journey> journeys) {
        this.journeys = journeys;
    }

    public JourneysGet2XXResponse realtimeDataUpdatedAt(@jakarta.annotation.Nullable Integer realtimeDataUpdatedAt) {

        this.realtimeDataUpdatedAt = realtimeDataUpdatedAt;
        return this;
    }

    /**
     * Get realtimeDataUpdatedAt
     *
     * @return realtimeDataUpdatedAt
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_REALTIME_DATA_UPDATED_AT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getRealtimeDataUpdatedAt() {
        return realtimeDataUpdatedAt;
    }


    @JsonProperty(JSON_PROPERTY_REALTIME_DATA_UPDATED_AT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRealtimeDataUpdatedAt(@jakarta.annotation.Nullable Integer realtimeDataUpdatedAt) {
        this.realtimeDataUpdatedAt = realtimeDataUpdatedAt;
    }

    public JourneysGet2XXResponse earlierRef(@jakarta.annotation.Nullable String earlierRef) {

        this.earlierRef = earlierRef;
        return this;
    }

    /**
     * Get earlierRef
     *
     * @return earlierRef
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_EARLIER_REF)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getEarlierRef() {
        return earlierRef;
    }


    @JsonProperty(JSON_PROPERTY_EARLIER_REF)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEarlierRef(@jakarta.annotation.Nullable String earlierRef) {
        this.earlierRef = earlierRef;
    }

    public JourneysGet2XXResponse laterRef(@jakarta.annotation.Nullable String laterRef) {

        this.laterRef = laterRef;
        return this;
    }

    /**
     * Get laterRef
     *
     * @return laterRef
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LATER_REF)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getLaterRef() {
        return laterRef;
    }


    @JsonProperty(JSON_PROPERTY_LATER_REF)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLaterRef(@jakarta.annotation.Nullable String laterRef) {
        this.laterRef = laterRef;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        JourneysGet2XXResponse journeysGet2XXResponse = (JourneysGet2XXResponse) o;
        return Objects.equals(this.journeys, journeysGet2XXResponse.journeys) &&
                Objects.equals(this.realtimeDataUpdatedAt, journeysGet2XXResponse.realtimeDataUpdatedAt) &&
                Objects.equals(this.earlierRef, journeysGet2XXResponse.earlierRef) &&
                Objects.equals(this.laterRef, journeysGet2XXResponse.laterRef);
    }

    @Override
    public int hashCode() {
        return Objects.hash(journeys, realtimeDataUpdatedAt, earlierRef, laterRef);
    }

    @Override
    public String toString() {
        String sb = "class JourneysGet2XXResponse {\n" +
                "    journeys: " + toIndentedString(journeys) + "\n" +
                "    realtimeDataUpdatedAt: " + toIndentedString(realtimeDataUpdatedAt) + "\n" +
                "    earlierRef: " + toIndentedString(earlierRef) + "\n" +
                "    laterRef: " + toIndentedString(laterRef) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

