/*
 * db-vendo-client
 * Schema for db-vendo-client/hafas-rest-api's Friendly Public Transport Format REST API
 *
 * The version of the OpenAPI document: 6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.olech2412.dbvendoclient.model;

import com.fasterxml.jackson.annotation.*;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * A location object is used by other items to indicate their locations.
 */
@JsonPropertyOrder({
        Location.JSON_PROPERTY_TYPE,
        Location.JSON_PROPERTY_ID,
        Location.JSON_PROPERTY_NAME,
        Location.JSON_PROPERTY_POI,
        Location.JSON_PROPERTY_ADDRESS,
        Location.JSON_PROPERTY_LONGITUDE,
        Location.JSON_PROPERTY_LATITUDE,
        Location.JSON_PROPERTY_ALTITUDE,
        Location.JSON_PROPERTY_DISTANCE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-11T16:58:48.518685525+02:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class Location {
    public static final String JSON_PROPERTY_TYPE = "type";
    public static final String JSON_PROPERTY_ID = "id";
    public static final String JSON_PROPERTY_NAME = "name";
    public static final String JSON_PROPERTY_POI = "poi";
    public static final String JSON_PROPERTY_ADDRESS = "address";
    public static final String JSON_PROPERTY_LONGITUDE = "longitude";
    public static final String JSON_PROPERTY_LATITUDE = "latitude";
    public static final String JSON_PROPERTY_ALTITUDE = "altitude";
    public static final String JSON_PROPERTY_DISTANCE = "distance";
    @jakarta.annotation.Nullable
    private TypeEnum type;
    @jakarta.annotation.Nullable
    private String id;
    @jakarta.annotation.Nullable
    private String name;
    @jakarta.annotation.Nullable
    private Boolean poi;
    @jakarta.annotation.Nullable
    private String address;
    @jakarta.annotation.Nullable
    private BigDecimal longitude;
    @jakarta.annotation.Nullable
    private BigDecimal latitude;
    @jakarta.annotation.Nullable
    private BigDecimal altitude;
    @jakarta.annotation.Nullable
    private BigDecimal distance;
    public Location() {
    }

    public Location type(@jakarta.annotation.Nullable TypeEnum type) {

        this.type = type;
        return this;
    }

    /**
     * Get type
     *
     * @return type
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public TypeEnum getType() {
        return type;
    }

    @JsonProperty(JSON_PROPERTY_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setType(@jakarta.annotation.Nullable TypeEnum type) {
        this.type = type;
    }

    public Location id(@jakarta.annotation.Nullable String id) {

        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getId() {
        return id;
    }

    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setId(@jakarta.annotation.Nullable String id) {
        this.id = id;
    }

    public Location name(@jakarta.annotation.Nullable String name) {

        this.name = name;
        return this;
    }

    /**
     * Get name
     *
     * @return name
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getName() {
        return name;
    }

    @JsonProperty(JSON_PROPERTY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setName(@jakarta.annotation.Nullable String name) {
        this.name = name;
    }

    public Location poi(@jakarta.annotation.Nullable Boolean poi) {

        this.poi = poi;
        return this;
    }

    /**
     * Get poi
     *
     * @return poi
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_POI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getPoi() {
        return poi;
    }

    @JsonProperty(JSON_PROPERTY_POI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPoi(@jakarta.annotation.Nullable Boolean poi) {
        this.poi = poi;
    }

    public Location address(@jakarta.annotation.Nullable String address) {

        this.address = address;
        return this;
    }

    /**
     * Get address
     *
     * @return address
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ADDRESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getAddress() {
        return address;
    }

    @JsonProperty(JSON_PROPERTY_ADDRESS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAddress(@jakarta.annotation.Nullable String address) {
        this.address = address;
    }

    public Location longitude(@jakarta.annotation.Nullable BigDecimal longitude) {

        this.longitude = longitude;
        return this;
    }

    /**
     * Get longitude
     *
     * @return longitude
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LONGITUDE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getLongitude() {
        return longitude;
    }

    @JsonProperty(JSON_PROPERTY_LONGITUDE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLongitude(@jakarta.annotation.Nullable BigDecimal longitude) {
        this.longitude = longitude;
    }

    public Location latitude(@jakarta.annotation.Nullable BigDecimal latitude) {

        this.latitude = latitude;
        return this;
    }

    /**
     * Get latitude
     *
     * @return latitude
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LATITUDE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getLatitude() {
        return latitude;
    }

    @JsonProperty(JSON_PROPERTY_LATITUDE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLatitude(@jakarta.annotation.Nullable BigDecimal latitude) {
        this.latitude = latitude;
    }

    public Location altitude(@jakarta.annotation.Nullable BigDecimal altitude) {

        this.altitude = altitude;
        return this;
    }

    /**
     * Get altitude
     *
     * @return altitude
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ALTITUDE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getAltitude() {
        return altitude;
    }

    @JsonProperty(JSON_PROPERTY_ALTITUDE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAltitude(@jakarta.annotation.Nullable BigDecimal altitude) {
        this.altitude = altitude;
    }

    public Location distance(@jakarta.annotation.Nullable BigDecimal distance) {

        this.distance = distance;
        return this;
    }

    /**
     * Get distance
     *
     * @return distance
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DISTANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getDistance() {
        return distance;
    }

    @JsonProperty(JSON_PROPERTY_DISTANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDistance(@jakarta.annotation.Nullable BigDecimal distance) {
        this.distance = distance;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Location location = (Location) o;
        return Objects.equals(this.type, location.type) &&
                Objects.equals(this.id, location.id) &&
                Objects.equals(this.name, location.name) &&
                Objects.equals(this.poi, location.poi) &&
                Objects.equals(this.address, location.address) &&
                Objects.equals(this.longitude, location.longitude) &&
                Objects.equals(this.latitude, location.latitude) &&
                Objects.equals(this.altitude, location.altitude) &&
                Objects.equals(this.distance, location.distance);
    }

    @Override
    public int hashCode() {
        return Objects.hash(type, id, name, poi, address, longitude, latitude, altitude, distance);
    }

    @Override
    public String toString() {
        String sb = "class Location {\n" +
                "    type: " + toIndentedString(type) + "\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    poi: " + toIndentedString(poi) + "\n" +
                "    address: " + toIndentedString(address) + "\n" +
                "    longitude: " + toIndentedString(longitude) + "\n" +
                "    latitude: " + toIndentedString(latitude) + "\n" +
                "    altitude: " + toIndentedString(altitude) + "\n" +
                "    distance: " + toIndentedString(distance) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

    /**
     * Gets or Sets type
     */
    public enum TypeEnum {
        LOCATION("location");

        private final String value;

        TypeEnum(String value) {
            this.value = value;
        }

        @JsonCreator
        public static TypeEnum fromValue(String value) {
            for (TypeEnum b : TypeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }

        @JsonValue
        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return String.valueOf(value);
        }
    }

}

