/*
 * db-vendo-client
 * Schema for db-vendo-client/hafas-rest-api's Friendly Public Transport Format REST API
 *
 * The version of the OpenAPI document: 6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.olech2412.dbvendoclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * A profile is a specific customisation for each endpoint. It parses data from the API differently, add additional information, or enable non-default methods.
 */
@JsonPropertyOrder({
        Profile.JSON_PROPERTY_LOCALE,
        Profile.JSON_PROPERTY_TIMEZONE,
        Profile.JSON_PROPERTY_ENDPOINT,
        Profile.JSON_PROPERTY_PRODUCTS,
        Profile.JSON_PROPERTY_TRIP,
        Profile.JSON_PROPERTY_RADAR,
        Profile.JSON_PROPERTY_REFRESH_JOURNEY,
        Profile.JSON_PROPERTY_JOURNEYS_FROM_TRIP,
        Profile.JSON_PROPERTY_REACHABLE_FROM,
        Profile.JSON_PROPERTY_JOURNEYS_WALKING_SPEED,
        Profile.JSON_PROPERTY_TRIPS_BY_NAME,
        Profile.JSON_PROPERTY_REMARKS,
        Profile.JSON_PROPERTY_REMARKS_GET_POLYLINE,
        Profile.JSON_PROPERTY_LINES
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-11T16:58:48.518685525+02:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class Profile {
    public static final String JSON_PROPERTY_LOCALE = "locale";
    public static final String JSON_PROPERTY_TIMEZONE = "timezone";
    public static final String JSON_PROPERTY_ENDPOINT = "endpoint";
    public static final String JSON_PROPERTY_PRODUCTS = "products";
    public static final String JSON_PROPERTY_TRIP = "trip";
    public static final String JSON_PROPERTY_RADAR = "radar";
    public static final String JSON_PROPERTY_REFRESH_JOURNEY = "refreshJourney";
    public static final String JSON_PROPERTY_JOURNEYS_FROM_TRIP = "journeysFromTrip";
    public static final String JSON_PROPERTY_REACHABLE_FROM = "reachableFrom";
    public static final String JSON_PROPERTY_JOURNEYS_WALKING_SPEED = "journeysWalkingSpeed";
    public static final String JSON_PROPERTY_TRIPS_BY_NAME = "tripsByName";
    public static final String JSON_PROPERTY_REMARKS = "remarks";
    public static final String JSON_PROPERTY_REMARKS_GET_POLYLINE = "remarksGetPolyline";
    public static final String JSON_PROPERTY_LINES = "lines";
    @jakarta.annotation.Nullable
    private String locale;
    @jakarta.annotation.Nullable
    private String timezone;
    @jakarta.annotation.Nullable
    private String endpoint;
    @jakarta.annotation.Nullable
    private List<ProductType> products = new ArrayList<>();
    @jakarta.annotation.Nullable
    private Boolean trip;
    @jakarta.annotation.Nullable
    private Boolean radar;
    @jakarta.annotation.Nullable
    private Boolean refreshJourney;
    @jakarta.annotation.Nullable
    private Boolean journeysFromTrip;
    @jakarta.annotation.Nullable
    private Boolean reachableFrom;
    @jakarta.annotation.Nullable
    private Boolean journeysWalkingSpeed;
    @jakarta.annotation.Nullable
    private Boolean tripsByName;
    @jakarta.annotation.Nullable
    private Boolean remarks;
    @jakarta.annotation.Nullable
    private Boolean remarksGetPolyline;
    @jakarta.annotation.Nullable
    private Boolean lines;

    public Profile() {
    }

    public Profile locale(@jakarta.annotation.Nullable String locale) {

        this.locale = locale;
        return this;
    }

    /**
     * Get locale
     *
     * @return locale
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LOCALE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getLocale() {
        return locale;
    }


    @JsonProperty(JSON_PROPERTY_LOCALE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLocale(@jakarta.annotation.Nullable String locale) {
        this.locale = locale;
    }

    public Profile timezone(@jakarta.annotation.Nullable String timezone) {

        this.timezone = timezone;
        return this;
    }

    /**
     * Get timezone
     *
     * @return timezone
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TIMEZONE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getTimezone() {
        return timezone;
    }


    @JsonProperty(JSON_PROPERTY_TIMEZONE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTimezone(@jakarta.annotation.Nullable String timezone) {
        this.timezone = timezone;
    }

    public Profile endpoint(@jakarta.annotation.Nullable String endpoint) {

        this.endpoint = endpoint;
        return this;
    }

    /**
     * Get endpoint
     *
     * @return endpoint
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ENDPOINT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getEndpoint() {
        return endpoint;
    }


    @JsonProperty(JSON_PROPERTY_ENDPOINT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setEndpoint(@jakarta.annotation.Nullable String endpoint) {
        this.endpoint = endpoint;
    }

    public Profile products(@jakarta.annotation.Nullable List<ProductType> products) {

        this.products = products;
        return this;
    }

    public Profile addProductsItem(ProductType productsItem) {
        if (this.products == null) {
            this.products = new ArrayList<>();
        }
        this.products.add(productsItem);
        return this;
    }

    /**
     * Get products
     *
     * @return products
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PRODUCTS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<ProductType> getProducts() {
        return products;
    }


    @JsonProperty(JSON_PROPERTY_PRODUCTS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setProducts(@jakarta.annotation.Nullable List<ProductType> products) {
        this.products = products;
    }

    public Profile trip(@jakarta.annotation.Nullable Boolean trip) {

        this.trip = trip;
        return this;
    }

    /**
     * Get trip
     *
     * @return trip
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TRIP)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getTrip() {
        return trip;
    }


    @JsonProperty(JSON_PROPERTY_TRIP)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTrip(@jakarta.annotation.Nullable Boolean trip) {
        this.trip = trip;
    }

    public Profile radar(@jakarta.annotation.Nullable Boolean radar) {

        this.radar = radar;
        return this;
    }

    /**
     * Get radar
     *
     * @return radar
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_RADAR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getRadar() {
        return radar;
    }


    @JsonProperty(JSON_PROPERTY_RADAR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRadar(@jakarta.annotation.Nullable Boolean radar) {
        this.radar = radar;
    }

    public Profile refreshJourney(@jakarta.annotation.Nullable Boolean refreshJourney) {

        this.refreshJourney = refreshJourney;
        return this;
    }

    /**
     * Get refreshJourney
     *
     * @return refreshJourney
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_REFRESH_JOURNEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getRefreshJourney() {
        return refreshJourney;
    }


    @JsonProperty(JSON_PROPERTY_REFRESH_JOURNEY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRefreshJourney(@jakarta.annotation.Nullable Boolean refreshJourney) {
        this.refreshJourney = refreshJourney;
    }

    public Profile journeysFromTrip(@jakarta.annotation.Nullable Boolean journeysFromTrip) {

        this.journeysFromTrip = journeysFromTrip;
        return this;
    }

    /**
     * Get journeysFromTrip
     *
     * @return journeysFromTrip
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_JOURNEYS_FROM_TRIP)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getJourneysFromTrip() {
        return journeysFromTrip;
    }


    @JsonProperty(JSON_PROPERTY_JOURNEYS_FROM_TRIP)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setJourneysFromTrip(@jakarta.annotation.Nullable Boolean journeysFromTrip) {
        this.journeysFromTrip = journeysFromTrip;
    }

    public Profile reachableFrom(@jakarta.annotation.Nullable Boolean reachableFrom) {

        this.reachableFrom = reachableFrom;
        return this;
    }

    /**
     * Get reachableFrom
     *
     * @return reachableFrom
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_REACHABLE_FROM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getReachableFrom() {
        return reachableFrom;
    }


    @JsonProperty(JSON_PROPERTY_REACHABLE_FROM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setReachableFrom(@jakarta.annotation.Nullable Boolean reachableFrom) {
        this.reachableFrom = reachableFrom;
    }

    public Profile journeysWalkingSpeed(@jakarta.annotation.Nullable Boolean journeysWalkingSpeed) {

        this.journeysWalkingSpeed = journeysWalkingSpeed;
        return this;
    }

    /**
     * Get journeysWalkingSpeed
     *
     * @return journeysWalkingSpeed
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_JOURNEYS_WALKING_SPEED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getJourneysWalkingSpeed() {
        return journeysWalkingSpeed;
    }


    @JsonProperty(JSON_PROPERTY_JOURNEYS_WALKING_SPEED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setJourneysWalkingSpeed(@jakarta.annotation.Nullable Boolean journeysWalkingSpeed) {
        this.journeysWalkingSpeed = journeysWalkingSpeed;
    }

    public Profile tripsByName(@jakarta.annotation.Nullable Boolean tripsByName) {

        this.tripsByName = tripsByName;
        return this;
    }

    /**
     * Get tripsByName
     *
     * @return tripsByName
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TRIPS_BY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getTripsByName() {
        return tripsByName;
    }


    @JsonProperty(JSON_PROPERTY_TRIPS_BY_NAME)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTripsByName(@jakarta.annotation.Nullable Boolean tripsByName) {
        this.tripsByName = tripsByName;
    }

    public Profile remarks(@jakarta.annotation.Nullable Boolean remarks) {

        this.remarks = remarks;
        return this;
    }

    /**
     * Get remarks
     *
     * @return remarks
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_REMARKS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getRemarks() {
        return remarks;
    }


    @JsonProperty(JSON_PROPERTY_REMARKS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRemarks(@jakarta.annotation.Nullable Boolean remarks) {
        this.remarks = remarks;
    }

    public Profile remarksGetPolyline(@jakarta.annotation.Nullable Boolean remarksGetPolyline) {

        this.remarksGetPolyline = remarksGetPolyline;
        return this;
    }

    /**
     * Get remarksGetPolyline
     *
     * @return remarksGetPolyline
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_REMARKS_GET_POLYLINE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getRemarksGetPolyline() {
        return remarksGetPolyline;
    }


    @JsonProperty(JSON_PROPERTY_REMARKS_GET_POLYLINE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRemarksGetPolyline(@jakarta.annotation.Nullable Boolean remarksGetPolyline) {
        this.remarksGetPolyline = remarksGetPolyline;
    }

    public Profile lines(@jakarta.annotation.Nullable Boolean lines) {

        this.lines = lines;
        return this;
    }

    /**
     * Get lines
     *
     * @return lines
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LINES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getLines() {
        return lines;
    }


    @JsonProperty(JSON_PROPERTY_LINES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLines(@jakarta.annotation.Nullable Boolean lines) {
        this.lines = lines;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Profile profile = (Profile) o;
        return Objects.equals(this.locale, profile.locale) &&
                Objects.equals(this.timezone, profile.timezone) &&
                Objects.equals(this.endpoint, profile.endpoint) &&
                Objects.equals(this.products, profile.products) &&
                Objects.equals(this.trip, profile.trip) &&
                Objects.equals(this.radar, profile.radar) &&
                Objects.equals(this.refreshJourney, profile.refreshJourney) &&
                Objects.equals(this.journeysFromTrip, profile.journeysFromTrip) &&
                Objects.equals(this.reachableFrom, profile.reachableFrom) &&
                Objects.equals(this.journeysWalkingSpeed, profile.journeysWalkingSpeed) &&
                Objects.equals(this.tripsByName, profile.tripsByName) &&
                Objects.equals(this.remarks, profile.remarks) &&
                Objects.equals(this.remarksGetPolyline, profile.remarksGetPolyline) &&
                Objects.equals(this.lines, profile.lines);
    }

    @Override
    public int hashCode() {
        return Objects.hash(locale, timezone, endpoint, products, trip, radar, refreshJourney, journeysFromTrip, reachableFrom, journeysWalkingSpeed, tripsByName, remarks, remarksGetPolyline, lines);
    }

    @Override
    public String toString() {
        String sb = "class Profile {\n" +
                "    locale: " + toIndentedString(locale) + "\n" +
                "    timezone: " + toIndentedString(timezone) + "\n" +
                "    endpoint: " + toIndentedString(endpoint) + "\n" +
                "    products: " + toIndentedString(products) + "\n" +
                "    trip: " + toIndentedString(trip) + "\n" +
                "    radar: " + toIndentedString(radar) + "\n" +
                "    refreshJourney: " + toIndentedString(refreshJourney) + "\n" +
                "    journeysFromTrip: " + toIndentedString(journeysFromTrip) + "\n" +
                "    reachableFrom: " + toIndentedString(reachableFrom) + "\n" +
                "    journeysWalkingSpeed: " + toIndentedString(journeysWalkingSpeed) + "\n" +
                "    tripsByName: " + toIndentedString(tripsByName) + "\n" +
                "    remarks: " + toIndentedString(remarks) + "\n" +
                "    remarksGetPolyline: " + toIndentedString(remarksGetPolyline) + "\n" +
                "    lines: " + toIndentedString(lines) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

