/*
 * db-vendo-client
 * Schema for db-vendo-client/hafas-rest-api's Friendly Public Transport Format REST API
 *
 * The version of the OpenAPI document: 6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.olech2412.dbvendoclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.util.Objects;

/**
 * ReisezentrumOpeningHours
 */
@JsonPropertyOrder({
        ReisezentrumOpeningHours.JSON_PROPERTY_MO,
        ReisezentrumOpeningHours.JSON_PROPERTY_DI,
        ReisezentrumOpeningHours.JSON_PROPERTY_MI,
        ReisezentrumOpeningHours.JSON_PROPERTY_DO,
        ReisezentrumOpeningHours.JSON_PROPERTY_FR,
        ReisezentrumOpeningHours.JSON_PROPERTY_SA,
        ReisezentrumOpeningHours.JSON_PROPERTY_SO
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-11T16:58:48.518685525+02:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class ReisezentrumOpeningHours {
    public static final String JSON_PROPERTY_MO = "Mo";
    public static final String JSON_PROPERTY_DI = "Di";
    public static final String JSON_PROPERTY_MI = "Mi";
    public static final String JSON_PROPERTY_DO = "Do";
    public static final String JSON_PROPERTY_FR = "Fr";
    public static final String JSON_PROPERTY_SA = "Sa";
    public static final String JSON_PROPERTY_SO = "So";
    @jakarta.annotation.Nullable
    private String mo;
    @jakarta.annotation.Nullable
    private String di;
    @jakarta.annotation.Nullable
    private String mi;
    @jakarta.annotation.Nullable
    private String _do;
    @jakarta.annotation.Nullable
    private String fr;
    @jakarta.annotation.Nullable
    private String sa;
    @jakarta.annotation.Nullable
    private String so;

    public ReisezentrumOpeningHours() {
    }

    public ReisezentrumOpeningHours mo(@jakarta.annotation.Nullable String mo) {

        this.mo = mo;
        return this;
    }

    /**
     * Get mo
     *
     * @return mo
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getMo() {
        return mo;
    }


    @JsonProperty(JSON_PROPERTY_MO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMo(@jakarta.annotation.Nullable String mo) {
        this.mo = mo;
    }

    public ReisezentrumOpeningHours di(@jakarta.annotation.Nullable String di) {

        this.di = di;
        return this;
    }

    /**
     * Get di
     *
     * @return di
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDi() {
        return di;
    }


    @JsonProperty(JSON_PROPERTY_DI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDi(@jakarta.annotation.Nullable String di) {
        this.di = di;
    }

    public ReisezentrumOpeningHours mi(@jakarta.annotation.Nullable String mi) {

        this.mi = mi;
        return this;
    }

    /**
     * Get mi
     *
     * @return mi
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_MI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getMi() {
        return mi;
    }


    @JsonProperty(JSON_PROPERTY_MI)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setMi(@jakarta.annotation.Nullable String mi) {
        this.mi = mi;
    }

    public ReisezentrumOpeningHours _do(@jakarta.annotation.Nullable String _do) {

        this._do = _do;
        return this;
    }

    /**
     * Get _do
     *
     * @return _do
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDo() {
        return _do;
    }


    @JsonProperty(JSON_PROPERTY_DO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDo(@jakarta.annotation.Nullable String _do) {
        this._do = _do;
    }

    public ReisezentrumOpeningHours fr(@jakarta.annotation.Nullable String fr) {

        this.fr = fr;
        return this;
    }

    /**
     * Get fr
     *
     * @return fr
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_FR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getFr() {
        return fr;
    }


    @JsonProperty(JSON_PROPERTY_FR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setFr(@jakarta.annotation.Nullable String fr) {
        this.fr = fr;
    }

    public ReisezentrumOpeningHours sa(@jakarta.annotation.Nullable String sa) {

        this.sa = sa;
        return this;
    }

    /**
     * Get sa
     *
     * @return sa
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SA)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getSa() {
        return sa;
    }


    @JsonProperty(JSON_PROPERTY_SA)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSa(@jakarta.annotation.Nullable String sa) {
        this.sa = sa;
    }

    public ReisezentrumOpeningHours so(@jakarta.annotation.Nullable String so) {

        this.so = so;
        return this;
    }

    /**
     * Get so
     *
     * @return so
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getSo() {
        return so;
    }


    @JsonProperty(JSON_PROPERTY_SO)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSo(@jakarta.annotation.Nullable String so) {
        this.so = so;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        ReisezentrumOpeningHours reisezentrumOpeningHours = (ReisezentrumOpeningHours) o;
        return Objects.equals(this.mo, reisezentrumOpeningHours.mo) &&
                Objects.equals(this.di, reisezentrumOpeningHours.di) &&
                Objects.equals(this.mi, reisezentrumOpeningHours.mi) &&
                Objects.equals(this._do, reisezentrumOpeningHours._do) &&
                Objects.equals(this.fr, reisezentrumOpeningHours.fr) &&
                Objects.equals(this.sa, reisezentrumOpeningHours.sa) &&
                Objects.equals(this.so, reisezentrumOpeningHours.so);
    }

    @Override
    public int hashCode() {
        return Objects.hash(mo, di, mi, _do, fr, sa, so);
    }

    @Override
    public String toString() {
        String sb = "class ReisezentrumOpeningHours {\n" +
                "    mo: " + toIndentedString(mo) + "\n" +
                "    di: " + toIndentedString(di) + "\n" +
                "    mi: " + toIndentedString(mi) + "\n" +
                "    _do: " + toIndentedString(_do) + "\n" +
                "    fr: " + toIndentedString(fr) + "\n" +
                "    sa: " + toIndentedString(sa) + "\n" +
                "    so: " + toIndentedString(so) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

