/*
 * db-vendo-client
 * Schema for db-vendo-client/hafas-rest-api's Friendly Public Transport Format REST API
 *
 * The version of the OpenAPI document: 6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.olech2412.dbvendoclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * StopsIdArrivalsGet2XXResponse
 */
@JsonPropertyOrder({
        StopsIdArrivalsGet2XXResponse.JSON_PROPERTY_ARRIVALS,
        StopsIdArrivalsGet2XXResponse.JSON_PROPERTY_REALTIME_DATA_UPDATED_AT
})
@JsonTypeName("_stops__id__arrivals_get_2XX_response")
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-11T16:58:48.518685525+02:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class StopsIdArrivalsGet2XXResponse {
    public static final String JSON_PROPERTY_ARRIVALS = "arrivals";
    public static final String JSON_PROPERTY_REALTIME_DATA_UPDATED_AT = "realtimeDataUpdatedAt";
    @jakarta.annotation.Nonnull
    private List<Alternative> arrivals = new ArrayList<>();
    @jakarta.annotation.Nullable
    private Integer realtimeDataUpdatedAt;

    public StopsIdArrivalsGet2XXResponse() {
    }

    public StopsIdArrivalsGet2XXResponse arrivals(@jakarta.annotation.Nonnull List<Alternative> arrivals) {

        this.arrivals = arrivals;
        return this;
    }

    public StopsIdArrivalsGet2XXResponse addArrivalsItem(Alternative arrivalsItem) {
        if (this.arrivals == null) {
            this.arrivals = new ArrayList<>();
        }
        this.arrivals.add(arrivalsItem);
        return this;
    }

    /**
     * Get arrivals
     *
     * @return arrivals
     */
    @jakarta.annotation.Nonnull
    @JsonProperty(JSON_PROPERTY_ARRIVALS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)

    public List<Alternative> getArrivals() {
        return arrivals;
    }


    @JsonProperty(JSON_PROPERTY_ARRIVALS)
    @JsonInclude(value = JsonInclude.Include.ALWAYS)
    public void setArrivals(@jakarta.annotation.Nonnull List<Alternative> arrivals) {
        this.arrivals = arrivals;
    }

    public StopsIdArrivalsGet2XXResponse realtimeDataUpdatedAt(@jakarta.annotation.Nullable Integer realtimeDataUpdatedAt) {

        this.realtimeDataUpdatedAt = realtimeDataUpdatedAt;
        return this;
    }

    /**
     * Get realtimeDataUpdatedAt
     *
     * @return realtimeDataUpdatedAt
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_REALTIME_DATA_UPDATED_AT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Integer getRealtimeDataUpdatedAt() {
        return realtimeDataUpdatedAt;
    }


    @JsonProperty(JSON_PROPERTY_REALTIME_DATA_UPDATED_AT)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRealtimeDataUpdatedAt(@jakarta.annotation.Nullable Integer realtimeDataUpdatedAt) {
        this.realtimeDataUpdatedAt = realtimeDataUpdatedAt;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        StopsIdArrivalsGet2XXResponse stopsIdArrivalsGet2XXResponse = (StopsIdArrivalsGet2XXResponse) o;
        return Objects.equals(this.arrivals, stopsIdArrivalsGet2XXResponse.arrivals) &&
                Objects.equals(this.realtimeDataUpdatedAt, stopsIdArrivalsGet2XXResponse.realtimeDataUpdatedAt);
    }

    @Override
    public int hashCode() {
        return Objects.hash(arrivals, realtimeDataUpdatedAt);
    }

    @Override
    public String toString() {
        String sb = "class StopsIdArrivalsGet2XXResponse {\n" +
                "    arrivals: " + toIndentedString(arrivals) + "\n" +
                "    realtimeDataUpdatedAt: " + toIndentedString(realtimeDataUpdatedAt) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

