/*
 * db-vendo-client
 * Schema for db-vendo-client/hafas-rest-api's Friendly Public Transport Format REST API
 *
 * The version of the OpenAPI document: 6
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.olech2412.dbvendoclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.math.BigDecimal;
import java.util.*;

/**
 * Trip – a vehicle stopping at a set of stops at specific times
 */
@JsonPropertyOrder({
        Trip.JSON_PROPERTY_ID,
        Trip.JSON_PROPERTY_ORIGIN,
        Trip.JSON_PROPERTY_DESTINATION,
        Trip.JSON_PROPERTY_DEPARTURE,
        Trip.JSON_PROPERTY_PLANNED_DEPARTURE,
        Trip.JSON_PROPERTY_PROGNOSED_ARRIVAL,
        Trip.JSON_PROPERTY_DEPARTURE_DELAY,
        Trip.JSON_PROPERTY_DEPARTURE_PLATFORM,
        Trip.JSON_PROPERTY_PROGNOSED_DEPARTURE_PLATFORM,
        Trip.JSON_PROPERTY_PLANNED_DEPARTURE_PLATFORM,
        Trip.JSON_PROPERTY_ARRIVAL,
        Trip.JSON_PROPERTY_PLANNED_ARRIVAL,
        Trip.JSON_PROPERTY_PROGNOSED_DEPARTURE,
        Trip.JSON_PROPERTY_ARRIVAL_DELAY,
        Trip.JSON_PROPERTY_ARRIVAL_PLATFORM,
        Trip.JSON_PROPERTY_PROGNOSED_ARRIVAL_PLATFORM,
        Trip.JSON_PROPERTY_PLANNED_ARRIVAL_PLATFORM,
        Trip.JSON_PROPERTY_STOPOVERS,
        Trip.JSON_PROPERTY_SCHEDULE,
        Trip.JSON_PROPERTY_PRICE,
        Trip.JSON_PROPERTY_OPERATOR,
        Trip.JSON_PROPERTY_DIRECTION,
        Trip.JSON_PROPERTY_LINE,
        Trip.JSON_PROPERTY_CANCELLED,
        Trip.JSON_PROPERTY_WALKING,
        Trip.JSON_PROPERTY_LOAD_FACTOR,
        Trip.JSON_PROPERTY_DISTANCE,
        Trip.JSON_PROPERTY_PUBLIC,
        Trip.JSON_PROPERTY_TRANSFER,
        Trip.JSON_PROPERTY_CYCLE,
        Trip.JSON_PROPERTY_ALTERNATIVES,
        Trip.JSON_PROPERTY_POLYLINE,
        Trip.JSON_PROPERTY_REMARKS,
        Trip.JSON_PROPERTY_CURRENT_LOCATION,
        Trip.JSON_PROPERTY_DEPARTURE_PROGNOSIS_TYPE,
        Trip.JSON_PROPERTY_ARRIVAL_PROGNOSIS_TYPE,
        Trip.JSON_PROPERTY_CHECKIN,
        Trip.JSON_PROPERTY_SCHEDULED_DAYS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-04-11T16:58:48.518685525+02:00[Europe/Berlin]", comments = "Generator version: 7.12.0")
public class Trip {
    public static final String JSON_PROPERTY_ID = "id";
    public static final String JSON_PROPERTY_ORIGIN = "origin";
    public static final String JSON_PROPERTY_DESTINATION = "destination";
    public static final String JSON_PROPERTY_DEPARTURE = "departure";
    public static final String JSON_PROPERTY_PLANNED_DEPARTURE = "plannedDeparture";
    public static final String JSON_PROPERTY_PROGNOSED_ARRIVAL = "prognosedArrival";
    public static final String JSON_PROPERTY_DEPARTURE_DELAY = "departureDelay";
    public static final String JSON_PROPERTY_DEPARTURE_PLATFORM = "departurePlatform";
    public static final String JSON_PROPERTY_PROGNOSED_DEPARTURE_PLATFORM = "prognosedDeparturePlatform";
    public static final String JSON_PROPERTY_PLANNED_DEPARTURE_PLATFORM = "plannedDeparturePlatform";
    public static final String JSON_PROPERTY_ARRIVAL = "arrival";
    public static final String JSON_PROPERTY_PLANNED_ARRIVAL = "plannedArrival";
    public static final String JSON_PROPERTY_PROGNOSED_DEPARTURE = "prognosedDeparture";
    public static final String JSON_PROPERTY_ARRIVAL_DELAY = "arrivalDelay";
    public static final String JSON_PROPERTY_ARRIVAL_PLATFORM = "arrivalPlatform";
    public static final String JSON_PROPERTY_PROGNOSED_ARRIVAL_PLATFORM = "prognosedArrivalPlatform";
    public static final String JSON_PROPERTY_PLANNED_ARRIVAL_PLATFORM = "plannedArrivalPlatform";
    public static final String JSON_PROPERTY_STOPOVERS = "stopovers";
    public static final String JSON_PROPERTY_SCHEDULE = "schedule";
    public static final String JSON_PROPERTY_PRICE = "price";
    public static final String JSON_PROPERTY_OPERATOR = "operator";
    public static final String JSON_PROPERTY_DIRECTION = "direction";
    public static final String JSON_PROPERTY_LINE = "line";
    public static final String JSON_PROPERTY_CANCELLED = "cancelled";
    public static final String JSON_PROPERTY_WALKING = "walking";
    public static final String JSON_PROPERTY_LOAD_FACTOR = "loadFactor";
    public static final String JSON_PROPERTY_DISTANCE = "distance";
    public static final String JSON_PROPERTY_PUBLIC = "public";
    public static final String JSON_PROPERTY_TRANSFER = "transfer";
    public static final String JSON_PROPERTY_CYCLE = "cycle";
    public static final String JSON_PROPERTY_ALTERNATIVES = "alternatives";
    public static final String JSON_PROPERTY_POLYLINE = "polyline";
    public static final String JSON_PROPERTY_REMARKS = "remarks";
    public static final String JSON_PROPERTY_CURRENT_LOCATION = "currentLocation";
    public static final String JSON_PROPERTY_DEPARTURE_PROGNOSIS_TYPE = "departurePrognosisType";
    public static final String JSON_PROPERTY_ARRIVAL_PROGNOSIS_TYPE = "arrivalPrognosisType";
    public static final String JSON_PROPERTY_CHECKIN = "checkin";
    public static final String JSON_PROPERTY_SCHEDULED_DAYS = "scheduledDays";
    @jakarta.annotation.Nullable
    private String id;
    @jakarta.annotation.Nullable
    private StopsIdGet2XXResponse origin;
    @jakarta.annotation.Nullable
    private StopsIdGet2XXResponse destination;
    @jakarta.annotation.Nullable
    private String departure;
    @jakarta.annotation.Nullable
    private String plannedDeparture;
    @jakarta.annotation.Nullable
    private String prognosedArrival;
    @jakarta.annotation.Nullable
    private BigDecimal departureDelay;
    @jakarta.annotation.Nullable
    private String departurePlatform;
    @jakarta.annotation.Nullable
    private String prognosedDeparturePlatform;
    @jakarta.annotation.Nullable
    private String plannedDeparturePlatform;
    @jakarta.annotation.Nullable
    private String arrival;
    @jakarta.annotation.Nullable
    private String plannedArrival;
    @jakarta.annotation.Nullable
    private String prognosedDeparture;
    @jakarta.annotation.Nullable
    private BigDecimal arrivalDelay;
    @jakarta.annotation.Nullable
    private String arrivalPlatform;
    @jakarta.annotation.Nullable
    private String prognosedArrivalPlatform;
    @jakarta.annotation.Nullable
    private String plannedArrivalPlatform;
    @jakarta.annotation.Nullable
    private List<StopOver> stopovers = new ArrayList<>();
    @jakarta.annotation.Nullable
    private BigDecimal schedule;
    @jakarta.annotation.Nullable
    private Price price;
    @jakarta.annotation.Nullable
    private BigDecimal operator;
    @jakarta.annotation.Nullable
    private String direction;
    @jakarta.annotation.Nullable
    private Line line;
    @jakarta.annotation.Nullable
    private Boolean cancelled;
    @jakarta.annotation.Nullable
    private Boolean walking;
    @jakarta.annotation.Nullable
    private String loadFactor;
    @jakarta.annotation.Nullable
    private BigDecimal distance;
    @jakarta.annotation.Nullable
    private Boolean _public;
    @jakarta.annotation.Nullable
    private Boolean transfer;
    @jakarta.annotation.Nullable
    private Cycle cycle;
    @jakarta.annotation.Nullable
    private List<Alternative> alternatives = new ArrayList<>();
    @jakarta.annotation.Nullable
    private FeatureCollection polyline;
    @jakarta.annotation.Nullable
    private List<StopOverRemarksInner> remarks = new ArrayList<>();
    @jakarta.annotation.Nullable
    private Location currentLocation;
    @jakarta.annotation.Nullable
    private PrognosisType departurePrognosisType;
    @jakarta.annotation.Nullable
    private PrognosisType arrivalPrognosisType;
    @jakarta.annotation.Nullable
    private Boolean checkin;
    @jakarta.annotation.Nullable
    private Map<String, Boolean> scheduledDays = new HashMap<>();

    public Trip() {
    }

    public Trip id(@jakarta.annotation.Nullable String id) {

        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getId() {
        return id;
    }


    @JsonProperty(JSON_PROPERTY_ID)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setId(@jakarta.annotation.Nullable String id) {
        this.id = id;
    }

    public Trip origin(@jakarta.annotation.Nullable StopsIdGet2XXResponse origin) {

        this.origin = origin;
        return this;
    }

    /**
     * Get origin
     *
     * @return origin
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ORIGIN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public StopsIdGet2XXResponse getOrigin() {
        return origin;
    }


    @JsonProperty(JSON_PROPERTY_ORIGIN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setOrigin(@jakarta.annotation.Nullable StopsIdGet2XXResponse origin) {
        this.origin = origin;
    }

    public Trip destination(@jakarta.annotation.Nullable StopsIdGet2XXResponse destination) {

        this.destination = destination;
        return this;
    }

    /**
     * Get destination
     *
     * @return destination
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DESTINATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public StopsIdGet2XXResponse getDestination() {
        return destination;
    }


    @JsonProperty(JSON_PROPERTY_DESTINATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDestination(@jakarta.annotation.Nullable StopsIdGet2XXResponse destination) {
        this.destination = destination;
    }

    public Trip departure(@jakarta.annotation.Nullable String departure) {

        this.departure = departure;
        return this;
    }

    /**
     * Get departure
     *
     * @return departure
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DEPARTURE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDeparture() {
        return departure;
    }


    @JsonProperty(JSON_PROPERTY_DEPARTURE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDeparture(@jakarta.annotation.Nullable String departure) {
        this.departure = departure;
    }

    public Trip plannedDeparture(@jakarta.annotation.Nullable String plannedDeparture) {

        this.plannedDeparture = plannedDeparture;
        return this;
    }

    /**
     * Get plannedDeparture
     *
     * @return plannedDeparture
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PLANNED_DEPARTURE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPlannedDeparture() {
        return plannedDeparture;
    }


    @JsonProperty(JSON_PROPERTY_PLANNED_DEPARTURE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPlannedDeparture(@jakarta.annotation.Nullable String plannedDeparture) {
        this.plannedDeparture = plannedDeparture;
    }

    public Trip prognosedArrival(@jakarta.annotation.Nullable String prognosedArrival) {

        this.prognosedArrival = prognosedArrival;
        return this;
    }

    /**
     * Get prognosedArrival
     *
     * @return prognosedArrival
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PROGNOSED_ARRIVAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPrognosedArrival() {
        return prognosedArrival;
    }


    @JsonProperty(JSON_PROPERTY_PROGNOSED_ARRIVAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPrognosedArrival(@jakarta.annotation.Nullable String prognosedArrival) {
        this.prognosedArrival = prognosedArrival;
    }

    public Trip departureDelay(@jakarta.annotation.Nullable BigDecimal departureDelay) {

        this.departureDelay = departureDelay;
        return this;
    }

    /**
     * Get departureDelay
     *
     * @return departureDelay
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DEPARTURE_DELAY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getDepartureDelay() {
        return departureDelay;
    }


    @JsonProperty(JSON_PROPERTY_DEPARTURE_DELAY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDepartureDelay(@jakarta.annotation.Nullable BigDecimal departureDelay) {
        this.departureDelay = departureDelay;
    }

    public Trip departurePlatform(@jakarta.annotation.Nullable String departurePlatform) {

        this.departurePlatform = departurePlatform;
        return this;
    }

    /**
     * Get departurePlatform
     *
     * @return departurePlatform
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DEPARTURE_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDeparturePlatform() {
        return departurePlatform;
    }


    @JsonProperty(JSON_PROPERTY_DEPARTURE_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDeparturePlatform(@jakarta.annotation.Nullable String departurePlatform) {
        this.departurePlatform = departurePlatform;
    }

    public Trip prognosedDeparturePlatform(@jakarta.annotation.Nullable String prognosedDeparturePlatform) {

        this.prognosedDeparturePlatform = prognosedDeparturePlatform;
        return this;
    }

    /**
     * Get prognosedDeparturePlatform
     *
     * @return prognosedDeparturePlatform
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PROGNOSED_DEPARTURE_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPrognosedDeparturePlatform() {
        return prognosedDeparturePlatform;
    }


    @JsonProperty(JSON_PROPERTY_PROGNOSED_DEPARTURE_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPrognosedDeparturePlatform(@jakarta.annotation.Nullable String prognosedDeparturePlatform) {
        this.prognosedDeparturePlatform = prognosedDeparturePlatform;
    }

    public Trip plannedDeparturePlatform(@jakarta.annotation.Nullable String plannedDeparturePlatform) {

        this.plannedDeparturePlatform = plannedDeparturePlatform;
        return this;
    }

    /**
     * Get plannedDeparturePlatform
     *
     * @return plannedDeparturePlatform
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PLANNED_DEPARTURE_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPlannedDeparturePlatform() {
        return plannedDeparturePlatform;
    }


    @JsonProperty(JSON_PROPERTY_PLANNED_DEPARTURE_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPlannedDeparturePlatform(@jakarta.annotation.Nullable String plannedDeparturePlatform) {
        this.plannedDeparturePlatform = plannedDeparturePlatform;
    }

    public Trip arrival(@jakarta.annotation.Nullable String arrival) {

        this.arrival = arrival;
        return this;
    }

    /**
     * Get arrival
     *
     * @return arrival
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ARRIVAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getArrival() {
        return arrival;
    }


    @JsonProperty(JSON_PROPERTY_ARRIVAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setArrival(@jakarta.annotation.Nullable String arrival) {
        this.arrival = arrival;
    }

    public Trip plannedArrival(@jakarta.annotation.Nullable String plannedArrival) {

        this.plannedArrival = plannedArrival;
        return this;
    }

    /**
     * Get plannedArrival
     *
     * @return plannedArrival
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PLANNED_ARRIVAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPlannedArrival() {
        return plannedArrival;
    }


    @JsonProperty(JSON_PROPERTY_PLANNED_ARRIVAL)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPlannedArrival(@jakarta.annotation.Nullable String plannedArrival) {
        this.plannedArrival = plannedArrival;
    }

    public Trip prognosedDeparture(@jakarta.annotation.Nullable String prognosedDeparture) {

        this.prognosedDeparture = prognosedDeparture;
        return this;
    }

    /**
     * Get prognosedDeparture
     *
     * @return prognosedDeparture
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PROGNOSED_DEPARTURE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPrognosedDeparture() {
        return prognosedDeparture;
    }


    @JsonProperty(JSON_PROPERTY_PROGNOSED_DEPARTURE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPrognosedDeparture(@jakarta.annotation.Nullable String prognosedDeparture) {
        this.prognosedDeparture = prognosedDeparture;
    }

    public Trip arrivalDelay(@jakarta.annotation.Nullable BigDecimal arrivalDelay) {

        this.arrivalDelay = arrivalDelay;
        return this;
    }

    /**
     * Get arrivalDelay
     *
     * @return arrivalDelay
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ARRIVAL_DELAY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getArrivalDelay() {
        return arrivalDelay;
    }


    @JsonProperty(JSON_PROPERTY_ARRIVAL_DELAY)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setArrivalDelay(@jakarta.annotation.Nullable BigDecimal arrivalDelay) {
        this.arrivalDelay = arrivalDelay;
    }

    public Trip arrivalPlatform(@jakarta.annotation.Nullable String arrivalPlatform) {

        this.arrivalPlatform = arrivalPlatform;
        return this;
    }

    /**
     * Get arrivalPlatform
     *
     * @return arrivalPlatform
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ARRIVAL_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getArrivalPlatform() {
        return arrivalPlatform;
    }


    @JsonProperty(JSON_PROPERTY_ARRIVAL_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setArrivalPlatform(@jakarta.annotation.Nullable String arrivalPlatform) {
        this.arrivalPlatform = arrivalPlatform;
    }

    public Trip prognosedArrivalPlatform(@jakarta.annotation.Nullable String prognosedArrivalPlatform) {

        this.prognosedArrivalPlatform = prognosedArrivalPlatform;
        return this;
    }

    /**
     * Get prognosedArrivalPlatform
     *
     * @return prognosedArrivalPlatform
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PROGNOSED_ARRIVAL_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPrognosedArrivalPlatform() {
        return prognosedArrivalPlatform;
    }


    @JsonProperty(JSON_PROPERTY_PROGNOSED_ARRIVAL_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPrognosedArrivalPlatform(@jakarta.annotation.Nullable String prognosedArrivalPlatform) {
        this.prognosedArrivalPlatform = prognosedArrivalPlatform;
    }

    public Trip plannedArrivalPlatform(@jakarta.annotation.Nullable String plannedArrivalPlatform) {

        this.plannedArrivalPlatform = plannedArrivalPlatform;
        return this;
    }

    /**
     * Get plannedArrivalPlatform
     *
     * @return plannedArrivalPlatform
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PLANNED_ARRIVAL_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getPlannedArrivalPlatform() {
        return plannedArrivalPlatform;
    }


    @JsonProperty(JSON_PROPERTY_PLANNED_ARRIVAL_PLATFORM)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPlannedArrivalPlatform(@jakarta.annotation.Nullable String plannedArrivalPlatform) {
        this.plannedArrivalPlatform = plannedArrivalPlatform;
    }

    public Trip stopovers(@jakarta.annotation.Nullable List<StopOver> stopovers) {

        this.stopovers = stopovers;
        return this;
    }

    public Trip addStopoversItem(StopOver stopoversItem) {
        if (this.stopovers == null) {
            this.stopovers = new ArrayList<>();
        }
        this.stopovers.add(stopoversItem);
        return this;
    }

    /**
     * Get stopovers
     *
     * @return stopovers
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_STOPOVERS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<StopOver> getStopovers() {
        return stopovers;
    }


    @JsonProperty(JSON_PROPERTY_STOPOVERS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setStopovers(@jakarta.annotation.Nullable List<StopOver> stopovers) {
        this.stopovers = stopovers;
    }

    public Trip schedule(@jakarta.annotation.Nullable BigDecimal schedule) {

        this.schedule = schedule;
        return this;
    }

    /**
     * Get schedule
     *
     * @return schedule
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SCHEDULE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getSchedule() {
        return schedule;
    }


    @JsonProperty(JSON_PROPERTY_SCHEDULE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setSchedule(@jakarta.annotation.Nullable BigDecimal schedule) {
        this.schedule = schedule;
    }

    public Trip price(@jakarta.annotation.Nullable Price price) {

        this.price = price;
        return this;
    }

    /**
     * Get price
     *
     * @return price
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PRICE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Price getPrice() {
        return price;
    }


    @JsonProperty(JSON_PROPERTY_PRICE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPrice(@jakarta.annotation.Nullable Price price) {
        this.price = price;
    }

    public Trip operator(@jakarta.annotation.Nullable BigDecimal operator) {

        this.operator = operator;
        return this;
    }

    /**
     * Get operator
     *
     * @return operator
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_OPERATOR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getOperator() {
        return operator;
    }


    @JsonProperty(JSON_PROPERTY_OPERATOR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setOperator(@jakarta.annotation.Nullable BigDecimal operator) {
        this.operator = operator;
    }

    public Trip direction(@jakarta.annotation.Nullable String direction) {

        this.direction = direction;
        return this;
    }

    /**
     * Get direction
     *
     * @return direction
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DIRECTION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getDirection() {
        return direction;
    }


    @JsonProperty(JSON_PROPERTY_DIRECTION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDirection(@jakarta.annotation.Nullable String direction) {
        this.direction = direction;
    }

    public Trip line(@jakarta.annotation.Nullable Line line) {

        this.line = line;
        return this;
    }

    /**
     * Get line
     *
     * @return line
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LINE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Line getLine() {
        return line;
    }


    @JsonProperty(JSON_PROPERTY_LINE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLine(@jakarta.annotation.Nullable Line line) {
        this.line = line;
    }

    public Trip cancelled(@jakarta.annotation.Nullable Boolean cancelled) {

        this.cancelled = cancelled;
        return this;
    }

    /**
     * Get cancelled
     *
     * @return cancelled
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CANCELLED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getCancelled() {
        return cancelled;
    }


    @JsonProperty(JSON_PROPERTY_CANCELLED)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCancelled(@jakarta.annotation.Nullable Boolean cancelled) {
        this.cancelled = cancelled;
    }

    public Trip walking(@jakarta.annotation.Nullable Boolean walking) {

        this.walking = walking;
        return this;
    }

    /**
     * Get walking
     *
     * @return walking
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_WALKING)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getWalking() {
        return walking;
    }


    @JsonProperty(JSON_PROPERTY_WALKING)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setWalking(@jakarta.annotation.Nullable Boolean walking) {
        this.walking = walking;
    }

    public Trip loadFactor(@jakarta.annotation.Nullable String loadFactor) {

        this.loadFactor = loadFactor;
        return this;
    }

    /**
     * Get loadFactor
     *
     * @return loadFactor
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_LOAD_FACTOR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public String getLoadFactor() {
        return loadFactor;
    }


    @JsonProperty(JSON_PROPERTY_LOAD_FACTOR)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setLoadFactor(@jakarta.annotation.Nullable String loadFactor) {
        this.loadFactor = loadFactor;
    }

    public Trip distance(@jakarta.annotation.Nullable BigDecimal distance) {

        this.distance = distance;
        return this;
    }

    /**
     * Get distance
     *
     * @return distance
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DISTANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public BigDecimal getDistance() {
        return distance;
    }


    @JsonProperty(JSON_PROPERTY_DISTANCE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDistance(@jakarta.annotation.Nullable BigDecimal distance) {
        this.distance = distance;
    }

    public Trip _public(@jakarta.annotation.Nullable Boolean _public) {

        this._public = _public;
        return this;
    }

    /**
     * Get _public
     *
     * @return _public
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_PUBLIC)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getPublic() {
        return _public;
    }


    @JsonProperty(JSON_PROPERTY_PUBLIC)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPublic(@jakarta.annotation.Nullable Boolean _public) {
        this._public = _public;
    }

    public Trip transfer(@jakarta.annotation.Nullable Boolean transfer) {

        this.transfer = transfer;
        return this;
    }

    /**
     * Get transfer
     *
     * @return transfer
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_TRANSFER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getTransfer() {
        return transfer;
    }


    @JsonProperty(JSON_PROPERTY_TRANSFER)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setTransfer(@jakarta.annotation.Nullable Boolean transfer) {
        this.transfer = transfer;
    }

    public Trip cycle(@jakarta.annotation.Nullable Cycle cycle) {

        this.cycle = cycle;
        return this;
    }

    /**
     * Get cycle
     *
     * @return cycle
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CYCLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Cycle getCycle() {
        return cycle;
    }


    @JsonProperty(JSON_PROPERTY_CYCLE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCycle(@jakarta.annotation.Nullable Cycle cycle) {
        this.cycle = cycle;
    }

    public Trip alternatives(@jakarta.annotation.Nullable List<Alternative> alternatives) {

        this.alternatives = alternatives;
        return this;
    }

    public Trip addAlternativesItem(Alternative alternativesItem) {
        if (this.alternatives == null) {
            this.alternatives = new ArrayList<>();
        }
        this.alternatives.add(alternativesItem);
        return this;
    }

    /**
     * Get alternatives
     *
     * @return alternatives
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ALTERNATIVES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<Alternative> getAlternatives() {
        return alternatives;
    }


    @JsonProperty(JSON_PROPERTY_ALTERNATIVES)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setAlternatives(@jakarta.annotation.Nullable List<Alternative> alternatives) {
        this.alternatives = alternatives;
    }

    public Trip polyline(@jakarta.annotation.Nullable FeatureCollection polyline) {

        this.polyline = polyline;
        return this;
    }

    /**
     * Get polyline
     *
     * @return polyline
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_POLYLINE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public FeatureCollection getPolyline() {
        return polyline;
    }


    @JsonProperty(JSON_PROPERTY_POLYLINE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setPolyline(@jakarta.annotation.Nullable FeatureCollection polyline) {
        this.polyline = polyline;
    }

    public Trip remarks(@jakarta.annotation.Nullable List<StopOverRemarksInner> remarks) {

        this.remarks = remarks;
        return this;
    }

    public Trip addRemarksItem(StopOverRemarksInner remarksItem) {
        if (this.remarks == null) {
            this.remarks = new ArrayList<>();
        }
        this.remarks.add(remarksItem);
        return this;
    }

    /**
     * Get remarks
     *
     * @return remarks
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_REMARKS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public List<StopOverRemarksInner> getRemarks() {
        return remarks;
    }


    @JsonProperty(JSON_PROPERTY_REMARKS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setRemarks(@jakarta.annotation.Nullable List<StopOverRemarksInner> remarks) {
        this.remarks = remarks;
    }

    public Trip currentLocation(@jakarta.annotation.Nullable Location currentLocation) {

        this.currentLocation = currentLocation;
        return this;
    }

    /**
     * Get currentLocation
     *
     * @return currentLocation
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CURRENT_LOCATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Location getCurrentLocation() {
        return currentLocation;
    }


    @JsonProperty(JSON_PROPERTY_CURRENT_LOCATION)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCurrentLocation(@jakarta.annotation.Nullable Location currentLocation) {
        this.currentLocation = currentLocation;
    }

    public Trip departurePrognosisType(@jakarta.annotation.Nullable PrognosisType departurePrognosisType) {

        this.departurePrognosisType = departurePrognosisType;
        return this;
    }

    /**
     * Get departurePrognosisType
     *
     * @return departurePrognosisType
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_DEPARTURE_PROGNOSIS_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public PrognosisType getDeparturePrognosisType() {
        return departurePrognosisType;
    }


    @JsonProperty(JSON_PROPERTY_DEPARTURE_PROGNOSIS_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setDeparturePrognosisType(@jakarta.annotation.Nullable PrognosisType departurePrognosisType) {
        this.departurePrognosisType = departurePrognosisType;
    }

    public Trip arrivalPrognosisType(@jakarta.annotation.Nullable PrognosisType arrivalPrognosisType) {

        this.arrivalPrognosisType = arrivalPrognosisType;
        return this;
    }

    /**
     * Get arrivalPrognosisType
     *
     * @return arrivalPrognosisType
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_ARRIVAL_PROGNOSIS_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public PrognosisType getArrivalPrognosisType() {
        return arrivalPrognosisType;
    }


    @JsonProperty(JSON_PROPERTY_ARRIVAL_PROGNOSIS_TYPE)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setArrivalPrognosisType(@jakarta.annotation.Nullable PrognosisType arrivalPrognosisType) {
        this.arrivalPrognosisType = arrivalPrognosisType;
    }

    public Trip checkin(@jakarta.annotation.Nullable Boolean checkin) {

        this.checkin = checkin;
        return this;
    }

    /**
     * Get checkin
     *
     * @return checkin
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_CHECKIN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Boolean getCheckin() {
        return checkin;
    }


    @JsonProperty(JSON_PROPERTY_CHECKIN)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setCheckin(@jakarta.annotation.Nullable Boolean checkin) {
        this.checkin = checkin;
    }

    public Trip scheduledDays(@jakarta.annotation.Nullable Map<String, Boolean> scheduledDays) {

        this.scheduledDays = scheduledDays;
        return this;
    }

    public Trip putScheduledDaysItem(String key, Boolean scheduledDaysItem) {
        if (this.scheduledDays == null) {
            this.scheduledDays = new HashMap<>();
        }
        this.scheduledDays.put(key, scheduledDaysItem);
        return this;
    }

    /**
     * Get scheduledDays
     *
     * @return scheduledDays
     */
    @jakarta.annotation.Nullable
    @JsonProperty(JSON_PROPERTY_SCHEDULED_DAYS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

    public Map<String, Boolean> getScheduledDays() {
        return scheduledDays;
    }


    @JsonProperty(JSON_PROPERTY_SCHEDULED_DAYS)
    @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
    public void setScheduledDays(@jakarta.annotation.Nullable Map<String, Boolean> scheduledDays) {
        this.scheduledDays = scheduledDays;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Trip trip = (Trip) o;
        return Objects.equals(this.id, trip.id) &&
                Objects.equals(this.origin, trip.origin) &&
                Objects.equals(this.destination, trip.destination) &&
                Objects.equals(this.departure, trip.departure) &&
                Objects.equals(this.plannedDeparture, trip.plannedDeparture) &&
                Objects.equals(this.prognosedArrival, trip.prognosedArrival) &&
                Objects.equals(this.departureDelay, trip.departureDelay) &&
                Objects.equals(this.departurePlatform, trip.departurePlatform) &&
                Objects.equals(this.prognosedDeparturePlatform, trip.prognosedDeparturePlatform) &&
                Objects.equals(this.plannedDeparturePlatform, trip.plannedDeparturePlatform) &&
                Objects.equals(this.arrival, trip.arrival) &&
                Objects.equals(this.plannedArrival, trip.plannedArrival) &&
                Objects.equals(this.prognosedDeparture, trip.prognosedDeparture) &&
                Objects.equals(this.arrivalDelay, trip.arrivalDelay) &&
                Objects.equals(this.arrivalPlatform, trip.arrivalPlatform) &&
                Objects.equals(this.prognosedArrivalPlatform, trip.prognosedArrivalPlatform) &&
                Objects.equals(this.plannedArrivalPlatform, trip.plannedArrivalPlatform) &&
                Objects.equals(this.stopovers, trip.stopovers) &&
                Objects.equals(this.schedule, trip.schedule) &&
                Objects.equals(this.price, trip.price) &&
                Objects.equals(this.operator, trip.operator) &&
                Objects.equals(this.direction, trip.direction) &&
                Objects.equals(this.line, trip.line) &&
                Objects.equals(this.cancelled, trip.cancelled) &&
                Objects.equals(this.walking, trip.walking) &&
                Objects.equals(this.loadFactor, trip.loadFactor) &&
                Objects.equals(this.distance, trip.distance) &&
                Objects.equals(this._public, trip._public) &&
                Objects.equals(this.transfer, trip.transfer) &&
                Objects.equals(this.cycle, trip.cycle) &&
                Objects.equals(this.alternatives, trip.alternatives) &&
                Objects.equals(this.polyline, trip.polyline) &&
                Objects.equals(this.remarks, trip.remarks) &&
                Objects.equals(this.currentLocation, trip.currentLocation) &&
                Objects.equals(this.departurePrognosisType, trip.departurePrognosisType) &&
                Objects.equals(this.arrivalPrognosisType, trip.arrivalPrognosisType) &&
                Objects.equals(this.checkin, trip.checkin) &&
                Objects.equals(this.scheduledDays, trip.scheduledDays);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, origin, destination, departure, plannedDeparture, prognosedArrival, departureDelay, departurePlatform, prognosedDeparturePlatform, plannedDeparturePlatform, arrival, plannedArrival, prognosedDeparture, arrivalDelay, arrivalPlatform, prognosedArrivalPlatform, plannedArrivalPlatform, stopovers, schedule, price, operator, direction, line, cancelled, walking, loadFactor, distance, _public, transfer, cycle, alternatives, polyline, remarks, currentLocation, departurePrognosisType, arrivalPrognosisType, checkin, scheduledDays);
    }

    @Override
    public String toString() {
        String sb = "class Trip {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    origin: " + toIndentedString(origin) + "\n" +
                "    destination: " + toIndentedString(destination) + "\n" +
                "    departure: " + toIndentedString(departure) + "\n" +
                "    plannedDeparture: " + toIndentedString(plannedDeparture) + "\n" +
                "    prognosedArrival: " + toIndentedString(prognosedArrival) + "\n" +
                "    departureDelay: " + toIndentedString(departureDelay) + "\n" +
                "    departurePlatform: " + toIndentedString(departurePlatform) + "\n" +
                "    prognosedDeparturePlatform: " + toIndentedString(prognosedDeparturePlatform) + "\n" +
                "    plannedDeparturePlatform: " + toIndentedString(plannedDeparturePlatform) + "\n" +
                "    arrival: " + toIndentedString(arrival) + "\n" +
                "    plannedArrival: " + toIndentedString(plannedArrival) + "\n" +
                "    prognosedDeparture: " + toIndentedString(prognosedDeparture) + "\n" +
                "    arrivalDelay: " + toIndentedString(arrivalDelay) + "\n" +
                "    arrivalPlatform: " + toIndentedString(arrivalPlatform) + "\n" +
                "    prognosedArrivalPlatform: " + toIndentedString(prognosedArrivalPlatform) + "\n" +
                "    plannedArrivalPlatform: " + toIndentedString(plannedArrivalPlatform) + "\n" +
                "    stopovers: " + toIndentedString(stopovers) + "\n" +
                "    schedule: " + toIndentedString(schedule) + "\n" +
                "    price: " + toIndentedString(price) + "\n" +
                "    operator: " + toIndentedString(operator) + "\n" +
                "    direction: " + toIndentedString(direction) + "\n" +
                "    line: " + toIndentedString(line) + "\n" +
                "    cancelled: " + toIndentedString(cancelled) + "\n" +
                "    walking: " + toIndentedString(walking) + "\n" +
                "    loadFactor: " + toIndentedString(loadFactor) + "\n" +
                "    distance: " + toIndentedString(distance) + "\n" +
                "    _public: " + toIndentedString(_public) + "\n" +
                "    transfer: " + toIndentedString(transfer) + "\n" +
                "    cycle: " + toIndentedString(cycle) + "\n" +
                "    alternatives: " + toIndentedString(alternatives) + "\n" +
                "    polyline: " + toIndentedString(polyline) + "\n" +
                "    remarks: " + toIndentedString(remarks) + "\n" +
                "    currentLocation: " + toIndentedString(currentLocation) + "\n" +
                "    departurePrognosisType: " + toIndentedString(departurePrognosisType) + "\n" +
                "    arrivalPrognosisType: " + toIndentedString(arrivalPrognosisType) + "\n" +
                "    checkin: " + toIndentedString(checkin) + "\n" +
                "    scheduledDays: " + toIndentedString(scheduledDays) + "\n" +
                "}";
        return sb;
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

